### ISSUE TITLE
Update of ZH_CN translation language file for v2.3.6

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#1]
The language file on your official web site was probably machine translated.
There were quite a few places improperly translated and the recently added new strings were left untranslated either.
I've therefore manually translated the language file from scratch. Here's the po file.
[BowPad_zh-CN.zip](https://github.com/stefankueng/BowPad/files/1866371/BowPad_zh-CN.zip)

How can I test it?

**Comment by stefankueng** [comment]
To test it, you have to build BowPad using NAnt:
$ nant
and then
$ nant lang
to build the language files.

Attaching the two language files.
[zh-CN.zip](https://github.com/stefankueng/BowPad/files/1868947/zh-CN.zip)

**Comment by wmjordan** [comment]
I'd localized quite dozens of applications before.
Never expected so much work is required to take the test.
Why not just use XML lang files and patch the interface dynamically?
Maybe, even better, using satellite resource files and an accompanied _Resource Hacker_ (or other professional localization programs) can help the translators to do the job too.

Thank you for making the lang files. I revised the translation after a test.
[BowPad_zh-CN.zip](https://github.com/stefankueng/BowPad/files/1869859/BowPad_zh-CN.zip)

**Comment by stefankueng** [comment]
The .lang files are actually resource dlls, so you could use Resource Hacker if you want to.
[BowPad_zh-CN.zip](https://github.com/stefankueng/BowPad/files/1873066/BowPad_zh-CN.zip)

**Comment by stefankueng** [comment]
update the web page.
