### ISSUE TITLE
Line end LF may suddenly change to Windows CR+LF

### ISSUE THREAD

**Issue by CofeeSap** [stefankueng/BowPad#10]
It can happen even if the file is from a linux machine.

I use Bowpad in WinScp.  For editing config files it's not really a big issue but bash scripts won't run if line endings are not unix.

**Comment by stefankueng** [comment]
The eol is detected when loading a file.
If the file contains only LF, then LF it is. But if it contains just one CRLF then the format is detected as Windows line endings.

**Comment by CofeeSap** [comment]
Is there possibility to enforce the user's choice of eol so the file is always converted to the same format? 

I think giving control to the user instead of the files deciding which format to use is better as it makes the output consistent and predictable.

Thanks!

**Comment by stefankueng** [comment]
So I've double checked: BowPad does not change the EOL automatically. The EOL detection when loading a file only applies when you edit the files: if you press enter, the detected EOL is inserted.
But the other line endings won't change.

However, I think you're problem is not with BowPad but with the settings in WinSCP.
You have to configure it correctly:
https://winscp.net/eng/docs/ui_login_environment
And there are other options you might have to change. From a quick websearch for "WinSCP EOL", this turned up as well:

> The key is to un-tick an option in the Editors tab that reads 'Force text file mode for files edited in external editor' which can be found when you click 'Edit' on your external text editor. Hope it helps others :)
