### ISSUE TITLE
Incomplete search result context

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#100]
Please take a look at the following screenshot.
I was searching the keyword "color" in a file.
The match in the list (line 42) was incompletely displayed, only a small part of the line was shown. That line was not so long, more content was expected shown.

<img width="539" alt="shot" src="https://user-images.githubusercontent.com/12182730/97935880-cae11700-1db4-11eb-9f94-cd7d292b30a6.PNG">

Here's the code snippet which reproduces the issue.

````c#
			static Dictionary<string, SolidColorBrush> GetBrushes() {
				var c = Array.FindAll(typeof(WpfBrushes).GetProperties(), p => p.PropertyType == typeof(SolidColorBrush));
				var d = new Dictionary<string, SolidColorBrush>(c.Length, StringComparer.OrdinalIgnoreCase);
				foreach (var item in c) {
					d.Add(item.Name, item.GetValue(null) as SolidColorBrush);
				}
				return d;
			}
````

**Comment by stefankueng** [comment]
currently, all lines longer than 100 chars are shortened for the results list. And that line is 110 char long.
I'll change that to 255 chars...

**Comment by wmjordan** [comment]
It seems that the shorten algorithm can be improved:
The above line was 110 char long, and any line longer than 100 chars were supposed to be shortened, so the shortened line could still have 100 chars. However, on the above screenshot we could see that the shortened line did not contain 100 chars--more characters were expected to be displayed.

Nevertheless, it is good to increase the amount to 255, since nowadays most users have bigger monitors which can display more content on the screen.
