### ISSUE TITLE
Assigning shortcut to plugin command

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#103]
Is it possible to assign shortcuts to specific plugin commands?
For instance, Ctrl+1 executes plugin A, Ctrl+2 executes plugin B...

**Comment by stefankueng** [comment]
Yes, just like to any other command: the command name is the name of the plugin.
(main menu, "configure shortcuts")

**Comment by wmjordan** [comment]
Thank you for the information!
