### ISSUE TITLE
Could not compile source code after upgrading VS to 16.8

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#104]
I got the following error messages when compiling the latest source code with WinSDK 10.0.17763.

<img width="905" alt="新的图片" src="https://user-images.githubusercontent.com/12182730/99135367-dbb74580-265c-11eb-890d-c981c0e25901.png">

**Comment by stefankueng** [comment]
strange, it compiles fine for me. Even if I set the SDK to use to 10.0.17763.
I found this: https://help.appveyor.com/discussions/problems/26088-checkforduplicateentries-is-not-a-member-of-microsoftwrldetails
but they don't really have a solution apart from using a newer SDK.

**Comment by stefankueng** [comment]
can you install a newer SDK and see if that helps?
![image](https://user-images.githubusercontent.com/665591/99142121-68103b00-2652-11eb-89ea-d72ba30c0817.png)

**Comment by wmjordan** [comment]
That's weird. Before upgrading VS, everything was fine. The compilation was very easy for guys like me which know little about C++.

OMG, it is really terrible. I just found that my offline books in the Help Viewer was completely erased after the upgrade. What had those VS guys done?

**Comment by wmjordan** [comment]
I checked the definition in the module.h and found that the `CheckForDuplicateEntries` was conditionally defined.

````C
#ifdef _DEBUG
template<typename T>
inline void CheckForDuplicateEntries(const CreatorMap** firstEntry, const CreatorMap** lastEntry, T validateEntry) throw()
{
    ....
}
#endif // _DEBUG
````

Since I knew little about C++,  every time I compiled the code was under the `Release` configuration. If I switch to the `Debug` configuration, it compiled successfully. Please try the `Release` configuration and see whether the code compiles on your side.

**Comment by stefankueng** [comment]
yes, it builds fine for me for release builds as well. Both for x64 and x86.

**Comment by wmjordan** [comment]
My VS was 16.8.1. How about yours?

**Comment by stefankueng** [comment]
mine too.

**Comment by stefankueng** [comment]
ok, I get the same error if I switch back to SDK 10.0.17763 and a release build...

**Comment by wmjordan** [comment]
Thanks for taking your time to address this.

I searched for "Details::CheckForDuplicateEntries" in GitHub code and found that someone else had encountered that as well, and his solution was adding a conditional directive there!

````C
#ifdef _DEBUG
        Details::CheckForDuplicateEntries((GetFirstEntryPointer() + 1), GetMidEntryPointer(),
            [](const Details::CreatorMap* entry, const Details::CreatorMap* entry2) -> void {
                __WRL_ASSERT__(entry->activationId.clsid != entry2->activationId.clsid && "Duplicate CLSID!");
            }
        );

        Details::CheckForDuplicateEntries((GetMidEntryPointer() + 1), GetLastEntryPointer(),
            [](const Details::CreatorMap* entry, const Details::CreatorMap* entry2) -> void {
                __WRL_ASSERT__(::wcscmp((entry->activationId.getRuntimeName)(), (entry2->activationId.getRuntimeName)()) != 0 && "Duplicate runtime class name!");
            }
        );
#endif
````

**Comment by stefankueng** [comment]
that's exactly what the next SDK version did:
![image](https://user-images.githubusercontent.com/665591/99144209-428c2d00-2664-11eb-9a6f-8b600f6693da.png)

**Comment by wmjordan** [comment]
Thank you for verifying that.
I added those lines and it compiled.

I will stick to SDK 17763 and see whether it works later.
