### ISSUE TITLE
Scripting API to get current lexer

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#105]
There's an API to set lexer, but no API to get lexer lang.

````jscript
// sets up the configured lexer for the specified language
BowPad.SetupLexerForLang("html");
````

**Comment by stefankueng** [comment]
you could use SCI_GETLEXER which returns an int identifying the lexer. See the properties.ini file, search for "Lexer=" to get the ints for each lexer.

**Comment by stefankueng** [comment]
that is:
` BowPad.SciGetLexer()`
or you could use the SciLexer function:
```
 BowPad.SciLexer = 2;
 var lexer = BowPad.SciLexer;

```

**Comment by wmjordan** [comment]
I tried to use the active lexer from the active document and apply it to the newly created document in the _search selection_ plugin. It does not seem to work.

The code of the Execute function is listed below:
````javascript
function Execute()
{
    var selStart = BowPad.SciGetSelectionStart();
    var selEnd = BowPad.SciGetSelectionEnd();
    if (selStart == selEnd)
        return false;
    if (BowPad.SciLineFromPosition(selStart) != BowPad.SciLineFromPosition(selEnd))
    {
        BowPad.alert("Multiline selection is not yet supported.");
	return false;
    }
    
    var selText = BowPad.SciGetSelText();
    var extractedLines = [];
    var docLen = BowPad.SciGetLength();
    var foundPos = BowPad.SciFindText(0, 0, docLen, selText).toArray()[0];
    var lexer = BowPad.SciLexer;

    while (foundPos >= 0)
    {
        var line = BowPad.SciLineFromPosition(foundPos);
        var lineText = BowPad.SciGetLine(line);
        extractedLines.push(lineText);
        foundPos = BowPad.SciFindText(0, BowPad.SciPositionFromLine(line+1), docLen, selText).toArray()[0];
    }
    
    if (extractedLines.length > 1) {
        BowPad.OpenNewTab();
        BowPad.SciInsertText(0, extractedLines.join(""));
        BowPad.SciEmptyUndoBuffer();
        BowPad.SciSetSavePoint();
	BowPad.SciLexer = lexer;
    }
    else {
	BowPad.alert("Only a single instance is found in document.");
    }
    return true;
}
````

**Comment by stefankueng** [comment]
ah, of course: that only sets the lexer, but the styling is still missing. In that case you really need a way to get the current lexer language string.

**Comment by stefankueng** [comment]
now, use:
`var lexer = BowPad.GetCurrentLanguage();`
and then
`BowPad.SetupLexerForLang(lexer);`

**Comment by wmjordan** [comment]
Thank you very much for the quick fix. But I'd got to find some way to have the code compiled first.

**Comment by wmjordan** [comment]
OK. There's an updated SearchSelection plugin which utilizes the new function.

[SearchSelection.zip](https://github.com/stefankueng/BowPad/files/5540441/SearchSelection.zip)
