### ISSUE TITLE
when file changed, Load session on start work no good.

### ISSUE THREAD

**Issue by jeleesky** [stefankueng/BowPad#107]
enable Load session on start.
open a file and edit it, then exit without save.
open the file with other editor, such as notepad++, modify it and save it.
startup bowpad, the old version of the file is load. I think the new version will be load just like notepad++.
thanks.

**Comment by stefankueng** [comment]
I'm guessing "auto-save on close" is also active?

**Comment by jeleesky** [comment]
yes,   the "auto-save on close" option  is active, and I can not deactive it.
when close the app, the file is saved in backup folder, the file itself is not saved.
I think that when the app is started it should check the file itself  to see if  it has been modified, if modified, the app should discard the backuped file and load the file itself. 
Best Regards.

**Comment by stefankueng** [comment]
the problem that "auto-save on close" can not be deactivated is already fixed for the upcoming release.
As for your suggestion -> working on it.

**Comment by jeleesky** [comment]
I download the version 2.6.5 and try it，the issue has been fixed, thanks!
