### ISSUE TITLE
New plugin to calculate arithmetic expressions

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#108]
I've written a plugin to do some math in BowPad.

For instance, new document (or selection)
````
(1+2)*3/4
````
or expression mixed with literal text
````
(mine 1 + Andy 2) * 3/4 ratio
````
Run Calculate.

Outputs
````
Eval expression:
(1+2)*3/4
Result:
2.25
````

The implementation is quite stupid. But it works in many cases.

[Calculate.zip](https://github.com/stefankueng/BowPad/files/5572707/Calculate.zip)

**Comment by stefankueng** [comment]
thanks!

**Comment by wmjordan** [comment]
I updated the plugin to better tolerate irrelevant characters in the expressions. 
For instance, execute the plugin against the following text yields -300:
````text
My salary $10000
Lottery ticket bonus $100*2
- credit card deb $9000
- food $1000
- traffic $500
````

The new version also converts full-width numbers, which are usually used in somewhere by Chinese, Japanese and Korean users, to half-width counterparts.
It also automatically replaces the expression with the results.
To obtain previous behavior which opens a new document window, press Shift key before evaluate the expression.

[Calculate.zip](https://github.com/stefankueng/BowPad/files/6197602/Calculate.zip)

**Comment by wmjordan** [comment]
The previous version had a bug when calculating fraction numbers, for instance `33*0.03` it gave a wrong result.

Please use this one.
[Calculate.zip](https://github.com/stefankueng/BowPad/files/6248481/Calculate.zip)
