### ISSUE TITLE
Replace All on invalid regex causes lockup

### ISSUE THREAD

**Issue by bhank** [stefankueng/BowPad#11]
* Open BowPad (2.3.8.1979, on Windows 7)
* Find/Replace
* Search for: (
* Check the "Regex mode" box
* Click "Replace All"

The app locks up. This doesn't happen when doing "Find" or "Replace", just "Replace All".

**Comment by stefankueng** [comment]
Marking as duplicate of the newly opened #42 even though it's the other way around.
