### ISSUE TITLE
add script command to get the keyboard state

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#110]
Is it possible to detect whether a user has pressed the Ctrl, Shift or Alt key when he executes a plugin?

If so, we can have difference behaviors for each plugin, determined by keyboard modifiers.

**Comment by stefankueng** [comment]
implement like this:
`var isPressed = BowPad.GetKeyState(keyvalue);`

with 'keyvalue' being the key being tested. These values are the VK_* values from the windows header:
https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by stefankueng** [comment]
```
	var ctrl = BowPad.GetKeyState(0x11);
	var shift = BowPad.GetKeyState(0x10);
	BowPad.alert("shift = " + shift + "\nctrl = " + ctrl);

```
