### ISSUE TITLE
Feature Request: Consistent Dropdown List View for opened file  

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#114]
In Bowpad, we can list all opened file and select any showing as current through goto tabs or tabbar button. But I see different view style such as 
![image](https://user-images.githubusercontent.com/28701482/100760870-30b0d500-342d-11eb-8ddc-73eb9637aff8.png)

**Comment by stefankueng** [comment]
that's because from the ribbon, it's done with a dropdown collection which is not available for the tab bar button where a menu is used. And since the menu is not available from the ribbon, they look slightly different.
Sorry, that won't change.

**Comment by kitepad** [comment]
I investigate source code in cmdtablist.cpp, I found some interesting :
1.  change HRESULT hr = CAppUtils::AddStringItem(collection, text.c_str(), -1, pImg); to HRESULT hr = CAppUtils::AddStringItem(collection, text.c_str(), -1, nullptr); when you click tabs, you can get similar view style 
  
![image](https://user-images.githubusercontent.com/28701482/100819280-cc226400-3486-11eb-8020-9ac9d5156508.png)

2. Some issues still exist, check mark not redraw in time when open/close document, you can trying to minimize bp and restore to see check mark draw correctly.

**Comment by kitepad** [comment]
All is ok after modified as below (but I don't know why and whether is right solution ): 
void CCmdTabList::ScintillaNotify(SCNotification* /*pScn*/)
{
    InvalidateUICommand(UI_INVALIDATIONS_VALUE, NULL);
}

**Comment by kitepad** [comment]
cmdCodeStyle.cpp can modify by this approach , but need to modify bowpad.xml to change dropdown's menu layout to VerticalMenuLayout.

**Comment by kitepad** [comment]
CmdLoadEncoding.cpp is same : CAppUtils::AddStringItem(pCollection, cp.name.c_str(), cp.category, nullptr);

CmdLanguage and CmdSpellCheckLang is same , but need to modify multi statement.

Finally, all of menu with check mark will have same style, include popup menu.
