### ISSUE TITLE
Request color options for selection metadata

### ISSUE THREAD

**Issue by barkoder** [stefankueng/BowPad#115]
Red text on a dark brown background is difficult to read.
![1](https://user-images.githubusercontent.com/70430094/100931489-83989400-34e2-11eb-9c83-a28ed1d592ee.png)

and

Orange text on a white background is also difficult to read.
![2](https://user-images.githubusercontent.com/70430094/100931769-df631d00-34e2-11eb-809d-4df8664586fb.png)

I would appreciate a "Blue text on white background" in dark mode and a "Yellow text on Brown background" in regular mode for the selection metadata or ideally an option to assign my own high contrast hex color values in settings.

Thank you.

**Comment by stefankueng** [comment]
what version are you using? Because the colors don't match what I got here.

**Comment by barkoder** [comment]
Upon further inspection, it's my Windows Desktop "dark" theme that's causing the color change in Bowpad. Reverting it back to the regular default "bright" Windows theme fixes the font color reading difficulty issues that I have with Bowpad.


But unfortunately, I really like my Windows Dark theme. Is there a way to have Bowpad ignore my Windows dark theme?

I am using version 2.6.5

**Comment by stefankueng** [comment]
I'll just not use colors when in high-contrast mode.
