### ISSUE TITLE
File encoding not saved correctly.

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#116]
In 2.6.5 portable:

Step 1: open a file and encoding is shown as ANSI.
Step 2: convert encoding to utf-8
Step 3: save file/close file.
step 4: reopen file. 

Expected result: file encoding should shown as UTF-8.
Actually result: file encoding shown as ANSI. (ANSI == UTF-8 ?)

Other encodings are right.

**Comment by stefankueng** [comment]
if a file only contains chars in the range 32-127 (i.e. only 'English' characters) then ANSI==UTF8, so in that case converting to utf8 actually doesn't change anything.
But you can configure that BP treats such files as utf8 by default: Button "New" in the 'File' section, click on the arrow. In the submenu you'll see 'Set defaults'
