### ISSUE TITLE
icon for bowpad

### ISSUE THREAD

**Issue by somratking420** [stefankueng/BowPad#12]
hi @stefankueng, I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by stefankueng** [comment]
Hi @somratking420.
Thanks for your offer. The current icon was made by me, and as you can clearly see I'm not very good at it. So if you can create a better one I'm all for it.

**Comment by somratking420** [comment]
Hello,
Good Day, i make a logo icon for your project.I make a 2 logo for you.Which logo do you like? If you want to use this logo in your project, then comment below, I will give you the source file.![bowpad-01](https://user-images.githubusercontent.com/40878798/42723164-ad5c682e-877a-11e8-976d-2731e1d15f76.jpg)

**Comment by stefankueng** [comment]
Thanks for the icons.
But if I may make some comments:

- Both icons don't have anything that resembles a bowtie. And I think they should. You can read why it's named BowPad here: https://tools.stefankueng.com/BowPad.html
- the colors in icon A are too bright for my taste.
- the colors in icon B are hard to look at. And color blind people couldn't make out anything in there.

**Comment by somratking420** [comment]
@stefankueng, any idia for your logo.plezz tell me.

**Comment by stefankueng** [comment]
look at the existing logo. Perhaps a better looking bowtie?
Or if you want to create better icons for the ribbon buttons, that would be great too.

**Comment by wmjordan** [comment]
I'd told my work fellows to "open that bowtie", quite sometime ago.
Please keep that bowtie on the icon. And I think the original icon is quite pleased to look at. No need to change it.

**Comment by GitHubRulesOK** [comment]
Personally think its ok  (but a bit dark) 
Simplistic is good for 16x16 icons however for reinforcing the brand could have some text at say 32x32 upwards
![bowpad-logo32](https://user-images.githubusercontent.com/12754913/44310062-cf7da880-a3bf-11e8-8d2a-0c91dad4289e.png)
![bowpad-logo256](https://user-images.githubusercontent.com/12754913/44310064-d5738980-a3bf-11e8-96da-068e5e431069.png)
May be better centred but needs to be "square" characters for scaling

**Comment by mediazombie** [comment]
Hi, I have another suggestion for a new icon.
![bowpad256](https://user-images.githubusercontent.com/4390082/44452940-22da3b80-a5f8-11e8-9130-22665943d643.png)

**Comment by mediazombie** [comment]
And here the icon in different resolutions and the original ai format.

[BowPad.zip](https://github.com/stefankueng/BowPad/files/2309495/BowPad.zip)

**Comment by GitHubRulesOK** [comment]
16x16 may benefit from minor sharpening (a pixel tweak or two)  since rounding down from source can add a bit of fuzzyness
![bowpad16](https://user-images.githubusercontent.com/12754913/44493782-dc68f900-a658-11e8-9320-9cc93e14dcf9.png)

**Comment by wmjordan** [comment]
I like @mediazombie 's design which has a bowtie and its flat style mixes well with other applications nowadays.

**Comment by wmjordan** [comment]
The original icon, I think is still the best for me, especially when it is scaled down even to 16*16, that the bowtie stands out of other icons very obviously.

**Comment by stefankueng** [comment]
I also like the icon from @mediazombie. But as mentioned the 16x16 icon needs a little tweaking.
And of course, we would also need a similar icon for the document icon.
See the original icons:
![bowpad icon](https://user-images.githubusercontent.com/665591/44537638-9ca91c80-a6ff-11e8-8984-8ff3d755453e.png)
![bowpad doc icon](https://user-images.githubusercontent.com/665591/44537641-9d41b300-a6ff-11e8-8739-56c0ecb35b3d.png)

**Comment by stefankueng** [comment]
looks very good. But can you center the bow vertically? Right now it looks a little off since it's in the bottom half.

**Comment by GitHubRulesOK** [comment]
Personally I thought it was good Artistic License (implying a bow tie on a rectangular style head)
![bow](https://user-images.githubusercontent.com/12754913/45057753-002f3480-b086-11e8-8300-e287a2ec9449.png)

**Comment by mediazombie** [comment]
Now the bowtie is vertically centered. Hope it is now like as requested from @stefankueng?
![bowpad_v2_16](https://user-images.githubusercontent.com/4390082/45146018-47badb00-b1c2-11e8-8c40-465381725f13.png)
![bowpad_v2_32](https://user-images.githubusercontent.com/4390082/45146022-4be6f880-b1c2-11e8-8572-3d6c796911b7.png)
![bowpad_v2_64](https://user-images.githubusercontent.com/4390082/45146030-4f7a7f80-b1c2-11e8-8d14-dd86f6e52f65.png)
[BowPad_v2.zip](https://github.com/stefankueng/BowPad/files/2356253/BowPad_v2.zip)

**Comment by stefankueng** [comment]
Perfect!
Now we need just the one for the documents and I'll make a new build...

**Comment by mediazombie** [comment]
Here is the first Version of the Document Icon... hope it is okay?
![bowpad_doc_16](https://user-images.githubusercontent.com/4390082/45232324-4f1bda80-b2cf-11e8-8993-0b7fb4e747c4.png)
![bowpad_doc_32](https://user-images.githubusercontent.com/4390082/45232331-53e08e80-b2cf-11e8-8913-ec68f48757a3.png)
![bowpad_doc_64](https://user-images.githubusercontent.com/4390082/45232336-580cac00-b2cf-11e8-8ca5-461e04a432d7.png)
[BowPad_Doc.zip](https://github.com/stefankueng/BowPad/files/2361839/BowPad_Doc.zip)

**Comment by stefankueng** [comment]
Yes, that's very nice!
Can you please also attach an svg of the document icon?

**Comment by mediazombie** [comment]
The svg should be included in the zip file. ;)

**Comment by stefankueng** [comment]
Ah yes! Sorry I missed that.
Now I just need the pngs in the size 128x128 and 256x256 as well. For both the normal and the doc icon.
