### ISSUE TITLE
Bowpad draws documents twice creating a flicker effect.

### ISSUE THREAD

**Issue by gmcode** [stefankueng/BowPad#121]
To reproduce.

1. Open bowpad and close all documents but ensure session autoload is on.
2. Open MainWindow.cpp and page down a few pages, e.g. past all the comments to the last #include (on a 1920x1080 screen)
3. Restart bowpad. Observe how bowpad draws page 1 of the document before then redrawing the rest.

You may need to restart bowpad several times to see the flickering clearly. It's more visible on low end graphics cards or when the machine is busy. In other situations, you may not notice a problem at all.

The problem may be happening because bowpad is opening the document then restoring the current position late in the process. It needs to do it earlier I think. Perhaps moving the position restoration code into the main document loading code and passing a flag to request the position be loaded. This would seem like it might fix the problem by setting the position early and also keep related code document opening code together and improve the API. Fixing this may also address other problems or help performance by reducing redundant redraws, but I can't be sure.

**Comment by stefankueng** [comment]
a flicker that's barely noticeable or only on low end graphics cards is not really an issue, at least not for me.

**Comment by gmcode** [comment]
I usually find that fixing these kind of issues is worth it because it reveals other bugs and finding the unexpected code interactions that cause these problems can be interesting and it can lead to cleaner code if fixed so other issues don't stack on it. But if it doesn't interest you that's fine, I can understand that. But perhaps keep it open, maybe somebody else will look at it then?

fyi my card is an intel optimus hd4000 which is typical of many older laptops, but it has a beefy quad core processor. I'm not sure what the typical bowpad user has for a graphics card, but the flickering might be worse for some people and better for others.
