### ISSUE TITLE
Feature Request: Disabling some syntax types

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#128]
Nowadays BowPad has supported many file types--actually a bit TOO many to me.
I guess that I would not have a chance to handle the _Pike_ file type in my life.

Is it possible to disable some of them?

**Comment by stefankueng** [comment]
how would an UI for this look like?
Maybe it's enough to use another control than the flow layout?

**Comment by wmjordan** [comment]
Maybe we don't need to add any interface element. We can utilize extensions text box in the Configure Styles dialog.
Today, the text box is empty.

![image](https://user-images.githubusercontent.com/12182730/102421672-f1df6980-403f-11eb-9db2-6844aa2deeb8.png)

In that text box, we can make that box displays all extensions that a lexer supports.
And users can modify it to add or remove extensions associated with that lexer.
If no extension is provided in the box, the lexer is disabled.

**Comment by stefankueng** [comment]
how about having a "most used" list of about 10 entries at the top of the list?

**Comment by wmjordan** [comment]
If we use "mostly used" stuff, we have to keep histories for them. That might not be so easy to implement. And the bad thing to user experience is that the position of those entries are not fixed, which is bad to end users who may have developed some kind of habits that he may have a memory that a certain types are at a certain place. The user will have to look for the file type. He may get annoyed.

If utilizing the _Extension_ text box is not good for you, another approach is to add an "[ ] Disable this file type" checkbox (by default unchecked) to the _Configure Styles_ dialog. If it is checked, BowPad adds its lexer name into a persistable array and then disables the lexer.

**Comment by stefankueng** [comment]
the entries change often because Scintilla gets new lexers every few months.

my problem with deactivating styles in the config-style dialog is that once disabled, it will be very hard for a user to select that lexer.

**Comment by wmjordan** [comment]
> it will be very hard for a user to select that lexer

It should be very easy if those disabled lexers are still in the _Language_ list in that dialog window.

We can add " (disabled)" to those lexers which have been disabled. For instance, if I disable "Sorcus", then the text in the _Language_ list becomes "Sorcus (disabled)", a user can very easily point out that.

**Comment by wmjordan** [comment]
Thank you for implementing this feature.
There are some problems in the current implementation.

1. Open the _Configure Styles_ dialog.
2. Select language "ASN1".
3. Check the checkbox.
4. Don't close the dialog, select language "Abaqus".
5. Check the checkbox.
6. Don't close the dialog, select language "ASN1" again.
7. **The checkbox which is expected to be checked is not checked.** (problem 1)
8. Click the _Ok_ button to close the dialog.
9. Open the `userconfig` file, we can see the following:

````ini
[SCLEX_ABAQUS]
hidden=1
Lexer=84

[SCLEX_ASN1]
hidden=1
Lexer=63
````

10. Open the _Configure Styles_ dialog again.
11. Examine the language "ASN1" and "Abaqus", we can see that the checkbox is checked.
12. Select language "Ada".
13. Check the checkbox.
14. Click Ok to close the dialog.
15. Open `userconfig` file and we will see that **the configurations for previous language ("ASN1" and "Abaqus") are no longer there**, but only the following: (problem 2)
````ini
[SCLEX_ADA]
hidden=1
Lexer=20
````

**Comment by wmjordan** [comment]
After updating my compilation to the above commissions, I set several languages disabled, but "IDL" was not included, however, its checkbox got checked--even after restarting BowPad.

Here's the `userconfig` file.

````ini
[SCLEX_ABAQUS]
hidden=1
Lexer=84

[SCLEX_ADA]
hidden=1
Lexer=20

[SCLEX_ASN1]
hidden=1
Lexer=63

[SCLEX_AU3]
hidden=1
Lexer=60

[SCLEX_AVE]
hidden=1
Lexer=19

[SCLEX_AVS]
hidden=1
Lexer=104

[SCLEX_BAAN]
hidden=1
Lexer=31

[SCLEX_BIBTEX]
hidden=1
Lexer=116

[SCLEX_BLITZBASIC]
hidden=1
Lexer=66

[SCLEX_BULLANT]
hidden=1
Lexer=27

[SCLEX_COBOL]
hidden=1
Lexer=92

[SCLEX_CPP]
hidden=1
Lexer=3

[SCLEX_CSOUND]
hidden=1
Lexer=74

[SCLEX_D]
hidden=1
Lexer=79

[SCLEX_DATAFLEX]
hidden=1
Lexer=129

[SCLEX_DMAP]
hidden=1
Lexer=112

[SCLEX_DMIS]
hidden=1
Lexer=114

[SCLEX_ECL]
hidden=1
Lexer=105

[SCLEX_EDIFACT]
hidden=1
Lexer=121

[SCLEX_EIFFEL]
hidden=1
Lexer=23

[SCLEX_ERLANG]
hidden=1
Lexer=53

[SCLEX_ERRORLIST]
hidden=1
Lexer=10

[SCLEX_ESCRIPT]
hidden=1
Lexer=41

[SCLEX_FLAGSHIP]
hidden=1
Lexer=73

[SCLEX_FORTH]
hidden=1
Lexer=52

[SCLEX_FORTRAN]
hidden=1
Lexer=36

[SCLEX_FREEBASIC]
hidden=1
Lexer=75

[SCLEX_GAP]
hidden=1
Lexer=81

[SCLEX_GUI4CLI]
hidden=1
Lexer=58

[SCLEX_HASKELL]
hidden=1
Lexer=68

[SCLEX_HOLLYWOOD]
hidden=1
Lexer=130

[SCLEX_IHEX]
hidden=1
Lexer=118

[SCLEX_INDENT]
hidden=0
Lexer=122
Style0=TEXT;000000;FFFFFF;;0;

[SCLEX_LOG]
hidden=0
Lexer=1101
Style13=ERRORBLOCK;FF0000;FFFFFF;;0;

[SCLEX_PO]
hidden=1
Lexer=90

[SCLEX_SPECMAN]
hidden=1
Lexer=59

[SCLEX_SREC]
hidden=1
Lexer=117

[SCLEX_TEHEX]
hidden=1
Lexer=119
````

**Comment by wmjordan** [comment]
And one more problem:
1. Click the Lexers on the Ribbon.
2. Open the Configure Styles dialog.
3. Disable some lexers.
4. Repeat step 1. We can see that the lexers disabled in step 3 are still there until BowPad is restarted.

We need to repopulate the lexer's DropDownGallery.

**Comment by stefankueng** [comment]
I made a mistake: I added the hidden flag to the lexer config, but one lexer can be used by multiple "languages", e.g. the XML lexer is used by xml, docbook, mako, wix, xaml, nant
I'll have to rewrite the whole thing...

**Comment by wmjordan** [comment]
Oh.... I really regret posting this request... for it has brought you so much work.

But it is now done. THANKS VERY MUCH!
