### ISSUE TITLE
Icons on Ribbon got vanished on Windows 7 machines after the recent build

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#130]
After [this commission](https://github.com/stefankueng/BowPad/commit/e570b1734cac4a0d5baad05c0fc8ef8a22ba2bdc), images on Ribbon bar--except those provided by plugins--disappeared on Windows 7 machines. (On Windows 10 machines things are good.)

![image](https://user-images.githubusercontent.com/12182730/102156384-6edfd700-3eb8-11eb-8f1c-7601a1d24b1a.png)

**Comment by stefankueng** [comment]
I've decided to drop support for Win7 - it's been out of (even extended!) support for almost a year now, meaning that OS is now insecure and a menace.
It's not just the icons that don't work anymore on Win7 - the dark mode also doesn't work properly.

**Comment by wmjordan** [comment]
Please reconsider that. There are still quite a lot of people who still stick with Windows 7--for example, more than a half co-workers in my office works on Windows 7. As the screenshot above shows, the PNG icons provided in the plugins can be correctly displayed in the drop-down list. Maybe we can add a procure to detect the version of the Windows and _patch_ the images by loading them from the resource with GDI and providing the bitmap to Ribbon.

Please also take a look at the screenshot on my Windows 10 machine (on top) and my Windows 7 machine (at bottom).
<img width="543" alt="shot" src="https://user-images.githubusercontent.com/12182730/102289100-d198a780-3f78-11eb-9d89-c4d640163a8f.png">

On my Windows 10 machines, you can see that the combo boxes and the numeric-up-down boxes were too bright on the Ribbon bar. Comparing with that on the Windows 10, the dark mode was working not too bad on my Windows 7 machines. Nothing uncomfortable except that the scrollbars in the file tree are not dark enough to me. 

BTW, to better support the dark mode, maybe we should add some image processing procedures to the images on the Ribbon bar anyway. I feel that the images on the Ribbon bar was too bright in the dark mode. Maybe we shall dim them, or provide an extract set of images in the dark mode (like what Visual Studio is doing nowadays). So the aforementioned "patching" procedure will not only serves BowPad on Windows 7 machines, but also benefiting Windows 10 machine user experience too.

**Comment by gmcode** [comment]
Thank you wmjordan, for being a voice of logic and reason on this subject. Much, much, appreciated. You are a very decent person.

**Comment by wmjordan** [comment]
Thank you @stefankueng !
BowPad is beautiful again ^_^

However, the plugin icons which used to be good now go blank.
They are blank on the QAT and on the Ribbon drop-down.

![shot](https://user-images.githubusercontent.com/12182730/102422664-3966f500-4042-11eb-9334-7f48d15e2691.png)

**Comment by wmjordan** [comment]
After this fix, more icons are restored.

There are still quite a few icons missing:
1. Copy, Cut and lexer on the first tab.
2. All icons on the second tab.
3. Mini toolbar icons and context menu icons. I think it is OK that no icons on context menus. We can leave them alone.

![image](https://user-images.githubusercontent.com/12182730/102562356-dc3a7480-4111-11eb-931b-04c2f2a49f7f.png)
![image](https://user-images.githubusercontent.com/12182730/102562385-ed838100-4111-11eb-81bf-8a849acd06ba.png)
![image](https://user-images.githubusercontent.com/12182730/102562513-2f142c00-4112-11eb-90a5-2289bfdb40b7.png)

**Comment by wmjordan** [comment]
Thank you for the fix.
I recompiled the code.
Almost all icons were restored, except some icons (the Copy, Cut, Lexer, White Space buttons):

![image](https://user-images.githubusercontent.com/12182730/102675830-d7d78f80-41d5-11eb-8174-9e033f4a5446.png)
![image](https://user-images.githubusercontent.com/12182730/102675860-f63d8b00-41d5-11eb-936e-da18d06603a0.png)
![image](https://user-images.githubusercontent.com/12182730/102676100-ebcfc100-41d6-11eb-823d-2479cb82ead3.png)

I set the task bar using small icons and found that the icon occasionally jumped onto the center of the button then onto the left after the above build and the title on the task bar appeared then disappeared. -- Maybe this was caused by the failure of rendering buttons on the Ribbon bar.

**Comment by wmjordan** [comment]
Thank you very much for fixing the problem.
All icons are back now! Beautiful!

The only thing not being fixed is that the title on the taskbar button was sometimes missing (please see the screenshot below), when I set the taskbar never group buttons and use small buttons on Windows 7 machines.
This problem occurred after the recent fixes in the recent 1 or 2 days.

![image](https://user-images.githubusercontent.com/12182730/102688643-020b6a80-4233-11eb-819a-9da10caa1bce.png)

**Comment by stefankueng** [comment]
I don't think I can do anything about the taskbar, sorry.

**Comment by wmjordan** [comment]
But it was good on this Tuesday and before.

What kind of changes recently made had caused this?

**Comment by wmjordan** [comment]
I got a crash while I closed BowPad on that troubling machine.

![image](https://user-images.githubusercontent.com/12182730/102690223-e60dc600-423e-11eb-886c-a468c33bb36a.png)

Shall I still provide the dump?

**Comment by stefankueng** [comment]
screenshot is enough, thanks.
fix coming up soon - currently working on another project...

**Comment by wmjordan** [comment]
Thank you very much.
Please take your time 👍

**Comment by stefankueng** [comment]
I can't reproduce the crash myself, but I think the next push should fix it.

**Comment by wmjordan** [comment]
Thank you very much for fixing this! No more crash now.

Can we use a smaller size to display the plugin icons? On both my Windows 10 machine (above) and Windows 7 machine (below), they look a bit too large that if I have more plugins, there will not be sufficient space on my screen to accommodate them.

<img width="482" alt="shot" src="https://user-images.githubusercontent.com/12182730/102703009-6f0b1880-42a4-11eb-9d5c-f9fac14bc654.png">

![image](https://user-images.githubusercontent.com/12182730/102702992-2d7a6d80-42a4-11eb-8430-1cd9481157f9.png)

**Comment by wmjordan** [comment]
I created branches on each recent commit, compiled each branch and copied each on onto Windows 7 machines and found that the problem of missing title on the taskbar button began to occur after [this commit](https://github.com/stefankueng/BowPad/commit/577f6d2399f3ce9c594374f0e20405214fe10063).

Maybe a wrong result was returned for a certain property and consequently the title on the taskbar was erased.

**Comment by wmjordan** [comment]
After the last build, the task bar title issue on Windows 7 machines was fixed.
Thank you for taking the time.

The too-large-icon on Windows 10 was fixed too.

But on Windows 7 the fix did not work--it is really exhausting!
How about no icons on the DropDownGallery on Windows 7 machines (icons only available on QAT) if there's no way out?

**Comment by stefankueng** [comment]
I hate Win7

**Comment by wmjordan** [comment]
Thank you Stefan! It has been so beautifully handled.

Eventually this issue can be sealed :)
