### ISSUE TITLE
Selection indicators in Ribbon drop-down lists were gone in version 2.6.5

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#131]
Before version 2.6.5, there were indicators in the drop-down lists on the Ribbon bar to indicate current selections. Now they are gone and it is hard to figure out which ones are selected.

The tabs:
![image](https://user-images.githubusercontent.com/12182730/102424246-b5af0780-4045-11eb-90b5-314d71a3a9e7.png)

The load as box:
![image](https://user-images.githubusercontent.com/12182730/102424437-13dbea80-4046-11eb-9533-80309ffd3821.png)

The language box:
![image](https://user-images.githubusercontent.com/12182730/102424165-91532b00-4045-11eb-9925-18ea3dda23d0.png)

And the lexer box.

**Comment by stefankueng** [comment]
Win7 I assume?
On Win8 and Win10, a nice checkbox is shown...

**Comment by wmjordan** [comment]
It is on my Windows 10 machine.

**Comment by stefankueng** [comment]
what version of Win10 do you use?
also see #114

**Comment by wmjordan** [comment]
I am using 1909.
I've gotten many other versions also, from 1607 to 1903.
None of them have gotten check-boxes in the drop-downs. All of them looked like the above screenshots.

**Comment by wmjordan** [comment]
I created a branch and **reverted the commit** related to #114.
After some simple "fixes" to make the compilation finished, I could see some indication to the selection then.

![image](https://user-images.githubusercontent.com/12182730/102676558-20dd1300-41d9-11eb-950a-0c66d500b77d.png)

When I switched back to the Main branch and discarded the above "fixes", no more indicators again.

**Comment by stefankueng** [comment]
I'm using Win10 20H2 here.
My version of the UIRibbon.dll is 10.0.19041.1
what's your version of the dll?

**Comment by wmjordan** [comment]
Mine is 10.0.18362.1 (windows 1909).
And I've also gotten 10.0.14393.2969, 6.1.7601.17514, 6.3.9600.16384, etc. on other machines.

**Comment by stefankueng** [comment]
thanks for the info, that helps.
