### ISSUE TITLE
Ident wrapped lines can't be turned off straighforwardly

### ISSUE THREAD

**Issue by gmcode** [stefankueng/BowPad#132]
Bug: If you turn on wrapped lines then turn on indent wrapped lines by clicking the indent wrapped lines menu option, and then try to turn off indent wrapped lines by clicking it again, lines remain indented.

It would be my expectation that clicking "indent wrapped lines" would toggle indentation on and off.

Change request: It would be my personal preference that the indentation graphic not be shown in the editor window nor in the line number margin when line numbers are on, because the presence of the line number itself or not implies there is indentation. Changing it to work this way would reduce visual clutter and match vs code (I think).

Thanks

**Comment by gmcode** [comment]
Thanks for looking at this. I don't think the issue is quite fixed though.

It's better, but there still seems to be a bug still, which is this:
When wrapping indent is off but regular wrapping is still on, an indentation as if 1 seems to still be in effect, because it shows an indent wrapping indicator) and/or a space wrapped from the previous line.

What I expect is when regular wrapping is on and wrapping indent is off, is for there to be no space on the indented line and ideally no wrapping indicator. Essentially it should act as the indent button was never used.

Secondly, the wrapping indicator should not be shown in the code or the line number margin when line numbers are on because you can see from where the line number changes where the line ends, so showing an indent indicator as well in these two places is pointless clutter.

So I think we should not show the indent graphic in the code or margin when line numbers are on and follow what visual studio and visual studio code do etc. as it's a good precedence that makes sense.

The only arguable value of showing a graphic wrapping indicator icon would be if line numbers were off and even then I'm happy to assume from the indentation that the line continues and still see no need for clutter.

Thanks

**Comment by wmjordan** [comment]
I'd love to provide some screenshots for gmcode's findings.



> When wrapping indent is off but regular wrapping is still on, an indentation as if 1 seems to still be in effect, because it shows an indent wrapping indicator) and/or a space wrapped from the previous line.
> 
> What I expect is when regular wrapping is on and wrapping indent is off, is for there to be no space on the indented line and ideally no wrapping indicator. Essentially it should act as the indent button was never used.

![image](https://user-images.githubusercontent.com/12182730/103046698-21ecb680-45c4-11eb-9aba-31e9a573fd38.png)
The indicators in the code (marked yellow) should not be displayed of Wrapping Indent is turned off, since each indicator has taken an extra space.



> Secondly, the wrapping indicator should not be shown in the code or the line number margin when line numbers are on because you can see from where the line number changes where the line ends, so showing an indent indicator as well in these two places is pointless clutter.

So I think we should not show the indent graphic in the code or margin when line numbers are on and follow what visual studio and visual studio code do etc. as it's a good precedence that makes sense.

![image](https://user-images.githubusercontent.com/12182730/103046860-a4757600-45c4-11eb-93a0-d01a3200e2b2.png)
The indicators (marked purple) on the line number clutter may be considered as unnecessary.

**Comment by gmcode** [comment]
Thanks for the pictures wmjordan, that helps a lot.

Stefan, after the latest patch, things are better, but the blue markers indicated by wmjordan above in yellow ring are still present, but they are unwanted and unnecessary because the (now) spaces in the line number column imply the same information but without the clutter, so can we remove the blue graphics in the yellow ring please.

**Comment by wmjordan** [comment]
I think the latest commit is good.

The indicators in sub-lines do not take extra space and I can tell the lines are wrapped without taking a look at the line number column.

**Comment by gmcode** [comment]
wmjordan, I respect you have a different opinion to me and yours is not unreasonable. But for me the principle is that the code / text is the most important thing. Anything that detracts from the code is a distraction. Why do people need extra reminding of indentation because I can see it's likely indented by the indentation itself and ident button the line numbers give me certainty if I need it, that's 3 ways right there, a fourth way doesn't make sense to me, when it distracts from the code.

Visual Studio and Visual Studio Code come to this same opinion so I think that affirms that it's likely the right choice for Bowpad and what people will expect. So for me clutter free and consistency is the way to go. 

We could of course have a "Show indentation graphic" menu option under the split button?

But even then I think the default should be to not show the graphic because it's keeping with the reason we don't show a graphic for the carriage return like some editors do, because *most* people do not appreciate graphics in the code unless its really critical. I don't think it is critical in this case nor the convention.

Anyway, that's my opinion, I hope it persuades you of the merit. But an option to turn the graphic on/off will satisfy everyone at worst case. Oh that reminds me, for consistency 'the tool tip' for the indent button should start with a capital 'I'.

I personally would like to see the wrap lines button go back on the main screen since i toggle line wrapping on off regular as i'm looking through code? Perhaps we could remove the 'Tabs' icon to make more space now that we have the tabs available from the tab bar button and/or Change Case or Trim Whitespace could go to the 'other' tab instead so that the wrap button can be bought back to the main tab where it was before?

**Comment by wmjordan** [comment]
I'd made a plugin for your situation. Unzip this thing into the plugins folder and you shall get what you want.

[RemoveWrapIndicators.zip](https://github.com/stefankueng/BowPad/files/5745823/RemoveWrapIndicators.zip)

**Comment by gmcode** [comment]
Hi wmjordan

I think the default is wrong here still. But I appreciate the effort for the plugin. Thank you.

**Comment by gmcode** [comment]
For completeness, I should add that my comments equally apply to being able to turn off the graphic that appears on the right when lines wrap using the regular wrap mode. VS Code etc. does not show this type of graphic either by default.

**Comment by gmcode** [comment]
It seems I am incorrect in some of my comments above. Visual Studio does show and end of line graphic, but Visual Studio Code does not. Though I like the latter, given there is no consistency to be gained here, I think I am going to live with this feature how Bowpad currently does it for a while and see if I get used to it. Thanks.
