### ISSUE TITLE
Memory and CPU consumption rose when switching to Other tab

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#133]
Reproduction:

1. Open BowPad, (also open the Task Manager, watching at the CPU and mem usage of BowPad, the mem usage should be around 27MB to 34MB)
2. Switch to the _Other_ tab on the Ribbon.
3. The mem and CPU usage goes high and then mem usage goes to 50MB or more.

I examined the interface elements on the _Other_ tab on the Ribbon. I suspected that the Font and Font Size drop-down were busy enumerating fonts and generating font preview samples when they were initialized, thus the CPU usage got very high, then BowPad stored the preview of each fonts installed on the system, thus the mem usage got increased considerably--I'd gotten hundreds of fonts installed on my system.

Since users seldom change the font on BowPad, can the font-preview generation operation be postponed (lazy load)?

**Comment by stefankueng** [comment]
Sorry, that can't be done. The ribbon loads this automatically.

**Comment by wmjordan** [comment]
Thank you for the information.

I got it "fixed" by modifying the BowPad.xml and commented out the `FontControl` element :P
