### ISSUE TITLE
BUG: Mouse wheel no longer working to scroll tabbar.

### ISSUE THREAD

**Issue by gmcode** [stefankueng/BowPad#136]
To reproduce:

1. Open lots of documents so that the scroll buttons are present. 
2. Place the mouse above the tabbar and use mouse wheel (or two fingers down on the trackpad) to attempt to scroll the tabbar.

On my machine the tabbar does not scroll the tabbar window. This used to work. I'm not sure what version of bowpad it stopped working in.

**Comment by stefankueng** [comment]
works fine for me. Did you change your mouse or mouse driver?

**Comment by wmjordan** [comment]
On those Windows 7 and Windows 10 machines here, BowPad works well too.

**Comment by gmcode** [comment]
Nothing has changed that I am aware off, but it has been a while since I used the feature, so something might have changed. I get one mouse wheel message and then that's it. If you guys aren't having trouble, then it must be something unusual this end so I'll look into it a bit more. FYI, I use an Dell ALPS mouse driver.

**Comment by stefankueng** [comment]
I know that Logitec drivers have a "whitelist" of apps that get the proper messages. All others get modified wheel messages which messes up BP.
Those modified messages are done for "compatibility" reasons for apps that don't properly implement the wheel messages. But seriously, it's 2020 and not 1995 anymore, so why Logitec still insists on that fu** whitelist is beyond me...

**Comment by gmcode** [comment]
I'm closing this issue. This isn't a bug in Bowpad after all. Thanks for your comments.
