### ISSUE TITLE
FYI: Dark Mode doesn't work on Windows 7 for find and replace.

### ISSUE THREAD

**Issue by gmcode** [stefankueng/BowPad#137]
I'm not looking for anyone to fix this, it's just a place holder for me to make some comments on the subject, that might possibly help later. But I'm thinking not. dark mode helper probably doesn't want to use the path to get the version info, because load library won't.

1.
So I think this should be used:
CPathUtils::GetVersionFromFile(L"uxtheme.dll");

Will add more later.

**Comment by stefankueng** [comment]
I've disabled dark mode for dialog on pre-Win10 because there the OS dark mode for controls doesn't work.

**Comment by gmcode** [comment]
I think that it's fair enough to not support Windows 7 for dark mode.

Separately though, why does DarkModeHelper.cpp use SHGetKnownFolderPath?

It seems to me that if you call LoadLibrary and CPathUtils::GetVersionFromFile with just "uxtheme.dll" with no directory component,  both routines will search the standard paths, so load and report version information for the same file, wherever they find it. Which means if you bundled the .dll with your app (hypothetical), it'd use that version, which seems to be what you'd want in that case.

As it stands, you would ignore your own version if you bundled it, which would be a surprise but then suddenly start using it, if the known path routine ever failed. That might also be a surprise.

Is there a known problem that means you know you always must use the system version?

**Comment by stefankueng** [comment]
Using SHGetKnownFolderPath is usually not necessary, but I got into the habit of doing it that way because of "dll planting" issues:
https://msrc-blog.microsoft.com/2018/04/04/triaging-a-dll-planting-vulnerability/

Also, we must never ship our own uxtheme.dll because that file is not redistributable.

**Comment by gmcode** [comment]
Personally, I think you should cease with using SHGetKnownFolderPath for the reasons I've said, but also because otherwise you'll then have to use it consistently I assume and currently that's not the case and I don't think it's worth pushing the same changes elsewhere . Search for "uxtheme.dll", for example in ScintillaWnd::Init. 

By the way see the "delay loaded functions, not available on Vista" comment in that file. If you don't support Vista now, as I assume you don't, you can stop delay loading those functions if they are in Windows 7, which I think they are.
