### ISSUE TITLE
BowPad Core?

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#138]
Is it possible to compile a minimal BowPad without the Ribbon so it can be run on Windows Server Core?

The interface has no Quick Access Toolbar, no Ribbon bar, no menu, but only tab bar, Scintilla editor, file tree and status bar.
To call BowPad functions, the geek has to use the Command Palette.
To modify the configurations, edit the `userconfig` and other files.

The major problem is the underlying logic of command handling and the definition of `UI_PKEY_*` stuff.

````C++
    virtual HRESULT     IUICommandHandlerUpdateProperty(REFPROPERTYKEY key, const PROPVARIANT* ppropvarCurrentValue, PROPVARIANT* ppropvarNewValue);
    virtual HRESULT     IUICommandHandlerExecute(UI_EXECUTIONVERB verb, const PROPERTYKEY* key, const PROPVARIANT* ppropvarValue, IUISimplePropertySet* pCommandExecutionProperties);
````

Is it possible to make such a thing?

**Comment by kitepad** [comment]
I like your idea, and I have to try. If you want to hide ribbon, it's ok. If you want to remove ribbon code, But I don't know how to modified popup menu because of ribbon framework api is used in all command implementations.

**Comment by wmjordan** [comment]
> ribbon framework api is used in all command implementations

It is really the headache.

**Comment by kitepad** [comment]
Base on my trying. MainWindow, FileTree, Command Palette, Editor Window, TabBar can be modified simply. 
Pls tell me if you find out solution to implement command easy, pls tell me. I have intersting on this too.

By the way, my idea is reimplement using classic popup menu.

**Comment by wmjordan** [comment]
A BowPad without menu or Ribbon, solely with its command palette (Ctrl+Shift+P) is OK for me on Windows Server Core.
The major problem is the command manager. We have to re-implement it, I am afraid.
