### ISSUE TITLE
tinyexpr.h

### ISSUE THREAD

**Issue by LLZWWY** [stefankueng/BowPad#143]
The tinyexpr.h file is missing from the code

**Comment by wmjordan** [comment]
Don't download the code.
Clone it.
Otherwise, you will miss all code files in the submodules.

**Comment by LLZWWY** [comment]
> 不要下载代码。
> 克隆一下。
> 否则，您将错过子模块中的所有代码文件。

How to deal with it, please? I didn't quite understand it when I first studied.

**Comment by LLZWWY** [comment]
> Don't download the code.
> Clone it.
> Otherwise, you will miss all code files in the submodules.

How to deal with it, please? I didn't quite understand it when I first studied

**Comment by wmjordan** [comment]
Please learn how to use _git_.
Visual Studio provides all functionality you need to compile BowPad.
Plenty of information on the web.

**Comment by gmcode** [comment]
llzwwy, use this from the command line to get bowpad into a directory named bowpad:
git clone --recurse-submodules https://github.com/stefankueng/BowPad.git

The --recurse-submodules option will fetch tinyexpr for you and you will then find tinyexpr.h in bowpad\ext\tinyexpr

Hope that helps.

**Comment by LLZWWY** [comment]
> llzwwy, use this from the command line to get bowpad into a directory named bowpad:
> git clone --recurse-submodules https://github.com/stefankueng/BowPad.git
> 
> The --recurse-submodules option will fetch tinyexpr for you and you will then find tinyexpr.h in bowpad\ext\tinyexpr
> 
> Hope that helps.

Thank you for your advice.
