### ISSUE TITLE
wrong detection of file encoding

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#147]
I don't know whether this is an appropriate request.

Sometimes BowPad fails to determine the file encoding.
Is it possible to specify file encoding before loading some particular files?
The workflow may look like that:

````javascript
function BeforeOpeningDocument() {
  if (CURRENT_DOCUMENT_PATH is under a certain paths && CURRENT_DOCUMENT_EXTENSION == ".log") {
    BowPad.SetFileEncoding(65001); // force loading the file 
  }
}
````

**Comment by stefankueng** [comment]
if you prefer that files that could be interpreted both as ANSI and UTF8 to be loaded as utf8:
![image](https://user-images.githubusercontent.com/665591/104805933-f5e3e000-57d3-11eb-9950-58b3f243c29c.png)
![image](https://user-images.githubusercontent.com/665591/104805940-fd0aee00-57d3-11eb-8e00-ada92d8f2586.png)

**Comment by wmjordan** [comment]
Oh, I forgot this.
I will try that and see whether it helps.

**Comment by wmjordan** [comment]
Today I encountered a UTF-8 encoded log file which was incorrectly opened as ANSI.
I am sure that "prefer UTF-8" check box has been checked.

**Comment by stefankueng** [comment]
even with "prefer UTF-8" checked, the load process determines the encoding. Only if it could be both ANSI and UTF-8 then UTF-8 is preferred (that's what the checkbox does).
If however the encoding check determines that there are illegal UTF-8 sequences in the file, it then falls back to ANSI.

**Comment by wmjordan** [comment]
Actually there's no illegal UTF-8 sequences in the file.
Could it be that BowPad loads a trunk of bytes into memory to detect the encoding, but just at the end of the trunk, a UTF-8 encoded character was cut off, thus it _determines that there are illegal UTF-8 sequences_. Typically, a Chinese character takes at least 3 bytes, if only the first one or two bytes are loaded, it gets broken.

**Comment by wmjordan** [comment]
The following file can reproduce the problem.

[WrongUTF8.txt](https://github.com/stefankueng/BowPad/files/5859359/WrongUTF8.txt)

It is a UTF-8 encoded file (without BOM). It is detected as UTF-8 but the display of characters are wrong.

![image](https://user-images.githubusercontent.com/12182730/105563901-cc3e3200-5d5a-11eb-81fd-caa98212fce4.png)

The correct display can be viewed in NotePad.exe.
![image](https://user-images.githubusercontent.com/12182730/105563937-fc85d080-5d5a-11eb-87b9-9a427114772f.png)

The file has a character "v", followed by 65535 characters (Unicode 0x4E00, UTF-8 0xE4,0xB8,0x80).

**Comment by wmjordan** [comment]
I checked the Chinese in the first image in the previous post and found that it was the representation of character 0xE4B8 in Chinese GB2312. It seemed that the UTF-8 encoding on the status bar (image 1) was wrong, and BowPad actually fell back to ANSI (on my computer, it was GB 2312, or GBK).

**Comment by stefankueng** [comment]
your file helped a lot - found some bugs when detecting the encoding. Thanks!

**Comment by stefankueng** [comment]
hmm - with this fix, maybe you won't need a way to specify encodings per path?

**Comment by wmjordan** [comment]
It is good to have this fixed--No need to write script :).

**Comment by wmjordan** [comment]
Just compiled the source code and tested with several files. Problem solved.
