### ISSUE TITLE
Selection of collapsed lines was not covering invisible lines

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#148]
Is it possible to cover the whole selection of collapsed lines instead of only the visible line?

For instance, given the following javascript code:
````js
if (a) {
   // do something
}
````

Reproduction:
1. Collapse the "if" statement block, it becomes
````js
if (a) { { 3 lines }
````
2. Select that visible line by clicking on the line number on the left of the editor window.
3. Press the Delete key on the keyboard to delete the selected `if` statement.
4. Only `if (a) {` is deleted, the following two lines will be expanded and remained there.

Expected behavior:
The selection covers not only the visible line but also the collapsed lines.
So, subsequent edit operations will affect the whole unit, not the visible line only.

**Comment by stefankueng** [comment]
unfortunately, Neil doesn't want to do this:
https://sourceforge.net/p/scintilla/bugs/1399/

**Comment by wmjordan** [comment]
It works great!
Thank you very much!
