### ISSUE TITLE
Different settings for various file types?

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#151]
Is it possible to have various display settings for each file type or lexer?

For instance,
*.log: no wrap, tab = 4
*.txt: wrap, tab = 8
*.xml: wrap, tab = 2
others: use default

**Comment by stefankueng** [comment]
what would happen if a user then enables wrap for *.log? Would that setting get overwritten? Or would the settings then be disabled if configured for a file type? If overwritten: for the file type or just the current session?

**Comment by wmjordan** [comment]
On EditPlus, Sublime Text and Visual Studio, those individual settings are permanent.

**Comment by stefankueng** [comment]
do you have suggestions/ideas on where/how this would be configured by the user?

**Comment by wmjordan** [comment]
On the aforementioned editors, they have configuration section for each language about those settings.
You can check out the Visual Studio and see that.
Maybe we can have similar controls in the _Configure Styles_ dialog.

**Comment by wmjordan** [comment]
For the "user-unfriendly" approach, is it possible to receive notification when a user switches tabs in the plugin script?

We can create a map in the script and let the user alter it. For instance,
````javascript
var settings = {
  "Log": { "wordWrap": false, "tabSize": 4 },
  "Text": { "tabSize": 8 }, // word-wrap not specified, using global settings
  "Xml": { "tabSize": 2 }
};
````

The missing logic is to read global word-wrap and tab-size settings when the script is initialized, and set the settings when the user switches tabs.

**Comment by stefankueng** [comment]
there's a callback:
```
function TabNotify(code, tabOrigin)
{
    return;
}
```
`code` is the notification code, with -551 being the code for "tab selection change".

**Comment by wmjordan** [comment]
I set `BowPad.alert(code)` in the `TabNotify` callback and found that the code was `-1`, not `-551`.

**Comment by wmjordan** [comment]
I also found that the notification was sent before the new tab was activated. Consequently, when the script was setting the display settings, they were done in the old tab.

**Comment by stefankueng** [comment]
fixed now - the params were switched and the selected tab was not set

**Comment by wmjordan** [comment]
Thanks for working on this.
I now have the following script.
It has following problems:
1. When opening a document, `setDisplay` is called, but a second later, the display setting will be reverted to the global setting.
2. When switching tabs, the `TabNotify(-551, tabId)` is called before the tab is activated, thus the setting is not applied to the new tab. The notification should happen when a tab is activated and its content is displayed.

````javascript
// returns the version of the plugin
// this callback is not optional! If you fail to implement this, the plugin
// config dialog won't work properly with your plugin
function Version() { return 100; }

var def = { wordWrap: true, tabSize: 4 };
var settings = {
	"Log": { wordWrap: false, tabSize: 2 },
	"BowPadPlugin": { tabSize: 2 },
	"Javascript": { tabSize: 2 },
	"Text": { tabSize: 8 }
};
function setDisplay() {
	var lexer = BowPad.GetCurrentLanguage();
	var s = settings[lexer];
	if (s) {
		BowPad.SciSetWrapMode((typeof(s.wordWrap) === "undefined" ? def.wordWrap : s.wordWrap) ? 1 : 0);
		BowPad.SciSetTabWidth(typeof(s.tabSize) === "undefined" ? def.tabSize : s.tabSize);
	}
}

// this is the main function that gets executed when the command is run, i.e.
// the button is clicked
function Execute()
{
	return true;
}

// return true if the plugin command is enabled (used for the button)
// note: not used yet by BowPad, but planned for the future
function IsEnabled() { return false; }

// return true if the plugin button should appear as checked
// note: not used yet by BowPad, but planned for the future
function IsChecked() { return false; }

// called after a document was opened
function OnDocumentOpen(index) {
	setDisplay();
}

// notification about tabs
function TabNotify(code, tabOrigin)
{
	if (code === -551) {
		setDisplay();
	}
}
````

**Comment by stefankueng** [comment]
sorry for the delay - I really need to clean up my inbox....

I've changed the order, so now the TabNotify callback is called **after** the main window does its initialization.
Also, you need to handle the AfterInit callback, since Tab/EOL/... settings are applied in that callback:

```
function AfterInit()
{
    setDisplay();
}
```

**Comment by wmjordan** [comment]
Thanks for updating the code.
Now it works most of the time. But while I was editing a BPJ file, its display settings somehow got reverted to default global settings, quite a few seconds after the document was opened and the `setDisplay` function had successfully applied the customized settings to the document.

Here's my code.

````javascript
// returns the version of the plugin
// this callback is not optional! If you fail to implement this, the plugin
// config dialog won't work properly with your plugin
function Version() { return 100; }

// default display settings for lexers undefined in settings
var def = { wrapMode: 1, tabWidth: 4 };
// define your display settings in the below object
var settings = {
	"Log": { wrapMode: 0, tabWidth: 2 },
	"BowPadPlugin": { tabWidth: 2 },
	"Javascript": { tabWidth: 2 },
	"Text": { tabWidth: 8 }
};

function setDisplay() {
	var lexer = BowPad.GetCurrentLanguage();
	var s = settings[lexer];
	if (s) {
		BowPad.SciSetWrapMode(typeof(s.wrapMode) === "undefined" ? def.wrapMode : s.wrapMode);
		BowPad.SciSetTabWidth(typeof(s.tabWidth) === "undefined" ? def.tabWidth : s.tabWidth);
	}
}

// this is the main function that gets executed when the command is run, i.e.
// the button is clicked
function Execute()
{
	return true;
}

// return true if the plugin command is enabled (used for the button)
// note: not used yet by BowPad, but planned for the future
function IsEnabled() { return false; }

// return true if the plugin button should appear as checked
// note: not used yet by BowPad, but planned for the future
function IsChecked() { return false; }

// called after a document was initialized
function AfterInit(index) {
	setDisplay();
}

// notification about tabs
function TabNotify(code, tabOrigin)
{
	if (code === -551) {
		setDisplay();
	}
}
`````

**Comment by stefankueng** [comment]
the settings should not be overwritten anymore

**Comment by wmjordan** [comment]
I am feeling good after compiling the last commit.
The script is running and I am adding more options into the script.
Hopefully it can solve requirements like #45 , #51 , etc.

It seems that the `SciSetCaretLineFrame(1)` function was not working as expected. No matter what number I pass into that function, it produces an error.

**Comment by stefankueng** [comment]
`SciSetCaretLineFrame `was not implemented for scripting. It is now though...

**Comment by wmjordan** [comment]
Now I have a script like this.

Since the users have to open the script file for configuration... Is it possible to make them easier to do so? For instance, if a user execute the script, the bpj file is opened--how can I locate the script file?

**Comment by wmjordan** [comment]
I found that the display settings will be reset when a file is modified externally and automatically reloaded by BowPad.

**Comment by wmjordan** [comment]
The missing feature:
1. Don't reset the file display settings if the file is automatically reloaded when it is modified externally.
2. An API to locate the folder where the plugin is installed.

**Comment by stefankueng** [comment]
for 1., there's now a call to TabNotify() when a tab is reloaded, with code 0x0409
and for 2., there's now a property PluginPath which you can use:
`var path = BowPad.PluginPath;`

**Comment by wmjordan** [comment]
Thank you very much for providing the functions.
Now there is a script to override display settings for specific file types (the global settings are also overridden).

[DisplaySettings.zip](https://github.com/stefankueng/BowPad/files/6469725/DisplaySettings.zip)

**Comment by stefankueng** [comment]
I thought a new callback function would help, so now there's:
```
// called after styles are set, so the plugin can set its own
function OnStyleSet()
{
    return;
}
```

**Comment by wmjordan** [comment]
> a new callback function would help

So, with this function, there's no need to use the `AfterInit` and `TabNotify` in the EditorSettings plugin, but use this instead?

````javascript
// called after styles are set, so the plugin can set its own
function OnStyleSet()
{
    overrideSettings();
}
````

**Comment by stefankueng** [comment]
basically, yes.

**Comment by wmjordan** [comment]
I checked the source code and found that the function name should be `OnStylesSet`.

BTW, by adding the following in my script, I found that the function was fired twice when I switch tabs.

````javascript
function OnStylesSet() {
  BowPad.alert("message");
}
````

**Comment by stefankueng** [comment]
yes, it's called twice: once after the styles are set and then again after the editorconfig styles are set.
I know I could go through all code and make sure it's only called once everywhere the styles are set, but I'm lazy :)

**Comment by stefankueng** [comment]
oh, btw:
you can push your plugins yourself to this repo (you have write access).
just copy it into /plugins (unzipped), then run
nant plugins
on the root folder (but only if the plugin works with a released version of BP, because after that command is executed the plugin will show up when fetching the list of plugins in BP).

**Comment by wmjordan** [comment]
> once after the styles are set and then again after the editorconfig styles are set.

Maybe it is reasonable to provide an argument to the `OnStylesSet`, for instance, 1 means styles are set, 2 means editorconfig is applied. If any type of document will receive two `OnStylesSet` callbacks, plugin writers may decide that when should apply the style in the plugin and handle one of them.

**Comment by wmjordan** [comment]
> you can push your plugins yourself to this repo (you have write access).
> just copy it into /plugins (unzipped), then run
> `nant plugins`

Thank you for granting the write access to me.

Unfortunately I know little about _nant_. I used to use it more than a decade ago but I immediately forgot it when C# 2005 Express was released. I guess it is better be done by your hands.

**Comment by stefankueng** [comment]
well, if you don't want to use Nant, just add your plugin to the plugins dir (unzipped) and push that. I'll do the rest then in another commit.

**Comment by wmjordan** [comment]
Can a plugin save data in memory for each document?

The usage like this:
1. With this plugin in effect, it sets editor settings for each document when a user switches tabs. For instance, text files are usually word-wrapped.
2. But a user may encounter a text document that he would like to have the word-wrap disabled. Thus he presses the word-wrap button to disable it.
3. The user switches to another document.
4. The user switches back to that text document he previously disabled word-wrap. Since the plugin nowadays has not remembered the settings before he switched the document, it enabled word-wrap again.
5. The user has to fight back to disable word-wrap again.

If the plugin receive notification when a document is being switched, it can save editor settings into memory; when a user switches back to that document, the plugin restores the settings from previously saved states instead of applying settings defined in the plugin again.

**Comment by stefankueng** [comment]
you can use the TabNotify callback to get notified just **before** a tab is switched to another (`code == -552`), which is where you read the doc data the user might have changed. You can store that data in a global variable map. But use the doc ID, not the tab number. You can get the doc ID with the API `GetDocIdOfCurrentTab()`.

**Comment by wmjordan** [comment]
Thank you for the hint.

I read two APIs on your site and their comments are the same. Are they doing an identical job?

````javascript
// returns the document ID of the specified tab index
var docID = BowPad.GetDocIdOfCurrentTab(int);
// returns the document ID of the specified tab index
var docID = BowPad.GetDocIDFromTabIndex(index);
````

**Comment by stefankueng** [comment]
also see #173

**Comment by stefankueng** [comment]
GetDocIdOfCurrentTab does not have a parameter, that's a bug in the docs.

**Comment by stefankueng** [comment]
added a file that might help:
https://github.com/stefankueng/BowPad/blob/main/src/scripting/constants.js

**Comment by wmjordan** [comment]
> added a file

It seems that there's at least one more:
````javascript
var TCN_TABRELOADED       = 0x409 // BP reloads an externally modified file
````

**Comment by wmjordan** [comment]
Well, I just tried to push a new version of this plugin to the repository.

**Comment by stefankueng** [comment]
you succeeded: https://github.com/stefankueng/BowPad/commit/d286a89f91a2537b328dcd39357e127ce5f80be5

**Comment by wmjordan** [comment]
I found that the plugin sometimes failed to apply editor settings when opening substantially longer documents.

It occurred on one of my server machine when several log files were opened, the editor settings were applied but soon reverted to Global BowPad editor settings--specifically the word-wrap option.

The log files had some lines with more than 16384 characters.

The issue occurred after opening a file. When switching document tabs, it did not happened.

**Comment by stefankueng** [comment]
I can't find any reason or code part why the word-wrap option would be overwritten.
There are exactly three places in the code where word-wrap is set: when initializing BP, before a document is loaded, and when the user presses the ribbon button to change the wrap mode.
Unless you have a plugin that sets the wrap mode?

**Comment by wmjordan** [comment]
> before a document is loaded

Logically it is "before document is loaded". However, [it can be asynchronous when loading a bit larger document](https://www.scintilla.org/ScintillaDoc.html#BackgroundLoadSave). I have not fully checked out the code, but my previous experience suggested that could happen.

1. Load document (with a background loader),
2. Plugin applies settings,
3. Scintilla's loader has finished loading and BowPad somehow applies default styling.

**Comment by stefankueng** [comment]
yes, I'm loading asynchronously, but that's not relevant here.
The "before document is loaded" event comes right after the main windows (ribbon, treeview, ...) are initialized, before any file is loaded (either due to a stored session or through the command line, e.g. when doubleclicking on a file in explorer).
So that has nothing to do with file size or slow loading.

please try a breakpoint in ext/scintilla/src/Editor.cxx, line 6702 (the 'case SCI_SETWRAPMODE' part), and then you can maybe see from the stacktrace where the call to set the wrapmode comes from?

**Comment by wmjordan** [comment]
That's quite odd.

If I placed a `BowPad.alert(...)` after each call to `overrideSettings()`, everything apparently went as expected.

I will try the breakpoint and see what's going on.

**Comment by wmjordan** [comment]
After the debugging, I encountered quite a few situations.

1. If I put my custom [log.plex file](https://github.com/stefankueng/BowPad/files/6505408/log.bplex.txt) into the BowPad directory (portable mode), the following assertion in LexStyles.cpp failed:
````C
            std::wstring lexName = ini->GetValue(lexerName.c_str(), L"LexerName", L"");
#ifdef _DEBUG
            assert(!lexName.empty());
#endif
````
2. After removing the log.plex file from the folder, things appeared to be OK. But when I opened a log file, which, according to the plugin, should not be word-wrapped, the Scintilla was not wrapping, but the word-wrap button on Ribbon was still pressed.
   ![image](https://user-images.githubusercontent.com/12182730/118747374-7a329680-b88c-11eb-92d2-fe407eea7460.png)

**Comment by stefankueng** [comment]
you have to add
`LexerName=bp_log`
below
`Lexer=1101`

that change is necessary since the update to Scintilla 5.0

**Comment by stefankueng** [comment]
as for the button-state not reflecting the line-wrap state, I've added a new command
`BowPad.InvalidateCommand(cmdId)`
which invalidates the command states so the buttons get updated. The `cmdId `for the line wrap is `167`

**Comment by wmjordan** [comment]
It seems that it is a matter of timing.
In the release build, I could not reproduce the problem that the word-wrap button was inconsistent with the status of Scintilla.
