### ISSUE TITLE
Feature Request: handle wildcards as filenames

### ISSUE THREAD

**Issue by tvb377** [stefankueng/BowPad#152]
It would be nice to be able to say
bowpad. *.c

from the command line.

**Comment by stefankueng** [comment]
would that open all *.c files in the path? Recursively?

**Comment by tvb377** [comment]
I wouldn't implement recursive operation.

Great would be wildcards for paths, e.g.
[fb]oo*/*/Makefile

But also the simpler 
bowpad *.c *.h Makefile
would already help a lot.
The latter is what Notepad++ implements.

Regards,
Titus

**Comment by stefankueng** [comment]
wildcards like
[fb]oo*/*/Makefile
are not really possible, because [ and ] are valid path chars, so there's no way to know that it should be treated as a glob.
