### ISSUE TITLE
Feature Request: Implement LRU list for Ctrl-Tab

### ISSUE THREAD

**Issue by tvb377** [stefankueng/BowPad#153]
See Ctrl-Tab e.g. on VSCode or Notpad++:

- Implement LRU for the tab switcher's list ;
- Present a small pop up with a list of the file names of the open tabs when the user presses ctrl-tab to allow for easier navigation

[edit]: the pop up is already implemented by the doc list, but should include full paths.

**Comment by wmjordan** [comment]
Maybe you can press Alt+W to bring out the document list at this moment, if you have a lot of files opened.

**Comment by tvb377** [comment]
Thanks for the hint; good to remind me of the document list.

I'd like to extend the feature request to include full paths in the document list, or at least the last components that could fit.
This is why the doc list is unusable for some of my use cases and I did not think about it when writing the feature request.

**Comment by wmjordan** [comment]
The recent builds lists paths in the document list when some file names in the list are identical.

If no file has the same name, there will be no paths displayed, looking neat.
I think it is a quite reasonable implementation.

**Comment by bhank** [comment]
Is it possible to bind Ctrl-Tab/Ctrl-Shift-Tab to activate the next/previous tab as they did before? Judging by the diff, I'm guessing not. (As a rule, every UI change must bother at least one existing user. 😃)

**Comment by stefankueng** [comment]
Sorry, no. But why would you want that?
Also, you can use Ctrl+1...8 to select the corresponding tab, and Ctrl+9 will select the rightmost one.

**Comment by bhank** [comment]
I'm accustomed to it in other tabbed apps I use (e.g. Brave, Firefox, Keepass, ConEmu, Foxit Reader) as well as standard Windows tabbed dialogs.

Most of these also support Ctrl-PgDn/Ctrl-PgUp for going to the next/previous tab. Some apps like Visual Studio Code bind Ctrl-Tab/Ctrl-Shift-Tab to the recently-used-tabs list, but also support Ctrl-PgDn/Ctrl-PgUp for next/previous tab.

**Comment by stefankueng** [comment]
https://github.com/stefankueng/BowPad/issues/163
