### ISSUE TITLE
bowpad stays hidden or minimized when opening a file

### ISSUE THREAD

**Issue by tvb377** [stefankueng/BowPad#154]
It's a bit tricky to reproduce, and it seemingly has gotten "better" (but maybe only my understanding how to circumvent this got better).
Still:
- open bowpad on one virtual desktop
- open powershell on a second virtual desktop
- on the first bring another window on top of bowpad
- alt-tab to the powershell
- open a file with bowpad
- bowpad stays hidden
- now it is sufficient to alt-tab back to powershell and again to bowpad.

With an earlier version I had to kill bowpad and reopen it since it simply did not want to show up again. But that may be attributed to my lack of practice.
Now it seems to be only a minor problem since there is a workaround that does not hurt too much.

**Comment by stefankueng** [comment]
this may be a bug in Windows, because since Vista an application can not bring itself to the front anymore - everything is handled only by Windows.

**Comment by tvb377** [comment]
just as a hint:
it might well be a problem triggered or caused by windows but this does not happen with notepad++
so I'd expect this behaviour also being due to a difference also somewhere in the user code.

**Comment by stefankueng** [comment]
well, it **is** an issue of Windows. But maybe I can find a way to work around it...
