### ISSUE TITLE
Help?/Option to Always start with LF line ending instead of CRLF?

### ISSUE THREAD

**Issue by barkoder** [stefankueng/BowPad#155]
Using [Version 2.6.5 portable](https://github.com/stefankueng/BowPad/releases/download/2.6.5/BowPad64-2.6.5-portable.zip).

Is there a way to have Bowpad start with LF line endings by default, instead of CRLF?

There is an option to change line endings. But it's only temporary. It reverts back to CRLF on "New empty files".

I can't seem to find a way have the LF line ending be permanent.

Thanks :)

**Comment by stefankueng** [comment]
The "New" button (top left) has a subcommand "set defaults". There you can set the default EOL.

**Comment by barkoder** [comment]
Thank you :)
