### ISSUE TITLE
Reading BowPad settings in plugins

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#157]
I want to write a plugin to format XML documents with the indentation settings in BowPad.
How can I read whether tab is preferred and how much is the amount of indentation?

**Comment by stefankueng** [comment]
https://www.scintilla.org/ScintillaDoc.html#SCI_GETTABWIDTH
and
https://www.scintilla.org/ScintillaDoc.html#SCI_SETUSETABS
should do the trick. For plugins that would then be:
BowPad.SciGetTabWidth() and BowPad.SciGetUseTabs()

**Comment by wmjordan** [comment]
Thank you for the explanation.
Exactly what I need.
