### ISSUE TITLE
Paths containing spaces are not working in Notepad debugger mode

### ISSUE THREAD

**Issue by 239** [stefankueng/BowPad#16]
It's related to [tickets 213](https://sourceforge.net/p/bowpad-sk/tickets/213/) and the issue seems to be that arguments passed to Notepad are not treated as one path (unquoted) so BowPad fails to open the file.
Perhaps an easy fix would be to join all arguments after _"BowPad.exe /z .../notepad.exe"_?

**Comment by stefankueng** [comment]
Works fine for me here, the path is reconstructed properly.
What's the exact path you're trying to open?

**Comment by 239** [comment]
My fault, I forgot to mention that it only happens with paths containing _"C:\Program Files (x86)\..."_ but not other system paths like _"C:\Windows\..."_.

**Comment by 239** [comment]
Yes, every en-64-bit system also has _"C:\Program Files"_ but what makes the two paths so special? It only fails on files in these locations as far as I know.
