### ISSUE TITLE
follow urls

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/BowPad#161]
currently, urls are shown underlined, and a Ctrl+doubleclick opens that url. But this is ugly since Ctrl+click also does a selection.
Instead, allow the user to click in the tooltip of the url to follow the link, like VSCode does this:

![image](https://user-images.githubusercontent.com/665591/108109143-cf92b800-7091-11eb-8035-6294c0482a37.png)

**Comment by wmjordan** [comment]
This is not a big issue for me.

I have another suggestion.
I wrote a VS extension which detects the file paths in the OutputPane (actually it has more things to do in the document window). And when we select part of the path, a floating toolbar will appear, the user can click buttons on it to browse the file in Windows Explorer or open the file. You can do similar thing in BowPad.

![image](https://user-images.githubusercontent.com/12182730/108287468-cd317a80-71c5-11eb-94d5-ac812c1734b7.png)

On the above screenshot, the tool bar has four buttons. They are "Copy selection", "Search selection", "Open in folder", "Open in command prompt" respectively.

The logic of the appearance of the toolbar is the SelectionChanged event. The bar appears usually on top of the mouse cursor. But if there is no sufficient vertical space above, it appears below the mouse cursor.
The disappearance of the toolbar will be:
1. a button on the bar is clicked
2. the mouse moves (about 100 pixels) away from the bar
