### ISSUE TITLE
Unexpected Regex search result

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#167]
Given some text like the following in the editor.
````
abcdefghigklmn
````

Search with the following Regular Expression: `^.{3}`

BowPad matches the first three characters `abc` in the line, which is correct.
When search again, the 4 to 6 characters `def` in the line will be matched.
This is not expected, since the `^` in the front of the expression indicates that the search should begin at the beginning of the line, but `def` is not there.

It seems to be a tough problem.

Please see whether this can be fixed.

**Comment by ToniMa1** [comment]
If you would extend @wmjordan 's input with another line, so it will look like:

> abcdefghigklmn
> opqrstuvwxyz

1. If you do a search with `^.{1}` it will iterate through all characters in all lines, in the example all characters in lines are highlighted.
2. Furthermore the `$` operator which should match the line end in fact matches the last line end, in the example **z** is highlighted.
3. and if you do a Regex replace with searchstring `^` and replace `x` (which should insert a new char at the line start) it will insert in the cursor line on the 2nd position, in our example `axbcdefghigklmn`
4. if you do a **Replace All** (with settings from 3rd bullet) it will just freeze the program and you have to kill it with task manager.


i hope this helps you to find out the issue with the `^` and the `$` :) 

btw: love the BowPad, great job!! Keep on!

**Comment by wmjordan** [comment]
There's still a problem. Given a string like the following:

````
abcdefghigklmn
opqrstuvwxyz.

````

Search `[^a-z]$`, which should match the `.` at the end of the second line.
If we replace it with an empty string, not only the `.` but also the line end at the second line are removed.
The `$` in Regex denotes the end of the line but not the last character in a line.

````CSharp
new Regex("$", RegexOptions.Multiline).Replace("ABC\nDE\nFG", "")
// returns "ABC\nDE\nFG" (nothing should be changed)

new Regex(".$", RegexOptions.Multiline).Replace("ABC\nDE\nFG", "")
// returns "AB\nD\nF" (the last character of each line is removed)
````

**Comment by stefankueng** [comment]
Sorry, I used a non-capturing group to emulate the $ in the regex.
Changed to use positive lookahead.

**Comment by wmjordan** [comment]
It seems that the Find command is working as expected.

But Find All command has still have this problem.
