### ISSUE TITLE
Opening file resets window size and position

### ISSUE THREAD

**Issue by 239** [stefankueng/BowPad#17]
When BowPad is not maximized its window is reset if you open more files from Explorer.

**Comment by 239** [comment]
You are right, I had to check again and the crucial bit here seems to be that it only happens when using the window auto-size feature (resizing to top/bottom and moving to the left/right edge).
So I'm not sure whether it's a Windows or BowPad problem but I know that the auto-resizing is crap and broken since W10.

**Comment by 239** [comment]
It's still broken so I'm not sure why this was closed. Just drag BowPad window to the left or right screen border so it takes up one half of the screen and open another file from Explorer.

**Comment by songbaoming** [comment]
Fixed in commmit [137b676](https://github.com/stefankueng/BowPad/commit/137b67648ccc9392ce5d9866eadd66ba3d32e288)
