### ISSUE TITLE
Some lines in BasicScriptObject may be incorrect

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#177]
Please see:

https://github.com/stefankueng/BowPad/blob/e5516e3db7ac8235855e83f6b94f673d22a9650c/src/scripting/BasicScriptObject.cpp#L321-L324
(Script names are not corresponding to Scintilla API names)

And

https://github.com/stefankueng/BowPad/blob/e5516e3db7ac8235855e83f6b94f673d22a9650c/src/scripting/BasicScriptObject.cpp#L330-L331
(The `SciGetIdleStyling` appears to be associated with `SCI_SETIDLESTYLING` conditionally and it seems that missing a `SciIdleStyling` counterpart)

**Comment by stefankueng** [comment]
thanks for noticing this bug!
