### ISSUE TITLE
Cut, Copy, and Paste Commands are Missing from the Editor Context Menu

### ISSUE THREAD

**Issue by Justdoro** [stefankueng/BowPad#178]
# Steps to reproduce

1. Open or create a document.
2. Select a region of text using the mouse or keyboard.
3. Activate the Editor context menu, using either a right-click on the mouse or the Windows menu key from the keyboard.
4. 'Cut', 'Copy', and 'Paste' are not available as commands from the context menu.

The commands are available from the toolbar, operating as expected.

Is this the expected behavior?

**Comment by stefankueng** [comment]
the commands are available:
![image](https://user-images.githubusercontent.com/665591/119690477-05da9300-be4a-11eb-8205-b3f8a038c088.png)

**Comment by Justdoro** [comment]
Thank you for the feedback -- very helpful.
