### ISSUE TITLE
System default encoding was not used

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#179]
I am using Chinese operating system (code page 936).

I found that since some previous builds, while I opened some (not all) Simplified Chinese encoded files, all Chinese characters inside the document were represented by hex codes.

I tried to execute the _Reload_ function in the file menu, nothing changed.
If I reopened the file with `ANSI` encoding in the _Others_ tab, the Chinese characters in the file were correctly displayed.

This had not took place before.
The Prefer UTF-8 option was not checked, thus the system encoding should have its precedence in encoding detection.

Have you changed or refactored something recently about the encoding detection?

**Comment by stefankueng** [comment]
what does the encoding say (status bar) when you first load such files? Meaning: what encoding was detected?

**Comment by stefankueng** [comment]
also if you could attach a test file here, that would help.

**Comment by wmjordan** [comment]
Sorry I had forgotten to mentioned that on the status bar, it printed "ANSI".

**Comment by wmjordan** [comment]
By debugging the project using a file which encountered the problem, I found the following part in _UnicodeUtils.cpp_:

````C
    // scan the whole buffer for a 0x00000000 sequence
    // if found, we assume a binary file
    int nDwords = cb / 4;
    for (int i = 0; i < nDwords; ++i)
    {
        if (0x00000000 == pVal32[i])
            return -1;
    }
````

`-1` was returned when scanning the file.

I examined the file and found `0x00000000` in the file, which was generated from an IOT application which read data from remote devices and stored them into the text file. Most devices produced human readable characters as the protocol specified. However, some incompetent devices produced that type of invalid data, which caused BowPad to think the file was a binary one.

**Comment by stefankueng** [comment]
uchardet was developed for the mozilla browser: it is better at detecting encodings, yes. But it's also slow and big. Which isn't a problem for a browser because you rarely open huge files there, but it is a problem for BP which can open files in the GB size range.

So I'll stick with what we have, but I'll change it so that it won't return "binary" for just one such zero sequence.

**Comment by wmjordan** [comment]
> it's also slow and big. Which isn't a problem for a browser because you rarely open huge files there

Thank you for updating and the investigation.
Maybe we can use uchardet to sample the 16 kilobytes from the beginning document and assume the encoding. Thus it won't take too much time and is sufficient in most cases.

**Comment by wmjordan** [comment]
If deploying _uchardet_ will take too much trouble, maybe we should let it be as it is today.

Then, we may indicate the file as Binary in the status bar.
Currently BowPad treats the binary file as ANSI. If that binary file is saved, it will be encoded with ANSI (system default encoding), consequently the Hex representations will be replaced by question marks and the document is broken.

**Comment by wmjordan** [comment]
Thank you for fixing this.
