### ISSUE TITLE
Execute external program settings 

### ISSUE THREAD

**Issue by wertemenge** [stefankueng/BowPad#18]
Execute external programs: configured customized settings are lost in some cases:
MENU run: configure a new run command -> save your open file -> new run command is lost
(Bowpad is running on Windows10)

**Comment by stefankueng** [comment]
I can not reproduce this.
Are there any steps that you might have missed to mention?
What command are you trying to configure? Maybe it's something to do with the command...

**Comment by stefankueng** [comment]
could this be the same as #64 ?

**Comment by stefankueng** [comment]
closing for now. If you still have the problem and new information, feel free to reopen the issue.
