### ISSUE TITLE
Small enhancement for Capture Regex

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#180]
Is it possible to ...

1. By default capture the whole expression?
   That is, if _capture expression_ is empty, the whole captured content will be output to the result box.

2. Add a check box to append new line to each capture?
   So, we don't need to manually type `\r\n` in _capture expression_ if we want that.

3. Add a check box to redirect the output to a new document window?

**Comment by stefankueng** [comment]
well, apart from redirecting the captures to a new window I think this is a good idea.
