### ISSUE TITLE
EditorSettings plugin stopped working after recent commits

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#181]
Could you guide me how to fix it?

**Comment by stefankueng** [comment]
works fine for me.
You could set a breakpoint in EditorConfigHandler.cpp, line 71 and see whether it goes there.
But note that after the editor config handler has applied the settings, the OnStylesSet() handler is called, so it might be possible that these settings are overridden by plugins.

**Comment by wmjordan** [comment]
That's strange.
I got this:
![image](https://user-images.githubusercontent.com/12182730/121273414-d1abab80-c8fa-11eb-8e94-45cb8c4c89db.png)
and this:
![image](https://user-images.githubusercontent.com/12182730/121273442-dcfed700-c8fa-11eb-96d6-911e94b5f3d3.png)

**Comment by wmjordan** [comment]
I checked the source code and found that the following lines were removed, which caused the script error.

````C
    {L"SciSetCaretFore", SCI_SETCARETFORE, SCI_SETCARETFORE, VT_NULL, VT_INT, VT_NULL},
    {L"SciGetCaretFore", SCI_GETCARETFORE, SCI_GETCARETFORE, VT_INT, VT_NULL, VT_NULL},
    {L"SciCaretFore", SCI_SETCARETFORE, SCI_GETCARETFORE, VT_INT, VT_INT, VT_NULL},
    {L"SciSetCaretLineVisible", SCI_SETCARETLINEVISIBLE, SCI_SETCARETLINEVISIBLE, VT_NULL, VT_BOOL, VT_NULL},
    {L"SciGetCaretLineVisible", SCI_GETCARETLINEVISIBLE, SCI_GETCARETLINEVISIBLE, VT_BOOL, VT_NULL, VT_NULL},
    {L"SciCaretLineVisible", SCI_SETCARETLINEVISIBLE, SCI_GETCARETLINEVISIBLE, VT_BOOL, VT_BOOL, VT_NULL},
````

**Comment by wmjordan** [comment]
Thank you for fixing this.
I just updated the plugin to work with the new version.
