### ISSUE TITLE
Match occurrence features blocking UI in large documents

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#183]
Nowadays, BowPad has two sweet features:
1. automatically highlight matching selections
2. highlight all search results

They are really nice. But when we deal with large documents, they block the interface and we can't do anything except waiting.

**Comment by stefankueng** [comment]
the highlight matching selections function is stopped after 1.5 seconds so it should not block for too long.

related #30 and #145

**Comment by wmjordan** [comment]
Oh, I see.

I observed my behavior when doing selections.

The problem of current approach is that when a user makes selections with a mouse, he drags the cursor over the text. During the process, the selection changes gradually, from zero length, to one character, then two characters, and so forth.
So the hang-up time will accumulate to more than 1.5 seconds, maybe 1.5*2=3 seconds, 1.5*3=4.5 seconds, or more.
