### ISSUE TITLE
Regex Mode has a bug

### ISSUE THREAD

**Issue by zcy6187** [stefankueng/BowPad#184]
When I use "find and replace"，I want to insert character '|' in the head of every line，so I use `^` to replace `|`，but the editor freeze. 
![Snipaste_2021-06-23_09-49-12](https://user-images.githubusercontent.com/20578665/123022397-51ac3800-d408-11eb-8858-26f50e28d615.png)

**Comment by stefankueng** [comment]
works fine for me.
Are you using the latest version? (2.7.1)

**Comment by zcy6187** [comment]
ok. the latest version is good.
