### ISSUE TITLE
BowPad somehow crashed after file system changed

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#186]
Here's the WinDbg display about the crash dump.

![image](https://user-images.githubusercontent.com/12182730/123942852-1beded00-d9ce-11eb-8da4-d9e3cdbacc13.png)

**Comment by wmjordan** [comment]
When a folder is collapsed, wouldn't BowPad stop listening on its change?

**Comment by stefankueng** [comment]
not immediately - there's a race condition because of the separate thread.

**Comment by wmjordan** [comment]
That's strange.
On the computer where the previous crash occurred, no one was operating at the time.
The folder should had been collapsed very earlier before the crash. If the listening on changes had been stopped, this bug might not occurred.

**Comment by wmjordan** [comment]
After the previous fix, BowPad no longer crashed.

However, I encountered a situation that the file monitor was not working. Given the following folder structure:

````
[Root Folder]
   [A]
      [B]
         some files
````

An external program created a folder `C` under `A`, the `C` did not appear in the file tree.

**Comment by stefankueng** [comment]
I can not reproduce this: when I create a folder C it appears in the file tree.
I had a file open first in [Root Folder], then opened a file in [B], making the file tree show the root folder with [A] and [B] expanded. Then I created folder [C] in [Root Folder] and it appeared in the tree.

**Comment by stefankueng** [comment]
It also works if I create a folder in [A] and in [B]

**Comment by wmjordan** [comment]
That's strange.
It occurred on one of my servers once.
But I could not reproduce that manually later.
I will post a new issue if I can reproduce it later.
