### ISSUE TITLE
Better Menu/Toolbar suggestion

### ISSUE THREAD

**Issue by hongnod** [stefankueng/BowPad#190]
Bowpad is a nice editor, thanks for your great work!
I have some suggestion for Menu and Toolbar arrangement. Currently, there are 3 main menu with sub menu (File) or Ribbon Toolbar(Main & Other),  for every day usage, I fell it not that handy, the Ribbon items occupy so much editing space, can you please make more main menu item and insert  sub-items  as one line Ribbon like a toolbar, and switch "File" main menu as such tool, then it will has same using experience, and give more space to editor.
Best Regards.

**Comment by stefankueng** [comment]
you have to be more specific here: which items do you want rearranged and how?

**Comment by hongnod** [comment]
![Uploading 未命名绘图.png…]()
Like this way

**Comment by wmjordan** [comment]
How about right clicking your most frequently used buttons on the Ribbon bar and selecting "Add to Quick Access Toolbar", then folding up the Ribbon bar.

![image](https://user-images.githubusercontent.com/12182730/128627047-22679474-6137-4e53-a0d0-d81984e6c48f.png)

**Comment by hongnod** [comment]
Good idea, but the Quick icon is too small.

**Comment by wmjordan** [comment]
You will get used to it later--I guess. That's what I am doing with my Office applications.

And the interface you suggested above is not possible for the standard Ribbon Bar control provided by the Windows system.

**Comment by hongnod** [comment]
![image](https://user-images.githubusercontent.com/6680267/128666943-5e5d8f92-b7ea-4079-b343-87d954d4521e.png)
Good!

**Comment by stefankueng** [comment]
@hongnod you're screenshot shows multiple ribbon tabs. That means you'd have to click even more to get to the command you need (first click on the tab e.g. `edit`, `search`, `view`, `code `and then on the command. As it is right now, the most used commands are all on the main tab so no need to first click on the right tab.

**Comment by wmjordan** [comment]
Hi Stefan, hongnod seems to have customized a better workspace personally and feel a little bit satisfied, in the last posted screenshot. We may consider closing this issue.
