### ISSUE TITLE
Capture Regex function is slow

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#191]
If there are thousands of matches in the captured results, the dialog interface hangs.

The problem might because that whenever a capture is met, `SCI_APPENDTEXT` is called once.

https://github.com/stefankueng/BowPad/blob/7614d28c65575acacd0c8fb564d4dcd83ab86d70/src/Commands/CmdRegexCapture.cpp#L260-L273

It may be better if we use memory buffer to hold the captures, then write them to the Scintilla window as a single string when the buffer is full or the search is done. So we can save quite a lot of calls to `SCI_APPENDTEXT`.

**Comment by stefankueng** [comment]
`SCI_APPENDTEXT `should be very fast. Did you test this by e.g. just removing the call to `SCI_APPENDTEXT`?
I don't think that this is the reason for the bad performance but most likely the regex search?

**Comment by stefankueng** [comment]
ok, profiling clearly shows that SCI_APPENDTEXT is much slower than using a custom buffer...

**Comment by wmjordan** [comment]
I examined the commit. It used a pre-allocated string as a buffer, if the search result accumulates overrun the buffer, string concatenation and memory reallocation may occur heavily. We may use [`stringbuf`](https://www.cplusplus.com/reference/sstream/stringbuf/) instead.

**Comment by stefankueng** [comment]
how about using ostringstream?

**Comment by wmjordan** [comment]
According to [this web page](https://www.cplusplus.com/reference/sstream/ostringstream/ostringstream/), `ostringstream` internally uses `stringbuf`.

**Comment by wmjordan** [comment]
I also have written another version which uses a 64KB buffer mentioned above.

````C++
constexpr auto BUFFER_SIZE                = 65536;

std::string                                     buffer;
buffer.reserve(BUFFER_SIZE);
while (std::regex_search(start, end, whatC, rx, flags))
{
    if (whatC[0].matched)
    {
        auto out = whatC.format(sCapture, flags);
        if (buffer.length() + out.length() > BUFFER_SIZE)
        {
            m_captureWnd.Call(SCI_APPENDTEXT, buffer.size(), reinterpret_cast<sptr_t>(buffer.c_str()));
            buffer.clear();
        }
        if (out.length() > BUFFER_SIZE)
        {
            // WE CAN WARN THE USER HERE THAT THE CAPTURE IS VERY LONG,
            // THE INPUT REGEX MAYBE INCORRECTLY CAPTURING A LARGE PART OF THE DOCUMENT
            m_captureWnd.Call(SCI_APPENDTEXT, out.size(), reinterpret_cast<sptr_t>(out.c_str()));
        }
        else
        {
            buffer += out;
        }

        sptr_t captureCount = 0;
        for (const auto& w : whatC)
        {
            capturePositions.push_back(std::make_tuple(captureCount, w.first - searchText.cbegin(), w.length()));
            ++captureCount;
        }
    }
    // update search position:
    if (start == whatC[0].second)
    {
        if (start == end)
            break;
        ++start;
    }
    else
        start = whatC[0].second;
    // update flags for continuation
    flags |= std::regex_constants::match_flag_type::match_prev_avail;
}
if (buffer.length() > 0)
{
    m_captureWnd.Call(SCI_APPENDTEXT, buffer.size(), reinterpret_cast<sptr_t>(buffer.c_str()));
}
````

**Comment by stefankueng** [comment]
Use the ProfileTimer to measure the times:
`ProfileTimer profiler(L"capture time : ");`
but you also have to create the registry DWORD value `HKCU\Software\BowPad\DebugOutputString` and set the value to 1. Then you'll get the time in the debug output.

Haven't tested your new version, but if it's faster then please push your changes.

**Comment by wmjordan** [comment]
I run both versions without benchmark code.
It seemed to me that there was not so much difference between them.

It is much better than before  now. Let's leave it here at this moment.
