### ISSUE TITLE
"Save" to last "Save"ed directory

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#192]
Greetings Kind Regards Thank You for providing BowPad I utilize it daily May I please request when attempting to "Save" the BowPad executable directory not be presented as I do not have write permission to save to it and of course do not wish to do so as documents are stored in a Personal directory Perhaps BowPad can "Save" to the last "Save"'d directory just as "Open" appears to "Open" the last "Open"'ed directory Thank You Kindly

**Comment by stefankueng** [comment]
the save path used is:

1. the path of the file/tab if it was saved before
2. the path the file tree is showing
3. the current directory (for example if you started BP from a console) - but only if it's NOT the same as the one the BP exe is in
4. the last save-as directory

**Comment by PaltryProgrammer** [comment]
I clicked "New" typed a few letters Clicked on "Save" and it attempted to save to C:\Program Files\BowPad
The File Tree Path is C:\Users\Bernard\Documents\Personal

**Comment by PaltryProgrammer** [comment]
Greetings Attached please find a gif which demonstrates the phenomenon Thank You Kindly
![Find and Replace regular expression emplacement](https://user-images.githubusercontent.com/48535920/132930589-3b601ab5-407b-4437-a119-e1d2c20a500a.gif)

**Comment by PaltryProgrammer** [comment]
Attached please find a gif which demonstrates the phenomenon
![Save of New to BowPad Directory](https://user-images.githubusercontent.com/48535920/132930935-3350471a-b2e4-40f2-a1f0-b0ac1f9943c9.gif)

**Comment by stefankueng** [comment]
screenshot shows that you're using a very old version of BP. Please update first and check if it still happens with the latest version

**Comment by PaltryProgrammer** [comment]
Greetings Thank you for your kind assistance The attached gif demonstrates the current version results in the phenomenon of saving a new file to the BowPad directory Kind Regards
![BpwPad version](https://user-images.githubusercontent.com/48535920/132939227-3cafbb6c-8df0-4ba7-9d74-f12288916552.gif)

**Comment by stefankueng** [comment]
you know the last version is 2.8.0, not 2.5.2!

**Comment by PaltryProgrammer** [comment]
Thank You for informing me of the latest version However as you can see in the gif of the older version "Check for Updates" did not function correctly I of course can not test if it functions correctly in the new version Also I am a bit surprised BowPad does not check for updates automatically or for that matter there is no "Preferences" page which is much easier to navigate than a series of ribbons and buttons Such a page would permit selection of such an option Of course you probably have other things to do in addition to your generous offering of BowPad Kind Regards

**Comment by stefankueng** [comment]
the check-for-updates works with newer versions ok. The problem was that the url used to fetch the version info changed due to some GH changes (my fault actually: I used a wrong url scheme instead of the GH recommended one which stayed stable).
