### ISSUE TITLE
Last Font

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#194]
Greetings Thank You for providing BowPad I would find it helpful if upon start of execution BowPad would utilize the Font and Font size utilized at close of last execution Kind Regards - Cheerio

**Comment by stefankueng** [comment]
that works for me.
Where do you change the font?

**Comment by PaltryProgrammer** [comment]
It now works for me too I was certain it was not working prior I am sorry I do not have a reasonable explanation for this other than it seems I am dedicating myself to wasting your valuable time
