### ISSUE TITLE
Internet Explorer via Help file boost regex link

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#195]
Why is my default web browser Chrome not opened upon clicking on the boost regex link in the Help file Instead IE is opened which is an old and perhaps insecure browser Further I am forced to use IE as the link for some reason refuses to be copied for pasting into a modern browser Also Why must I hold down the Ctrl key and click on the link Why is it not sufficient to click on it w/ no keys participating Thank You - Cheerio

**Comment by stefankueng** [comment]
BowPad does not use boost, also there's no help file.

**Comment by PaltryProgrammer** [comment]
The upper left hand corner of grepWin states "Press F1 for help" When I press F1 another window appears on top of which it states "regex Help" the contents of which include links to boost

**Comment by stefankueng** [comment]
this is the issue tracker for BowPad...

**Comment by PaltryProgrammer** [comment]
I am aware this git site is the issue tracker for BowPad I presented a previous issue #195 which you closed However my comment above contradicts your assertion re/ no Help file and no boost link Attached please find two screen captures which demonstrate my claim re/ same
![grepWin Press F1 for help](https://user-images.githubusercontent.com/48535920/131393669-7d52c5dc-2b91-4ec3-9e4e-ee55b7b1cef0.png)
![grepWin regex Help](https://user-images.githubusercontent.com/48535920/131393719-78a9d2a4-8216-4a33-9999-88f220e50e3d.png)
