### ISSUE TITLE
regex \< does not match <

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#196]
Greetings Kind Regards The regular expression \< does not match the text string <
Like wise for >
- Cheerio

**Comment by stefankueng** [comment]
works fine for me here. Are you using the latest version?

**Comment by PaltryProgrammer** [comment]
I apologize to have wasted your time Somewhere I thought I read < was a special character in Perl regex and so needed to be escaped when searching for < For some reason the post above did not display the escape Thank You Kindly - Cheerio
