### ISSUE TITLE
Font Size Changes Upon Save of New

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#198]
![changing font size upon save of new](https://user-images.githubusercontent.com/48535920/131690993-d4833228-a075-434a-82a5-f08c0693f862.gif)
The attached gif demonstrates the font size changing upon a save of a new file

**Comment by stefankueng** [comment]
First thanks for the report with the animation - that helped a lot.
And wow: this is a 5 year old bug!
Fix coming up...
