### ISSUE TITLE
luttering Mouse Cursor

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#199]

**Comment by PaltryProgrammer** [comment]
Greetings Kind Regards Attached is a gif which demonstrates a flutter of the mouse cursor alternating between pointer and text select icons This occurs occasionally seemingly after the computer has been running for several days and begins to respond sluggishly though it is not low on resources The fluttering does not occur in other editors in particular Notepad++ Visual Studio A reboot eliminates the phenomenon - Cheerio
![BowPad fluttering cursor](https://user-images.githubusercontent.com/48535920/132617900-24a2f732-0fbb-4b5d-a6b4-f0816407ced7.gif)

**Comment by stefankueng** [comment]
I can not reproduce that.
Also, when you hover your mouse cursor at the top of the ribbon buttons: that's still inside the ribbon, so nothing I could even do there.
