### ISSUE TITLE
Custom Syntax Highlighting

### ISSUE THREAD

**Issue by mva1985** [stefankueng/BowPad#20]
This is a fantastic little editor and very customize-able...  thanks so much.  I do like the very limited number of files to run the editor and that I can hid the ribbon toolbar yet also add items to the Quick Access Toolbar.

Of course my requests my have all ready been considered by the developer.  But if not I would appreciate it if you would.

Also, I use some kinda of obscure BASICs with similar highlighting to the ones already included in BowPad but they are different. 

For example....
yabasic - [http://www.yabasic.de](url)
rcbasic - [http://rcbasic.online](url)      recently changed his domain address so there's not much there
tbas - [https://digilander.libero.it/tonibinhome/tbas/index.html](url)

The first two still receive fairly regular updates.

Thanks for taking this under consideration.

**Comment by mva1985** [comment]
Thanks so much...  that is the information I needed.

**Comment by mva1985** [comment]
just wondering if I can add multiple symbols for a comment line such as "rem" ' and #

do I just put them on the CommentLine??

**Comment by stefankueng** [comment]
The "CommentLine" is used for the comment/uncomment feature. It has nothing to do with the syntax highlightling.
For example, you can select one or more lines, then hit Ctrl+K,C and those lines will get 'commented'. That's what this configuration is for.

**Comment by stefankueng** [comment]
https://tools.stefankueng.com/BowPad_lexerconfig.html
