### ISSUE TITLE
Summary Character Count - enhancement

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#202]
Greetings Kind Regards Perhaps it may be useful for the Summary to include character count - Cheerio

**Comment by stefankueng** [comment]
what would you consider a "character"? I mean on first sight this question might seem stupid, but:
- do you count spaces?
- should newlines be counted?
- should punctuation marks be counted? And should that include -,.:;!?... but also '`´ marks?

**Comment by stefankueng** [comment]
so basically you answered my question with "everything"....
Now, if you can give a good reason for why you would need that information I might add it.

**Comment by PaltryProgrammer** [comment]
I don't recall precisely why I looked for a character count recently It may have been because I was submitting to a web form which limits the number of characters permitted I have encountered this limit rather often Kind Regards

**Comment by stefankueng** [comment]
depending on the web form this could include newlines or not. And even then newlines might not be consistent, i.e. the webform might count them as two bytes for CR and LF, or only one byte (LF) - which might even not be the same as in BP.
So counting that would not help.

But if you hover the mouse cursor over the "Line/Column" part of the status bar, the tooltip will show you how many bytes/chars the document uses (in utf8 encoding). That should be enough for this kind of situation.
