### ISSUE TITLE
No Save Prompt on Exit for New File

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#203]
Greetings Kind Regards As you can see in the attached gif when the program is exited no save prompt is presented for a new file as has occurred w/ previous versions I do not know if this is a bug or intended behavior - Thank You Cheerio

![No Save Prompt](https://user-images.githubusercontent.com/48535920/133351479-a5910e6d-c585-4180-a555-7f305420af91.gif)

**Comment by stefankueng** [comment]
The button "load last session on start" has a submenu, if you've activated the entry "auto save on close" then unsaved files are automatically saved on close and restored on start.
