### ISSUE TITLE
Two New 1 files

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#204]
Two "New 1" files are present as shown in the attached screen shot One was created in a prior session and reloaded automatically The second was created in a subsequent session I do not know if this is a bug or designed behavior Kind Regards - Cheerio

![Two New 1](https://user-images.githubusercontent.com/48535920/133562165-976237d8-7f33-4fae-916e-6d33ac60dee7.png)

**Comment by stefankueng** [comment]
this is by design: when you create a new tab, there's a counter that's used to create the tab names. But there's no check whether a tab with the same name already exists.
