### ISSUE TITLE
Editor Corner Color in dark mode.

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#206]
In dark mode, when horizontal and vertical scrollbar are showed, right bottom corner color is different.
Can we change this color? Below is screen shot:

![image](https://user-images.githubusercontent.com/28701482/133931810-d8618ee2-6338-4ef4-a467-5eb5b7194359.png)

**Comment by stefankueng** [comment]
what color would you like there?

**Comment by kitepad** [comment]
1. v-scrollbar or h-scrollbar claim space.
2. may be better if color is same as scrollbar background, such as black in dark mode.
