### ISSUE TITLE
Drop down menu display incorrect.

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#207]
Some menu's dropdown list display incorrectly. Such as LoadAs, Lexer, Convert to. It seems check mark is lost. Tested version is 2.8.0 portable. And latest github's build is same problem.
For example: 
![image](https://user-images.githubusercontent.com/28701482/134114113-e986e9ee-ab82-4b12-a5fc-6a98906d36bc.png)

**Comment by kitepad** [comment]
I checked with previous version: 2.6.3/2.6.5, 2.7.0 - 2.8.0, github main.

Before 2.6.5 is correct. From 2.7.0, all versions is same issues.

**Comment by stefankueng** [comment]
As of Win10 19041, returning S_FALSE for a request for an item image resulted in the ribbon framework showing a nice checkmark for the selected item. But it seems that in Win11 this doesn't work anymore...
