### ISSUE TITLE
loading the file with the default code page 

### ISSUE THREAD

**Issue by TomSoft0** [stefankueng/BowPad#209]
this setting : 
          [Defaults]
          encodingnew=852
works fine for new files,
but how to have code page set after opening already existing file? 
would do well to : encodingload=852, but it doesn't work

**Comment by stefankueng** [comment]
in the "Other" tab, click the "Load as" dropdown button in the "Encoding" section, then select the encoding you want.

**Comment by TomSoft0** [comment]
I don't want to choose constantly, I want the Latin II code page to always be the default.

**Comment by stefankueng** [comment]
the default encoding when loading files is (if no encoding can be detected from the file itself) is the local windows codepage. You could try and change that.

**Comment by TomSoft0** [comment]
in settings :
[Defaults]
existing setting works fine : **encodingnew**
why can't use  e.g. :  **encodingload** ? 
that would fix the problem  (no encoding can be detected from the file itself)

**Comment by TomSoft0** [comment]
From the new version, the problem is solved. Thank you.
