### ISSUE TITLE
How delete one line in editor

### ISSUE THREAD

**Issue by wincaman** [stefankueng/BowPad#21]
Hello:
I need delete one line by shortcuts in direct mode.

I dont like used cmdcut, because I need first mark some block of lines and then delete.

I need delete in fast mode, I put this line in shortcuts.ini, but then not work
cmdLineDelete=Ctrl,M    , for example

What are the correct command ? 
Thank for your help.
Winca

**Comment by stefankueng** [comment]
Scintilla assigns the SCI_LINEDELETE command automatically to Ctrl+Shift+L
