### ISSUE TITLE
Still Inconsistent and Odd Spell Checker Behavior

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#212]
![still inconsistent and odd spell checker](https://user-images.githubusercontent.com/48535920/135710747-4873385f-438b-40fa-859f-6b964d8000c2.gif)

**Comment by stefankueng** [comment]
as I said in #208 this is expected **while** you're typing. The behavior is correct a few ms after you've stopped writing.

**Comment by PaltryProgrammer** [comment]
![aa you can see](https://user-images.githubusercontent.com/48535920/135719351-fa6af539-588c-4111-8ca0-4fa285e81bdd.png)

**Comment by stefankueng** [comment]
So instead of just saying that you would expect "aa" to be marked as wrong, you provide instead an animation and just assume I can guess what you mean?

"aa" is in fact correct, because the spell checker has a lot of abbreviations included.
