### ISSUE TITLE
Displayed zoom factor is not matched with selected and lost checked mark.

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#213]
When I zoom in/out font by status bar, actual zoom factor is not matched with selected, only 100% and 200% is matched. Tested version is 2.8.0, 2.6.5.

**Comment by stefankueng** [comment]
I'm sorry but I don't understand.
What do you mean by "zoom in/out font by status bar"?
Zooming is done by holding down the ctrl key while scrolling with the mouse wheel.

**Comment by kitepad** [comment]
Pls see screen shot:
1. 125% is selected
![image](https://user-images.githubusercontent.com/28701482/135781431-227acbaa-b8bf-4bff-a847-d238000a441a.png)
2. 150% is selected
![image](https://user-images.githubusercontent.com/28701482/135781472-2af22bb7-7838-4e7d-a367-ae0e30bba58e.png)
3. No check mark
![image](https://user-images.githubusercontent.com/28701482/135781524-d9d1820e-e987-4dcf-8273-41f94031409c.png)
