### ISSUE TITLE
Regex searching with Unicode characters freezes BowPad

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#219]
Please test with this sample file with a lot of Chinese characters (code page UTF-8):

[sample.txt](https://github.com/stefankueng/BowPad/files/7333868/sample.txt)

The search term is `第...章`, which matches quite a few phrases in the file.
![image](https://user-images.githubusercontent.com/12182730/137048226-246170c3-9482-4b7e-b40c-eef3ed222ac8.png)

As we press the _Find_ button to search downward, BowPad will get frozen (the characters on the title bar of the Search/Replace dialog marked yellow circle in the following screenshot indicated that BowPad was not responding).
![image](https://user-images.githubusercontent.com/12182730/137048349-656b87a8-16b7-4c29-9407-f6fbf8b516fc.png)

**Comment by wmjordan** [comment]
WinDbg has the following stack trace:
![image](https://user-images.githubusercontent.com/12182730/137050845-fbbf9a98-e714-4faf-b575-c90a99af2dd0.png)

I issued the `g`o command after taking the above screenshot in WinDbg and let the frozen BowPad run for a while, then Break the process in WinDbg and checked again. The stacks were just the same.

**Comment by stefankueng** [comment]
I have the highlight-matches checkbox checked as well.
I'll try some more...
