### ISSUE TITLE
Updated French translation

### ISSUE THREAD

**Issue by drocca69** [stefankueng/BowPad#22]
Hi,

I almost completed updated French translation but I cannot find the meaning of 4 strings:
"Find Result Action"
"Init Folding Margin"
"System Includes"
"User Includes"

Could you please explain these strings and tell me where they appear in the GUI?

Thanks in advance :)

Regards from France,
Etienne J.

**Comment by stefankueng** [comment]
"Find Result Action" is actually a hidden button, so you don't need to translate that text.
"Init Folding Margin" is also not shown - it's used for a command that initializes folding

"System Includes" and "User Includes" are used in the command button "Corresponding File".
For example, open the BowPad.cpp file, then that "Corresponding File" button gets enabled. If you then click on the arrow you'll get a list of include files, grouped together. And "System includes" and "User includes" are two of those group headers.

**Comment by drocca69** [comment]
Thanks for your quick answer.

Please find attached the updated French translation :)
[BowPad.fr.zip](https://github.com/stefankueng/BowPad/files/2544745/BowPad.fr.zip)

**Comment by drocca69** [comment]
Hi,

Please find attached the newly updated French translation:
[BowPad_fr.zip](https://github.com/stefankueng/BowPad/files/3520644/BowPad_fr.zip)
