### ISSUE TITLE
Fonts not rendering properly

### ISSUE THREAD

**Issue by jrapdx-001** [stefankueng/BowPad#227]
Some (though not all) fonts selected from the dropdown list initially render as expected.  However after an interval of minutes (or when switching buffers) the editor frequently reverts to a default font. (Default is proportional, not monospace.)

Screenshot with correctly rendered text:

![BowPad-font-rendered-OK-541x463-A](https://user-images.githubusercontent.com/93953827/142741884-5d148bb1-c95e-4a6d-84d9-5691781bf960.jpg)

After program reverts to default (_supposed_ to be 'Iosevka' but it's not):

![BowPad-font-NOT-rendered-541x463-A](https://user-images.githubusercontent.com/93953827/142741949-678e4b84-eb6c-49ae-a802-29cf75258b4f.jpg)

FWIW buffers will again show correct typeface on reselecting from the list. 

Also font variants, e.g., 'Iosevka Extended', don't work, such fonts aren't rendered at all.  (The same variants _are_ rendered OK in other editors.) 

Thanks for BowPad and looking into the issue. AFAICT (via search) there haven't been prior reports of similar font problems.

**Comment by jrapdx-001** [comment]
Interestingly the first font issue I reported disappeared after updating to BP 2.8.1 a few hours ago. However the second problem  remains (re: font variants not rendering).

**Comment by stefankueng** [comment]
I've installed the font "Iosevka extended", and it renders fine for me here.
Where did you get that font from? Or any other that doesn't work for you?

**Comment by jrapdx-001** [comment]
Yes it seems that other font families with variants exhibit the same issue: Source Code Pro, Victor Mono, Cascadia Code. Possibly there's a difference installing only a single font (vs. whole family).

_Iosevka_ is available here: https://github.com/be5invis/Iosevka/blob/v11.1.0/doc/PACKAGE-LIST.md. (Dozens of packages are listed, super-ttc-sgr-iosevka-11.1.0.zip contains the primary variants in multiple weights.)

BTW I'm running Windows 11, don't know if that matters. (FWIW system fonts setup appears identical to Windows 10.)

**Comment by stefankueng** [comment]
still works fine for me with that font.
go to "configure styles" and check if you've set a specific font there, or check the usersconfig file.
