### ISSUE TITLE
[FEATURE-REQUEST] Add markdown support.

### ISSUE THREAD

**Issue by CypherpunkSamurai** [stefankueng/BowPad#229]
Hi, I very much like the application, can you please add markdown support?

**Comment by stefankueng** [comment]
markdown files are already shown with proper colors (there's a markdown lexer).

**Comment by CypherpunkSamurai** [comment]
> markdown files are already shown with proper colors (there's a markdown lexer).

I was specifically looking for a markdown preview panel, is it currently possible to add it? :)

**Comment by stefankueng** [comment]
Sorry, but that's outside of a text editor realm.
