### ISSUE TITLE
Numeric Conversion Tool-Tip Questions

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#233]
Greetings Kind Regards The attached GIF demonstrates usage of the handy (thank you) numeric conversion tool-tip . However a few questions re/ its' display arise as demonstrated and shown below . May I also  please suggest for your kind consideration a means to copy to clipboard any of the converted values , to wit i.e. e.g. via mouse click upon an entry in the tool-tip or perhaps via keyboard selection e.g. x -> hex , etc. Thank You - Cheerio

PS Please note "uage" and "converson" are misspelled but not reported by spell checker as seen in GIF

0x01234
0x012345				? significance of dark bar at bottom , also note "significance" is reported as misspelled
0x0123456			! off screen if keyboard cursor too far to left
0xFFFFFFF			? significance of white bar at bottom

![BowPad Numeric Conversion tool-tip](https://user-images.githubusercontent.com/48535920/148667188-52e4c1e8-b816-42ea-bac1-ef80da03c425.gif)

**Comment by stefankueng** [comment]
ok, got the spell checking problem fixed.

The "dark bar at the bottom" shows the color the number would represent (RGB value). I'll try to make this more clear.

**Comment by stefankueng** [comment]
as for copying content of the tooltip: I don't see a way that would work. A tooltip can not get focus, so using the keyboard is not possible.

Also note that you can also type something like this:
0x100+200+sin(0.1)
if you select the whole text, the tooltip will show you the result of that equation.

**Comment by PaltryProgrammer** [comment]
Thank You for your kind reply . The calculator tool-tip is a nice feature . I noticed for most operations it is not necessary to select the equation , it is sufficient to merely hover . The exception is exponentiation to wit i.e. e.g. "2^2" . If the exponentiation symbol is in an equation selection is necessary . This is of course a minor matter however may I suggest not being able to copy the result to the clipboard is rather an inconvenience as it then becomes necessary to memorize the  result . May I present for your kind consideration the possibility to utilize a window other than a tool-tip to wit i.e. e.g. the window type utilized for displaying the clickable window upon hovering/selecting an internet address . Kind Regards
