### ISSUE TITLE
Spell Checker not Functioning

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#234]
Greetings and Kind Regards I pasted text into BowPad with correct spelling then modified one word as shown in the attached image .  You will observe the misspelled word is not indicated as such though Spell Checker is in fact enabled . A fix would be greatly appreciated as I rely on Spell Checker Thank You Kindly

![BowPad Spell Checker not functionin](https://user-images.githubusercontent.com/48535920/151644101-9b7a64d8-ff3e-4eaf-890c-b39ca33869c5.png)

**Comment by stefankueng** [comment]
do you use an official build? I made some fixes to the spell checker since the last official release...

**Comment by PaltryProgrammer** [comment]
The version I utilized is shown in the attached image . I only know I downloaded it from your site . So I presume it is "official" Thank You Kindly

![BowPad version](https://user-images.githubusercontent.com/48535920/151656763-89b4bec0-c25d-4391-8619-bbf9894cddb1.png)

**Comment by stefankueng** [comment]
ok, then we can assume that this is fixed now.
If you still experience the problems with the next release, feel free to reopen this issue.
