### ISSUE TITLE
Update to 2.8.2 not Functioning

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#239]
Greetings Kind Regards My current version is 2.8.1 Upon "Check for Updates" I am informed a new version is available . However the first and second buttons i.e. to wit "Download and install the update" and "Download the update" have no effect . Also upon "Visit our Website" and upon BowPad "Download" I am taken to GIT BowPad version 2.8.1 - Best

**Comment by stefankueng** [comment]
fixed now
