### ISSUE TITLE
Possible to disable the numeric forms tool tip

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#240]
I found that BowPad sometimes popped up the numeric tool tip while the cursor was not hovering on a number, for instance, something like `---`.

Accidentally the unintended appearance of the tip popped in the way while I was to select something, and eventually I clicked on the tip and the content in system clipboard was overwritten by the tip content, which was undesired.

Is it possible to disable that tool tip (maybe done by modifying the user config file)?

**Comment by stefankueng** [comment]
instead of deactivating the tooltip, let's fix the real problem: showing the tooltip for something that's not a number/equation.
With a simple `---` I could not reproduce this.
Do you have a text segment which shows this problem?

**Comment by wmjordan** [comment]
It seems to be quite random. I have difficulty to reproduce the problem.

And in most cases, at my side, I use BowPad to view and filter log files which are filled with timestamps, data values, but I seldom need the tip. I still hope that I can have a way to disable it, or make it appear only when Shift or another modifier key is pressed.

**Comment by wmjordan** [comment]
Perhaps, the functionality of the tip can be implemented via a plugin script?

**Comment by stefankueng** [comment]
Sorry, but I think a plugin can't really provide a tooltip.
And to avoid having the clipboard content overwritten: Windows has a history, just press Win+V instead of Ctrl+V.
I myself use this: https://github.com/sabrogden/Ditto

**Comment by wmjordan** [comment]
It does not necessary to be a tip. It may be a message box displaying those numeric forms with `Yes` and `No` buttons. Yes button copies contents to clipboard and no button closes the box.

The procedure may be:
1. user selects some characters with number or arithmetic expression.
2. user executes the plugin.
3. the plugin calculate the expression and display various numeric forms of the number or calculation result with a message box.
4. if a user needs to copy the result, he/she clicks the Yes button. Otherwise the No button.

**Comment by stefankueng** [comment]
I changed the tooltips to appear a line more above the cursor. So you should be able to select the text without accidentally clicking on the tooltip.

**Comment by wmjordan** [comment]
> I changed the tooltips to appear a line more above the cursor. So you should be able to select the text without accidentally clicking on the tooltip.

This can be of help.
Perhaps it is also appropriated to handle the mouse_down message. When a user clicks the editor window, he/she may want to begin selecting text, thus BowPad'd better hide the tooltip immediately.

**Comment by wmjordan** [comment]
Is it possible to hook the aforementioned mouse down event in the editor?

**Comment by stefankueng** [comment]
would you disable all tooltips or just the numeric one?
there's also a tooltip for urls.

**Comment by stefankueng** [comment]
disable the tooltip(s) with:
```
[View]
urltooltip=0
numtooltip=0
```

in the `settings` file

**Comment by wmjordan** [comment]
Thank you very much. It works.
