### ISSUE TITLE
Numeric forms tool tip displayed unexpectedly

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#243]
Reproduction:
1. Put the following text into the editor.
2. Click on the `-` within any `---`.
3. A tool tip displaying numeric forms for 0 will pop up.
   ![image](https://user-images.githubusercontent.com/12182730/156908128-11afa9b3-28ed-46e1-8588-4dbdfea19a12.png)

````text
---	0	0
---	0	0
---	0	0
---	0	0
---	0	0
---	0	0
````

**Comment by wmjordan** [comment]
I compiled the latest code today and could no longer reproduce this issue any more.
I will keep testing the new version and see whether it occurs again.

**Comment by stefankueng** [comment]
there's also a build available for every push. Go to https://github.com/stefankueng/BowPad/actions/workflows/msbuild.yml and then click on the latest green build. You'll see at the bottom two "Artifacts", one for ARM64 and one for x64 - these contain the built exe files.
