### ISSUE TITLE
Matching Highlight Misses Last Character

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#248]
Please see attached image Thank You Kindly - Best
![Matching Highlight Misses Last Character](https://user-images.githubusercontent.com/48535920/160002436-8e48a16e-31d7-49fc-875a-0cb3e23f5a0d.png)

**Comment by stefankueng** [comment]
this is already fixed:
https://github.com/stefankueng/BowPad/commit/fc34b955644b510602ccc172aa9eee304ffde866

either wait for a new release or get an automated build (only unsigned exe) from here:
https://github.com/stefankueng/BowPad/actions/runs/2017847916
