### ISSUE TITLE
Feature request: bowpad as git editor

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#249]
Currently specifying Bowpad.exe (version 2.8.1.2809) as the default git editor doesn't work (i.e. bowpad prompts the file does not exist and only closing bowpad entirely causes git to detect the closing of the file).

**Comment by stefankueng** [comment]
in the _upcoming version 2.8.10_ this will work by passing `/wait`.
to configure BP with git:
`git config --global core.editor "BowPad.exe -wait"`
