### ISSUE TITLE
Position Lost After Auto-loaded Externally Changed Document

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#25]
I've been using BowPad to monitor log files for quite a long time.
BowPad's feature of auto-reloading externally modified files is ideal for monitoring log files.
However, while I had placed the cursor at the middle of a document, which was updating by another process, and switch back to the main window of BowPad from outside of it. The display position got lost while BowPad reloaded the document as the document was growing long. BowPad appeared to scroll to the percentage position of the document rather than remaining at the position where the cursor was.

**Comment by stefankueng** [comment]
I think this got solved with issue  #26  - the underlying problem was the same.
