### ISSUE TITLE
vs2022 build issue

### ISSUE THREAD

**Issue by hongnod** [stefankueng/BowPad#251]
Build Bowpad with VS2022,there is error item:
E0035	:  The <experimental/coroutine> and <experimental/resumable> headers are only supported with /await and implement pre-C++20 coroutine support. Use <coroutine> for standard C++20 coroutines.	CustomActions	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\experimental\coroutine	36

**Comment by stefankueng** [comment]
I don't get that error.
Also it doesn't show up on the auto-build here:
https://github.com/stefankueng/BowPad/runs/5740990009?check_suite_focus=true

**Comment by hongnod** [comment]
![image](https://user-images.githubusercontent.com/6680267/164566477-f4cca4f5-5460-4fe1-a182-0d5da010f36e.png)
Set to C++17 works.

**Comment by hongnod** [comment]
![image](https://user-images.githubusercontent.com/6680267/164566566-541e1cb0-e9a8-4c4a-9788-369271c7177f.png)
ISO C++17 Standard (/std:c++17)  works.

**Comment by stefankueng** [comment]
I know that c++17 doesn't show those errors. But as I said: I don't see that error with a fresh clone/checkout.

**Comment by hongnod** [comment]
not a problem
