### ISSUE TITLE
Feature request: Plugin write status bar function

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#255]
I am developing a plugin and I need to output some information from the plugin for debugging purpose.
However, `BowPad.alert` takes the focus away from BowPad, `BowPad.debugprint` requires a debugger which is overkill.

Is it possible to add a function to write some text to the status bar?

**Comment by stefankueng** [comment]
you can also use dbgview instead of a full debugger: https://docs.microsoft.com/en-us/sysinternals/downloads/debugview

**Comment by wmjordan** [comment]
Oh, I've overlooked and forgotten dbgview. Thank you for reminding me that.
