### ISSUE TITLE
Feature request: option to automatically trim whitespaces on save

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#256]
Instead of manually pressing trim whitespaces to remove whitespace(s) at end of line automatically trim whitespaces if saving.

**Comment by wmjordan** [comment]
If the plugin script APIs provide a way to do something before saving and allow the script to execute the Trim command which already exists in BowPad, this request can be implemented via plugin script within minutes.

**Comment by stefankueng** [comment]
with the last commit, you can use the new ExecuteCommand command:
`BowPad.ExecuteCommand(85);`

**Comment by wmjordan** [comment]
I got stuck while compiling the source code after upgrading to VS 2022 (actually version 17.3 preview 3).

The compiler complained that `std:otringstream` has something wrong:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/12182730/179125786-8a68156c-a925-4ad8-9eef-b77fe8d6736a.png">

Your code used to be compiled successfully without any problem.
Too weird. Must be something wrong with VS preview.

**Comment by wmjordan** [comment]
Previously, the `IsChecked` callback has a comment "_not used yet by BowPad, but planned for the future_". Is it used in the recent version?

If it is used, the `Execute` callback can be used to toggle the checked state and use `WriteSetting` to persist the state.
The auto-trim-before-saving function will be executed when the command is checked.

**Comment by stefankueng** [comment]
the problem is that the gallery control which is used to show the list of plugin commands does not allow for a checked state. So at the moment I have no idea on how to do that.

**Comment by wmjordan** [comment]
Can the text of the plugin be changed at runtime? If so, we can add some text after the the plugin name to indicate that it is " _(disabled)_"
