### ISSUE TITLE
Spell Checker language

### ISSUE THREAD

**Issue by Fraxlin** [stefankueng/BowPad#258]
How can I select a different language for spell checking? 
In the language menu I only see two:
![Spell checker](https://user-images.githubusercontent.com/88848258/169982378-38293166-1ac3-4c4d-a050-4f6b6a791163.png)

**Comment by stefankueng** [comment]
you can install other spell checkers from the windows settings. Somewhere in there you can download and install additional languages for Windows - but if you only need the spell checkers you should uncheck what you don't need from that additional language.

**Comment by Fraxlin** [comment]
I installed an additional language pack from Windows settings and BowPad showed it right away ... thank you!!
