### ISSUE TITLE
Edit Selection command was not working as expected in some cases

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#259]
Case 1: Given the following snippet:

````
123 456
345 678
````

Select one of the space, and execute the Edit Selection command.
Only the selected space is selected, the other one is not.
Expected result: two spaces in line 1 and line 2 respectively were selected to be modified.

Case 2: Given the following snippet:

````
123:{456}
345:{456}
````

Select the last `{456`, and execute the Edit Selection command.
Only the last instance of `{456` is selected.

**Comment by stefankueng** [comment]
as for the single space: the selection is automatically trimmed. Which leads in this case to an empty selection.
Not sure this should change...
