### ISSUE TITLE
auto completion triggered by key shortcut and list matched word in current document

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/BowPad#263]
Currently, auto completion is by lexer config. Can we have another auto completion style like scite (from scintilla.org)? It's triggered by key shortcut and list matched word in current document, config is not need.

_Originally posted by @kitepad in https://github.com/stefankueng/BowPad/issues/156#issuecomment-1159620367_

**Comment by kitepad** [comment]
In scite, this feature is called "Complete Word".  It's useful for my work:
1.  Create some small files like html, js, css file.
2.  Input file content with some repeated text, such as define a js function and input function name, repeat html tag name, 
     repeat css property name.

This feature can help user to save more time when edit file in BowPad.

**Comment by kitepad** [comment]
I spend half day to learn from scite and taken some code to add "Complete Word" to BowPad autocomplete. It's a experiments and I'm not sure whether have copyright issues for taken source code. If you have interesting this, you can following steps:
1. add below source code in AutoComplete.cpp and place before HandleAutoComplete method.
2. add    PrepareWordList(&wordSet,m_editor); after       std::map<std::string, AutoCompleteType> wordSet;

Source code from scite with modification:
`namespace SA = Scintilla;

class TextReader
{
protected:
    static constexpr Scintilla::Position extremePosition = INTPTR_MAX;
    /** @a bufferSize is a trade off between time taken to copy the characters
     * and retrieval overhead.
     * @a slopSize positions the buffer before the desired position
     * in case there is some backtracking. */
    static constexpr Scintilla::Position bufferSize = 4000;
    static constexpr Scintilla::Position slopSize   = bufferSize / 8;
    char                                 buf[bufferSize + 1];
    Scintilla::Position                  startPos;
    Scintilla::Position                  endPos;
    int                                  codePage;

    Scintilla::ScintillaCall& sc;
    Scintilla::Position       lenDoc;

    bool InternalIsLeadByte(char ch) const
    {
        if (Scintilla::CpUtf8 == codePage)
            // For lexing, all characters >= 0x80 are treated the
            // same so none is considered a lead byte.
            return false;
        else
            return ::IsDBCSLeadByteEx(codePage, ch) != 0;

    }
    void Fill(Scintilla::Position position)
    {
        if (lenDoc == -1)
            lenDoc = sc.Length();
        startPos = position - slopSize;
        if (startPos + bufferSize > lenDoc)
            startPos = lenDoc - bufferSize;
        if (startPos < 0)
            startPos = 0;
        endPos = startPos + bufferSize;
        if (endPos > lenDoc)
            endPos = lenDoc;
        sc.SetTarget(SA::Span(startPos, endPos));
        sc.TargetText(buf);
    }

public:
    explicit TextReader(Scintilla::ScintillaCall& sc_) noexcept
        : startPos(extremePosition)
        , endPos(0)
        , codePage(0)
        , sc(sc_)
        , lenDoc(-1)
    {
        buf[0] = 0;
    }

    // Deleted so TextReader objects can not be copied.
    TextReader(const TextReader& source) = delete;
    TextReader& operator=(const TextReader&) = delete;
    char        operator[](Scintilla::Position position)
    {
        if (position < startPos || position >= endPos)
        {
            Fill(position);
        }
        return buf[position - startPos];
    }
    /** Safe version of operator[], returning a defined value for invalid position. */
    char SafeGetCharAt(Scintilla::Position position, char chDefault = ' ')
    {
        if (position < startPos || position >= endPos)
        {
            Fill(position);
            if (position < startPos || position >= endPos)
            {
                // Position is outside range of document
                return chDefault;
            }
        }
        return buf[position - startPos];
    }
    bool IsLeadByte(char ch) const
    {
        return codePage && InternalIsLeadByte(ch);
    }
    void SetCodePage(int codePage_) noexcept
    {
        codePage = codePage_;
    }
    bool Match(SA::Position pos, const char* s)
    {
        for (int i = 0; *s; i++)
        {
            if (*s != SafeGetCharAt(pos + i))
                return false;
            s++;
        }
        return true;
    }

    int StyleAt(SA::Position position)
    {
        return sc.UnsignedStyleAt(position);
    }

    SA::Line GetLine(SA::Position position)
    {
        return sc.LineFromPosition(position);
    }

    SA::Position LineStart(SA::Line line)
    {
        return sc.LineStart(line);
    }

    SA::FoldLevel LevelAt(SA::Line line)
    {
        return sc.FoldLevel(line);
    }

    SA::Position Length()
    {
        if (lenDoc == -1)
            lenDoc = sc.Length();
        return lenDoc;
    }

    int GetLineState(SA::Line line)
    {
        return sc.LineState(line);
    }
};

static void PrepareWordList(std::map<std::string, AutoCompleteType>* wordList, CScintillaWnd* m_editor)
{
    const std::string wordCharacters         = "_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    bool              autoCompleteIgnoreCase = false;

    auto               lineLen   = m_editor->Scintilla().GetCurLine(0, nullptr);
    const std::string  line      = m_editor->Scintilla().GetCurLine(lineLen); // GetCurrentLine();
    const SA::Position caret     = m_editor->Scintilla().CurrentPos();
    const SA::Line     ln        = m_editor->Scintilla().LineFromPosition(caret);
    const SA::Position lineStart = m_editor->Scintilla().LineStart(ln);
    const SA::Position current   = caret - lineStart;

    SA::Position startword = current;
    // Autocompletion of pure numbers is mostly an annoyance
    bool allNumber = true;
    while (startword > 0 && (wordCharacters.find(line[startword - 1]) != std::string::npos))
    {
        startword--;
        if (line[startword] < '0' || line[startword] > '9')
        {
            allNumber = false;
        }
    }
    if (startword == current || allNumber)
        return; // true;

    const std::string    root       = line.substr(startword, current - startword);
    const SA::Position   rootLength = root.length();
    const SA::Position   doclen     = m_editor->Scintilla().Length();
    const SA::FindOption flags =
        SA::FindOption::WordStart | (autoCompleteIgnoreCase ? SA::FindOption::None : SA::FindOption::MatchCase);
    const SA::Position posCurrentWord = m_editor->Scintilla().CurrentPos() - rootLength;

    m_editor->Scintilla().SetTarget(SA::Span(0, doclen));
    m_editor->Scintilla().SetSearchFlags(flags);
    SA::Position posFind = m_editor->Scintilla().SearchInTarget(root);
    TextReader   acc(m_editor->Scintilla());
    while (posFind >= 0 && posFind < doclen)
    { // search all the document
        SA::Position wordEnd = posFind + rootLength;
        if (posFind != posCurrentWord)
        {
            while (wordCharacters.find(acc.SafeGetCharAt(wordEnd)) != std::string::npos)
                wordEnd++;
            const SA::Position wordLength = wordEnd - posFind;
            if (wordLength > rootLength)
            {
                const std::string word = m_editor->Scintilla().StringOfSpan(SA::Span(posFind, wordEnd));
                wordList->insert({word, AutoCompleteType::Snippet});
            }
        }
        m_editor->Scintilla().SetTarget(SA::Span(wordEnd, doclen));
        posFind = m_editor->Scintilla().SearchInTarget(root);
    }
}
`
