### ISSUE TITLE
Italian translation update

### ISSUE THREAD

**Issue by Hexaae** [stefankueng/BowPad#267]
Here is updated Italian translation.
I used ResourceHacker directly to modify also some gadgets (were too long/short for the ITA strings).
Attached file: [BowPad_it.zip](https://github.com/stefankueng/BowPad/files/9040742/BowPad_it.zip)

**Comment by stefankueng** [comment]
please translate the po file instead of hacking the binary file. Those files are automatically generated from the po file.
https://github.com/stefankueng/BowPad/blob/main/Languages/BowPad_it.po

**Comment by Hexaae** [comment]
The problem is that I've had to resize also some UI elements to fit the new strings, that's why I used RH

**Comment by stefankueng** [comment]
tell me which UI elements you resized, and I'll try to resize them in the main UI for all languages

**Comment by Hexaae** [comment]
OK...
![image](https://user-images.githubusercontent.com/8591462/177290189-5f0bb8bf-c0bd-49e6-aee7-3f417664686f.png)
![image](https://user-images.githubusercontent.com/8591462/177290321-04a841a2-1db9-44dd-98fd-a977059ceab3.png)
