### ISSUE TITLE
ZH_CN Lang files for version 2.4.3

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#27]
Please use it:
[BowPad_zh-CN.zip](https://github.com/stefankueng/BowPad/files/2801022/BowPad_zh-CN.zip)

**Comment by stefankueng** [comment]
please send a patch for the po file instead. I'm not putting binary files online that I haven't built myself.

**Comment by wmjordan** [comment]
I used a localization tool to build those DLL files, according to your description here:
https://github.com/stefankueng/BowPad/issues/1#issuecomment-378370055

Consequently no po file was available since the DLL files were directly generated by the localization tool.

**Comment by stefankueng** [comment]
That tool is meant to be used only for testing the translation.
The right way is to translate the po file:
https://github.com/stefankueng/BowPad/blob/master/Languages/BowPad_zh-CN.po

The language binaries are then built from those.

**Comment by wmjordan** [comment]
OMG, that's miserable.
I trashed the po translation project after building the DLL files.

**Comment by songbaoming** [comment]
This version is old.
