### ISSUE TITLE
Request About Box Button to Copy version to Clipboard

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#274]
Greetings Kind Regards May I please suggest a button in the About Box which copies the version to the clipboard. I am surprised this is not sine qua non for all applications. - Best Cheerios

**Comment by stefankueng** [comment]
I'll just change the label to a readonly edit control, so you can select the text and use Ctrl+C to copy it to the clipboard.
A separate button is a little bit overkill in my opinion.
