### ISSUE TITLE
How to set custom language highlighting？

### ISSUE THREAD

**Issue by wangdemon** [stefankueng/BowPad#276]
I have a custom programming language, how to set the highlight of the custom language
![1](https://user-images.githubusercontent.com/20681339/182187655-d7a4c073-7714-4b92-ac18-d324aa323eaf.PNG)
.

**Comment by wangdemon** [comment]
How to format the custom language code

**Comment by stefankueng** [comment]
see here : https://tools.stefankueng.com/BowPad_lexerconfig.html

**Comment by wangdemon** [comment]
Thank you. I can already set the highlight.I have two more questions:
1 How to set BodPad background color, I like the black background. I want to set the bowpad to a black background, just like the black theme of vscode.
2 How to format code, vscode can format code with alt+shift+f shortcut keys

**Comment by wangdemon** [comment]
Thank you. I can already set the highlight. I have another question. How to format code,  like vscode, I can format the code with shortcut keys.

**Comment by stefankueng** [comment]
formatting code would depend on the language. VS code uses plugins for that.
You can only use an [editorconfig ](https://editorconfig.org/)file.
