### ISSUE TITLE
Request Download File Hash

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#277]
Greetings Kind Regards I do not recall seeing a hash of each download file. May I suggest provide same if not already done so. - Cheerio

**Comment by stefankueng** [comment]
What would that be useful for?
If you want to ensure that the file hasn't been messed with, just verify the digital signature of the msi or exe.

**Comment by PaltryProgrammer** [comment]
Thanks I didn't know about such things. I was wondering what that meant in a file Properties. - Cheerio
