### ISSUE TITLE
Question about highlight

### ISSUE THREAD

**Issue by Adminny** [stefankueng/BowPad#278]
I use old version 2.0.12 due strong highlight.
Left side - 2.0.12
Right side - the latest version
![bow](https://user-images.githubusercontent.com/77626266/186180257-e8cd9977-dd81-4b78-9be1-c65af2aeb4cd.png)

Is it possible in the new version to choose the degree of highlight: light or strong?

**Comment by stefankueng** [comment]
open the `settings` file (either in the bin directory where bowpad.exe resides, or in `%appdata%\bowpad`), then either delete the entry
```
[View]
bracehighlighttext=0
```
or change the value to 1 and save the file, then open BP again.

Not sure how/why that setting got changed to `=0` though...

**Comment by Adminny** [comment]
Thanks for answer.
It doesn't work for me. No changes. The same is very light.
Also in the last version the highlight disappears in 5 seconds.
In the old version the highlight is constant.

**Comment by stefankueng** [comment]
well, the highlighting was made lighter on purpose, as was the decision to make it disappear after 5 seconds.
Because the original highlighting was too obvious/annoying.
