### ISSUE TITLE
feature request: Column paste

### ISSUE THREAD

**Issue by ljohnson1980** [stefankueng/BowPad#28]
Provide either a paste special, or context menu entry that permits lines on the clipboard (from some other app) to be pasted as a column at the current cursor position (maintain X position as when pasting columnar data captured from within Bowpad).

Example:

Building a table where the language constructs such as parens, commas, comments, and so forth are already in the file. Fields for the matrix are organized in the file in columns visually.

Obtain data to fill a given field from a spread sheet or database program. This comes into the clipboard as lines.

Place the cursor at the top of the matrix field, right click, select "Paste as column".

Now the field is populated.

My current approach is to paste the data as lines near the destination structure.
Select the column of data as columnar data (Alt+mouse selction)
Go to the top of the destination column
Paste.

This feature would save many keystrokes.

There are times I can have the spreadsheet generate the entire code line and eliminate this process altogether, however, some spreadsheets or other data sources are things I have no control over and must use the raw data.

Thanks

**Comment by wmjordan** [comment]
I am the second on requesting this feature.

**Comment by stefankueng** [comment]
I'm not sure how this is different from:
hold down ALT key, click on a column, drag the pointer downwards: you'll get a "cursor" that covers the whole column. Now hit Ctrl+V to paste.

**Comment by wmjordan** [comment]
Maybe this issue could be closed.

Previous version of BowPad was lacking such a feature. But recent versions, it was realized by the Scintilla perhaps.
