### ISSUE TITLE
Should I care this warning: C6262 ?

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#280]
When I run code analysis on BowPad.cpp, I got this message: D:\BowPad2\src\BowPad.cpp(439): warning C6262: Function uses '141404' bytes of stack.  Consider moving some data to heap.

I'm beginner of win32, and not sure if I resolve this warning? No warning when I build solution.

**Comment by stefankueng** [comment]
you can usually ignore this warning. Unless the function/method in question is called recursively (i.e. if it calls itself).
User mode processes (i.e. all apps/programs that are not drivers or special services) get 2MB of stack. So if the warning does not tell you that the function uses a lot of that, you can ignore it.
