### ISSUE TITLE
Crash when spell checker is activated

### ISSUE THREAD

**Issue by dosware** [stefankueng/BowPad#282]
Installed 2.8.4.2924 (64-bit) (WIndows 10) over the previous stable version. Have had no issues with BowPad previously. With 2.8.4.2924 (64-bit), the program/ interface loads fine. Typing new text in the default window initially is ok, but after a few words of text, the program crashes without any error message when attempting to space or backspace. So nothing I can attach.  Is there a debugging / log error mode?

**Comment by stefankueng** [comment]
I can't reproduce this.
Do you start with an empty document?
What text do you enter?
Can you reproduce this by starting with a new document?
What lexer is active? (e.g., Text, C++, html, ...)

**Comment by stefankueng** [comment]
by any chance: do you have spell checker activated?

**Comment by dosware** [comment]
Yes- the Spell Checker was activated and when I turn it off, the program no longer crashes. So that appears to be the issue.

Thanks, RIch
