### ISSUE TITLE
AutoClose not working

### ISSUE THREAD

**Issue by AccoII** [stefankueng/BowPad#285]
I've just unzipped BowPad64-2.8.5-portable and it doesn't autoclose html tags such as <p> which my previous version BowPad64-2.6.5-portable does. I have searched the interface and enabled the Autocomplete and AutoBraces options and the new version still doesn't autoclose any html tags. Can you offer me some advice please? I don't know whether this is intentional or something I need to do.

Thanks and great program by the way - I use it a lot.

Accoii

**Comment by stefankueng** [comment]
the autoclose was changed because the way it was caused too many annoyances for users.
For closing xml tags, you now have to type `</` to get the autocompletion hint to close the tag, and then just hit enter.
