### ISSUE TITLE
Find in Files apparent error

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#286]
Please see attached PNG demonstrates apparent error re/ Find and replace -> Find Files. As you can see it reports "Found: 0 matches." while the PNG also shows a file in the Folder to search containing the searched for text. - Kind Regards
![Screenshot (16)](https://user-images.githubusercontent.com/48535920/196006800-30b72c08-6d24-473d-9684-25cbd58c865f.png)

**Comment by stefankueng** [comment]
you've also limited the search files named "amazon" (box left of "Find files" button). So while the text "amazon" is found in the shown file, the filename of that file is not "amazon" so "find in files" can not find that.
