### ISSUE TITLE
Cascadia Code Font Incorrect Appearance

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#287]
Greetings Kind Regards Thank You for providing BowPad. In the attached PNG please note the appearance of font Cascadia Code as appears in BowPad is different from that in Visual Studio. The correct appearance can be confirmed via https://github.com/microsoft/cascadia-code

![Cascadia Code Font Incorrect Presentation](https://user-images.githubusercontent.com/48535920/197061031-5bcae5f0-e95e-4f24-a729-364c53d664f6.png)

**Comment by stefankueng** [comment]
works fine for me here.

**Comment by PaltryProgrammer** [comment]
Thank You for investigating. Cascadia Code works fine for me here also. I do not know why prior it did not. It may be prior I inadvertently utilized Cascadia Code Light instead of Cascadia Code as Cascadia Code Light and some but all other variants do not display as should in BowPad.
