### ISSUE TITLE
Limit code pages in a smaller set

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#288]
I have a file that BowPad always insists that the file is encoded in ISO 8859-7. But obviously I don't speak Greek.

Is it possible to limit the possible code pages to a smaller set?
For instance, adding the following lines into the _settings_ file can limit the possible code pages to five that are used BowPad's auto file encoding detection scope.
````ini
codepages=0,65001,1200,1201,936
````
The `0` stands for ANSI encoding, and `65001` is UTF-8, `1200` is UTF16LE, etc.

**Comment by wmjordan** [comment]
The sample file is like the following: 
[test.txt](https://github.com/stefankueng/BowPad/files/9874643/test.txt)

It is detected as Greek on several computers.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/12182730/198163401-880ef831-e703-450f-8a9f-dc6a2d1eb99e.png">

The ANSI encoding (code page 936 on my computer) should read like the following:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/12182730/198163590-3b9118f2-7cd7-4152-a899-7405adc03b19.png">

**Comment by stefankueng** [comment]
unfortunately, the uchardet lib does not provide a way to get the 'confidence' of the detection, nor to limit the detection to only certain codepages.
So I'd have to disable uchardet detection completely via uchardet...

**Comment by wmjordan** [comment]
Oh, I see.
I once worked with the C# ported version of uchardet and I met with the same problem.
Since documents handled by my project were all encoded in Chinese encodings or UTF encodings. Thus I customized the `nsUniversalDetector` to include UTF-8 and Chinese related probers only.

To limit the detection to only certain codepages, we have to pull the logic of `nsUniversalDetector` out and customize it. For instance, European users seldom handle Chinese documents. They can disable the `nsMBCSGroupProber`. And Chinese, Japanese or Korean users might want to disable the Latin-1 prober.

The customization can be done by intercepting https://github.com/freedesktop/uchardet/blob/23a664560b79715c04cbf73a7e2771e26086b210/src/nsUniversalDetector.cpp#L187-L206

and

https://github.com/freedesktop/uchardet/blob/23a664560b79715c04cbf73a7e2771e26086b210/src/nsUniversalDetector.cpp#L317-L331

**Comment by stefankueng** [comment]
patching uchardet won't help at all.
Even if I change the confidence lever according to the current language/codepage of the user it doesn't help.
Confidence of Greek is 0.6, confidence of codepage 936 is zero!

I'll just add a setting to disable uchardet.

**Comment by wmjordan** [comment]
Thank you for working on this issue.
Which setting can be used to disable the uchardet?

**Comment by stefankueng** [comment]
in the settings file
```
[Defaults]
useUCharDet=0
```

**Comment by wmjordan** [comment]
Great.
It is working well on my machine now.
