### ISSUE TITLE
Check Spelling Fail

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#289]
Greetings Kind Regards Thank You for providing BowPad Attached please find GIF demonstrates check spelling fail. Attached also is the text file shown.
[Chcek Spelling Fail.zip](https://github.com/stefankueng/BowPad/files/9942915/Chcek.Spelling.Fail.zip)
[Consider Today Or Soon.txt](https://github.com/stefankueng/BowPad/files/9942917/Consider.Today.Or.Soon.txt)

**Comment by stefankueng** [comment]
are you using the latest version? Because the spelling error is shown for me here, using your test file

**Comment by stefankueng** [comment]
ok, I think I see the problem now.
