### ISSUE TITLE
Drag selected text to top or bottom doesn't auto scroll

### ISSUE THREAD

**Issue by ljohnson1980** [stefankueng/BowPad#29]
I don't remember this failing in Bowpad, but now, when I select text and then click and drag to somewhere else, it only works if I don't need to scroll.

I can drop the selected text somewhere else on the screen, but if I need to scroll up or down, all I get is the modified cursor indicating illegal action. (b/w stop -- circle with bar)

Otherwise, great editor. My preferred platform. Thanks!

**Comment by stefankueng** [comment]
This needs to be done in the Scintilla control.
Tried to add such a scrolling behavior in BP but Scintilla captures the mouse while text is dragged, so there's no way to do that in BP.
