### ISSUE TITLE
two New 1

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#290]
Greetings Kind Regards Thank You for providing BowPad I utilize it daily. Attached please find PNG demonstrates two "New 1" I do not know if this is an error so I present for your determination. Thank You Kindly
![two New 1](https://user-images.githubusercontent.com/48535920/200994791-7b17b6ff-7cd3-44dd-9945-617cddaaeddc.png)

**Comment by stefankueng** [comment]
my guess is that you closed BP with one "New 1" still open and not saved. But you have the "Auto-save on close" active (I think). Which means when you start BP again, that "New 1" is reopened. When you then create a new tab, the count starts again at 1 so you get two "New 1" tabs.
