### ISSUE TITLE
minor bug tab right arrow not highlighted

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#291]
This is to report a minor bug re/ the tab right arrow. The attached GIF demonstrates Thank You Kindly Current Version shown in PNG

![Minor Bug right tab arrow not highlighted cropped](https://user-images.githubusercontent.com/48535920/202898252-bb958f8e-efc6-4396-86cf-94a03b2716ae.gif)
![current version](https://user-images.githubusercontent.com/48535920/202898357-d7043f8c-44c6-45cd-acac-b759f89187d4.png)

**Comment by stefankueng** [comment]
what gif?

**Comment by PaltryProgrammer** [comment]
Please see attached PNG indicates buttons either which to click to activate GIF
![Here GIF](https://user-images.githubusercontent.com/48535920/203173963-af16d98e-7b17-4995-b676-b58b1c89f104.png)

**Comment by stefankueng** [comment]
gifs don't need to be started. But it wasn't showing up at all yesterday...
arrow button is disabled if the rightmost tab is visible, but I'll change it a little...
