### ISSUE TITLE
Tab buttons disappeared since recent commits

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#292]
I synced the source code to the last commit and compiled the code.
I found that tab buttons were gone in the compiled version.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/12182730/209336484-34d93c95-b6d7-4ed1-a52f-bee333f0f597.png">

I checked out to the _make the current tab more stand out_ commit and the compiled executable was the last working version.
Since the _fix drawing tabs at the right end of the window_ commit, the tab buttons were invisible on my computer.

**Comment by stefankueng** [comment]
Ups, my bad. They're not drawn because you don't have enough files open to show the spin box. Since I always have at least 10 files open, I never noticed the problem.

**Comment by wmjordan** [comment]
Thank you. It is working properly now.

On the contrary, I seldom had more than 10 files open.
7 is my usual upper bound :)
