### ISSUE TITLE
Tab buttons were not responding to left mouse clicks

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#296]
I compiled the recent code and found that tab buttons were not responding to left mouse clicks, unless I had more documents opened and tab buttons could not be completely displayed on the tab bar.

Could it be caused by the recent commits?

**Comment by stefankueng** [comment]
do you have the latest version?
https://github.com/stefankueng/BowPad/commit/f4b3dd1df583d3446e1bd7cc6329b3ba179b9bf1

**Comment by wmjordan** [comment]
Oops, I forgot to pull the commits.
Sorry for the trouble.
