### ISSUE TITLE
Feature Request Set Background Color

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#298]
Kind Regards May i please request feature i.e. to wit set background color . Thank You Kindly . i find the default white too bright and the dark theme black too dark . My preferred background as set in Visual Studio is RGB (255 , 248 , 231) which incidentally is the color of the universe . [https://science.nasa.gov/cosmic-latte-average-color-universe] Thank You Kindly

**Comment by PaltryProgrammer** [comment]
thank you however only the text is affected .

![image](https://github.com/stefankueng/BowPad/assets/48535920/810ca6ac-c08e-4f1c-babb-55e65cc32cd7)

**Comment by stefankueng** [comment]
I think the solution here would be to use the text background of the "default" style of a lexer as the window background.

**Comment by PaltryProgrammer** [comment]
thank you kindly . however i am unable to locate means to set the text background of the default style of a lexer as the window background control .
