### ISSUE TITLE
Objeck syntax highlighting for BowPad

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [stefankueng/BowPad#302]
I asked for a Scintilla lexer for Objeck at Lexilla but they are not yet added it: https://github.com/ScintillaOrg/lexilla/issues/121

I know BowPad supports user defined lexer. Could you make a lexer for Objeck? Thank you.

p/s: This is Objeck: https://github.com/objeck/objeck-lang

**Comment by stefankueng** [comment]
the user defined lexer is just that: user defined
that means you as the user have to do it yourself.
