### ISSUE TITLE
Crashed BowPad

### ISSUE THREAD

**Issue by 1997tn** [stefankueng/BowPad#306]
How to reproduce: download https://github.com/k-john-gough/gpcp/releases/download/v1.4.08-beta3/gpcp-NET1.4.08b3.zip, extract and open gpcp-NET\documentation\Examples\Forms.cp in BowPad, set the lexer to Modula as BowPad doesn't support Component Pascal, scroll down a while and BowPad started to freeze.

**Comment by stefankueng** [comment]
I can not reproduce this. File opens fine for me, without any freezing.
Assuming you mean the file `Form.cp` since there's no `Forms.cp` file.

and next time, please just attach the file to this issue instead of having me download huge files just to extract and find one single file.

**Comment by 1997tn** [comment]
Try scrolling down a while, it doesn't happen immediately after you opened the file.

**Comment by stefankueng** [comment]
created an issue in the right place: https://github.com/ScintillaOrg/lexilla/issues/128

and please, next time just attach the file in question here. I don't like to download huge zips and have to extract and then search for a single small file.
