### ISSUE TITLE
Modula lexer bug

### ISSUE THREAD

**Issue by 1997tn** [stefankueng/BowPad#309]
MOD is a keyword for modulo on both Modula-2 and Modula-3. The problem is, if MOD is part of another word, e.g: HMOD, it will also highlight MOD like this: H**MOD**. It should only highlight MOD when it's a standalone word!

**Comment by stefankueng** [comment]
That's a problem of the modula lexer in lexilla

**Comment by 1997tn** [comment]
> That's a problem of the modula lexer in lexilla

OK. I will report on Lexilla.

**Comment by 1997tn** [comment]
https://github.com/ScintillaOrg/lexilla/issues/129
