### ISSUE TITLE
Awk syntax highlighting

### ISSUE THREAD

**Issue by cup** [stefankueng/BowPad#31]
please and thank you

**Comment by stefankueng** [comment]
just use the 'Bash' lexer.

**Comment by cup** [comment]
https://github.com/ProgerXP/Notepad2e/issues/216

**Comment by cup** [comment]
@stefankueng i would rather avoid that if possible - as Awk is different enough
for it to be annoying - here are some other implementations if it helps:

- https://github.com/ProgerXP/Notepad2e/blob/302735c/src/Styles.c#L1629
- https://github.com/rizonesoft/Notepad3/blob/master/src/StyleLexers/styleLexAwk.c
- https://github.com/zufuliu/notepad2/blob/master/src/EditLexers/stlAwk.c

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5530

**Comment by stefankueng** [comment]
https://sourceforge.net/p/scintilla/bugs/765/
