### ISSUE TITLE
Bowpad refuses to minimize if pressing on taskbar entry after typing

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#312]
If opening bowpad then without typing pressing the bowpad taskbar entry bowpad minimizes.
If opening bowpad then typing then pressing the bowpad taskbar entry bowpad is not minimized and "Windows Background.wav" is played.

I tested notepad.exe as well and there notepad minimizes always regardless of what seems to be focus related.

OS: Windows 10
Bowpad version: 2.8.7.2960 (64-bit)

**Comment by Wallby** [comment]
> I'm sorry, but I can not reproduce this. I tried both Win11 and a Win10 station.

It doesn't always happen. It seems to never happen ever if you wait for a while before closing after stopping typing. When I tried to close it quickly after I've stopped typing it happened often but not always.

**Comment by Wallby** [comment]
> > I'm sorry, but I can not reproduce this. I tried both Win11 and a Win10 station.
> 
> It doesn't always happen. It seems to never happen ever if you wait for a while before closing after stopping typing. When I tried to close it quickly after I've stopped typing it happened often but not always.

To be extra clear what I meant..
If you stop typing then wait long enough before minimizing bowpad from the taskbar this never happened for me.
If you stop typing then quickly minimize bowpad from the taskbar this sometimes happens for me.

**Comment by Wallby** [comment]
I am quite confident this animation of the red markings underneath the text is what causes it, if you try to minimize before it has finished (i.e. reached the bottom) this happens every time, thus it is not "sometimes".

![2023-02-10-13-00-37](https://user-images.githubusercontent.com/13614975/218087845-44df847b-d112-4f10-a245-96e826664905.gif)

**Comment by stefankueng** [comment]
Thanks, that helped with reproducing the problem.
I can improve the situation, but there will always be a small time where this could still happen. However I do not consider this a big problem, only a small annoyance.
