### ISSUE TITLE
The close icon in tabs and number in combo boxes couldn't be displayed correctly in different Windows Versions.

### ISSUE THREAD

**Issue by Briar-CatHei** [stefankueng/BowPad#313]
In Windows 7, the close icon in tabs couldn't be rendered correctly, it displayed as a block.
![bowpad_win7](https://user-images.githubusercontent.com/82100581/214257051-e207b93a-31f4-41f7-b7b5-a8e875d58d50.png)

And in Windows 10 & 11, the number in combo boxes were covered in white color in the dark theme unless I moved the mouse consor to them.
![bowpad_win10](https://user-images.githubusercontent.com/82100581/214260041-01a6a843-2017-4054-b305-0e9b3c45ea70.png)
![bowpad_win11](https://user-images.githubusercontent.com/82100581/214257063-a3eb25ca-be4d-4861-9a28-dec6e8352abc.png)

**Comment by stefankueng** [comment]
the problem with the combo boxes is not really fixable. That's a bug in the windows ribbon framework - well maybe not really a bug because the dark mode isn't officially documented....
