### ISSUE TITLE
Horizontal scroll direction reversed if using touchpad with vertical scroll direction set to up if moving up in windows settings 

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#314]
I.e. if setting devices -> touchpad -> scroll and zoom -> scrolling direction to downwards motion scrolls down the horizontal scrolling direction in bowpad is reversed (i.e. scrolling left scrolls right and scrolling right scrolls left).

I tested in microsoft edge as well where this doesn't happen.

Bowpad version: 2.8.7.2960 (64-bit)

**Comment by stefankueng** [comment]
that's the correct behavior.
I've also tested with ms edge and chrome, and it happens there as well.
Check edge again, I think you missed something there.

**Comment by Wallby** [comment]
> that's the correct behavior. I've also tested with ms edge and chrome, and it happens there as well. Check edge again, I think you missed something there.

I checked microsoft edge, notepad, and explorer and all three horizontally do exactly the opposite as bowpad.
With scrolling direction set to "downwards scrolls up" scrolling left scrolls right on my machine but in bowpad scrolling left scrolls left.
With scrolling direction set to "downwards scrolls down" scrolling left scrolls left on my machine but in bowpad scrolling left scrolls right.

In any case perhaps there could be a feature in bowpad to allow inverting the horizontal scrolling direction.
