### ISSUE TITLE
Dragging a tab from one bowpad window to another bowpad window causes "Document removed" popup

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#324]
BowPad version: 2.8.7.2960 (64-bit)

Example..

![image](https://user-images.githubusercontent.com/13614975/234970857-a7a3629e-06c7-47ab-812e-1cc512bbefa6.png)

To reproduce..
1. open two bowpad windows
2. drag a tab from one window to the other window

**Comment by stefankueng** [comment]
I can not reproduce this. Do you have more information on your setup, what kind of files you move, what paths those files have, ...

**Comment by Wallby** [comment]
Tried both on C: drive and D: drive and happens on both, thus don't think path matters. There's no spaces or weird characters in the paths.

**Comment by Wallby** [comment]
Could the "load last session on start" option being enabled have any impact? Otherwise I don't know. I've tried restarting my computer as well and it still happens.

**Comment by stefankueng** [comment]
I have that option enabled as well. But that option is only enabled for the first BP window that's opened. Further instances of BP have that option disabled.
Dragging from either BP instance didn't show this error.

One thought though: are your two BP instances running under different accounts or privileges (e.g. one with normal and one with elevated privileges?)

**Comment by Wallby** [comment]
> One thought though: are your two BP instances running under different accounts or privileges (e.g. one with normal and one with elevated privileges?)

Not on purpose. The window with the "load last session on start" option enabled has a bunch of files open and from different folders as well. I have BowPad installed to my D: drive.

**Comment by Wallby** [comment]
Here is a video..

https://github.com/stefankueng/BowPad/assets/13614975/b242bb8f-03e8-4068-9b1a-f449d224c8dc

**Comment by Wallby** [comment]
Tested with 2.8.9 and it seems to have returned..

https://github.com/stefankueng/BowPad/assets/13614975/d985d2d4-9d39-411f-8979-94e51c726f7c

**Comment by Wallby** [comment]
> Tested with 2.8.9 and it seems to have returned..

Note.. dragging a tab out of a window to create a new window seems to work fine always. Dragging any tab to an already existing window causes this issue for me every time.

**Comment by Wallby** [comment]
I think I found the cause.. a comparison fails in `CDocumentManager::GetIdForPath` because `m_documents` contains `L"C:\\Users\\Maarten-Laptop\\AppData\\Local\\Temp\\skt29B6.tmp"` in ``m_path`), but `path`, which is ultimately generated in TempFile.cpp by `GetTempPath` contains `L"C:\\Users\\MAARTE~1\\AppData\\Local\\Temp\\skt29B6.tmp"`. This results in `CDocumentManager::GetIdForPath` returning -1 which then causes an assert in `CDocumentManager::GetModDocumentFromID`.

It seems that `OpenFile` succeeds because that uses `CPathUtils::GetLongPathname` and then supplies to result to `m_docManager.GetIdForPath`. Adding `CPathUtils::GetLongPathname` in `OpenFileAs` seems to be all that was required. Shall I submit a pull request? It's only two lines that are effected (though I don't mind getting to be mentioned as a contributor).
