### ISSUE TITLE
Not all search result are shown when find files. 

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#325]
1. input search string, folder string and files (*.cpp) in find dialog. 
2. click find files
3. Show result in list. 

I expect search result is same as "Find All in Folder", but I got this:
![image](https://user-images.githubusercontent.com/28701482/235057716-5452edd6-ed56-44d1-ad2e-3a5d5e0814b4.png)

**Comment by stefankueng** [comment]
FYI: The "Find Files" feature only searches for the files, not the search text you entered. It only lists the files that match the e.g. `*.cpp;*.txt` mask in the "`Folders to search`" path.
But the results list header titles in this case are of course wrong.
