### ISSUE TITLE
Column select doesn't work everywhere on wrapped line

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#326]
To reproduce..
1. put the cursor at the following position..
![image](https://user-images.githubusercontent.com/13614975/235296805-b756b70a-b637-4282-b766-560ab1418459.png)
2. hold alt + shift and press the up arrow
3. what happens is the following..
![image](https://user-images.githubusercontent.com/13614975/235297104-cf642fba-6b18-4296-840b-5c35ef43db58.png)

What I would expect to happen..
![image](https://user-images.githubusercontent.com/13614975/235297074-53caaff8-3799-474b-b390-775caf92a63c.png)

BowPad version: 2.8.7.2960 (64-bit)

**Comment by stefankueng** [comment]
you have to press the up arrow key twice in your case to get the desired effect. The first time the cursor does not show because that line is the same one as where the cursor already is.
Also, this is really a problem of the Scintilla control we use.

**Comment by Wallby** [comment]
> you have to press the up arrow key twice in your case to get the desired effect. The first time the cursor does not show because that line is the same one as where the cursor already is. Also, this is really a problem of the Scintilla control we use.

What I meant doesn't work.

**Example 1**
Starting at the non wrapped part of the first line..
![image](https://github.com/stefankueng/BowPad/assets/13614975/7ad06790-73c1-4666-be29-278e91b96d06)
.. then holding alt and pressing down twice results in..
![image](https://github.com/stefankueng/BowPad/assets/13614975/1351af71-8d3d-48bd-85a0-eabe8e5ad560)
Multiline select works here, but I would expect pressing down would be required only once here.

**Example 2**
Starting at the wrapped part of the first line..
![image](https://github.com/stefankueng/BowPad/assets/13614975/17012aea-d4ef-4331-bde6-8e3ccfc900b4)
.. then holding alt and pressing down once results in..
![image](https://github.com/stefankueng/BowPad/assets/13614975/b448e0dd-505e-4295-bea4-3349bf66a6a6)
Multiline select on the wrapped part of the line is impossible, what I would expect to happen here is..
![image](https://github.com/stefankueng/BowPad/assets/13614975/3a3b852f-40f1-4ece-868f-0e7aff781295)

**Comment by Wallby** [comment]
Perhaps this could work like this..
```
abcdefghijkl|mnopqrstuvwxyz0123456789abcde <
fghijklmnopqrstuvwxyz0123456789
abcdefghijklmnopqrstuvwxyz0123456789
```
.. and then pressing down with alt+shift held would result in..
```
abcdefghijkl|mnopqrstuvwxyz0123456789abcde <
fghijklmnopqrstuvwxyz0123456789
abcdefghijkl|mnopqrstuvwxyz0123456789
```
.. and..
```
abcdefghijklmnopqrstuvwxyz0123456789abcde <
fghijklmnop|qrstuvwxyz0123456789
abcdefghijklmnopqrstuvwxyz0123456789
```
.. and then pressing down with alt+shift held would result in..
```
abcdefghijklmnopqrstuvwxyz0123456789abcde <
fghijklmnop|qrstuvwxyz0123456789
abcdefghijklmnopqrstuvwxyz0123456789     
           |
```
I.e. consistently with how it would work if there wasn't any linewrapping.. there's temporarily whitespace added to a line that has less characters than the selected column and if any characters are actually modified the whitespace is actually added.
