### ISSUE TITLE
unreliable web link pop-up

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#334]
greetings kind regards please see attached GIF demonstrate unreliable web link pop-up . text file is attached . 
[spend spend spend.txt](https://github.com/stefankueng/BowPad/files/11645883/spend.spend.spend.txt)

![unreliable link pop-up](https://github.com/stefankueng/BowPad/assets/48535920/d82e6789-b557-47c5-b7c3-636bc7fe72b3)
![image](https://github.com/stefankueng/BowPad/assets/48535920/733e6856-7a85-42c9-84c6-a1ba4f1f3b17)

**Comment by stefankueng** [comment]
the 'www.cnn.com' url is not detected because the http/https is missing.
the url at the bottom to remarkable.com works fine for me.
