### ISSUE TITLE
Confusing Vertical Line and Shading in Spelling Corrections List

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#338]
greetings kind regards thank you for providing BP attached please find PNG and please observe vertical line and shading in spelling corrections list purpose of which i do not understand and perhaps may be a bug . thank you kindly
![image](https://github.com/stefankueng/BowPad/assets/48535920/194073a7-8e80-43ad-80fe-f7b3bb438d04)

**Comment by stefankueng** [comment]
What version is your UIRibbon.dll? Located in C:\Windows\System32.

**Comment by PaltryProgrammer** [comment]
![image](https://github.com/stefankueng/BowPad/assets/48535920/1525ef3d-d69f-4193-836c-d5b896f71ecf)

**Comment by stefankueng** [comment]
that's strange.
Does the menu for e.g. the Lexers also not show a checkmark for the current lexer?

**Comment by PaltryProgrammer** [comment]
i never utilize the Lexer menu . a GIF of it is attached . i do not know if it answers your question .
![Lexer](https://github.com/stefankueng/BowPad/assets/48535920/93904aeb-cb50-4cb4-b8a2-fea4507243e0)
