### ISSUE TITLE
Backup or read sessions using relative path

### ISSUE THREAD

**Issue by coo11** [stefankueng/BowPad#340]
I am using portable version of Bowpad and sometimes I use it as a sticky note.
Every time I move the program directory, all sessions disappeared.
In that case, data in `backup` directory was overwritten after I entered something new.
Could you make Bowpad save the session with a relative path, or automatically read and open the text in the `backup` directory?

**Comment by stefankueng** [comment]
the backup dir is always in the same dir as the bowpad.exe (in case of the portable version).
Can you provide a detailed situation where it doesn't work? Please provide all paths.

**Comment by coo11** [comment]
- Copy Bowpad dir to another folder
    The bowpad.exe in the new directory runs and shows the session but the bowpad.exe in the old directory not.
- Move Bowpad dir to another folder
    The bowpad.exe in the new directory runs and shows nothing.

> Move `BowPad` from `E:\Programs\Portable` to `E:\Programs`
![capture](https://github.com/stefankueng/BowPad/assets/22176261/e2685606-5d1f-4a77-a656-358f34f9c295)

**Comment by coo11** [comment]
Sorry, I may not have made it clear what I want to feedback. What I mean is that if I run Bowpad with the following options turned on, and then enter some text in a new tab - It just saved by Bowpad in the backup directory, and not specified to be saved anywhere else. Then move the Bowpad folder to another directory and run Bowpad, the content will not be shown, although it is still in the backup folder.
![2023-08-06_213654](https://github.com/stefankueng/BowPad/assets/22176261/b1fe70d6-9119-4f83-ad81-6a9f5e11dcdb)

It's not a big deal, until one time I inadvertently typed new content into a blank tab after moved the Bowpad directory, only to realize that the content automantically saved in the backup folder before was overwritten.

![2023-08-06_222020](https://github.com/stefankueng/BowPad/assets/22176261/346608bc-7263-45f7-b08e-ba2afe68790c)
Maybe it would be better to change the autosave file location to a relative path?
