### ISSUE TITLE
Odd Occurrence re/ Font

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#342]
please see attached GIF demonstrate change in font upon merely entering colon character ,
![Odd Occurence](https://github.com/stefankueng/BowPad/assets/48535920/20313fe1-794a-402a-b130-7ddbe57b7d92)

**Comment by stefankueng** [comment]
That's expected: you have the 'ini'-file lexer active. So as soon as you enter a colon, that part is treated as a key and colored blue with a bold font.

**Comment by PaltryProgrammer** [comment]
thank you kindly my apologies to have troubled your kind self w/ my ignorance .
