### ISSUE TITLE
slow samba open

### ISSUE THREAD

**Issue by gitthangbaby** [stefankueng/BowPad#343]
Opening short files from samba (\\domain) takes 10sec during which it's frozen.
Opening in other editors* is instant.
Opening the same files from samba labelled (X: drive = \\domain) is instant.
*Opening in Kate is 1min. Interestingly, these are 2 alone cases. Kate also fast via mapped drive X:. When Kate is frozen, BowPad freezes too.

I wonder what file opening, locking procedure is different from other editors.

**Comment by stefankueng** [comment]
can't reproduce this with my samba server.

**Comment by gitthangbaby** [comment]
Could be Qnap Samba or DNS issue as well, if more than 1 app has this delay. Compared 10 apps. Hope someone else can also report this.
