### ISSUE TITLE
Lookbehind assertions are not supported

### ISSUE THREAD

**Issue by maszhaowei** [stefankueng/BowPad#344]
In regex mode of search dialogue, lookhehind assertions will display message "regexp expression is invalid". But lookahead assertions are valid.
Search string: ^-.+(?<!separator)$
BowPad version: 2.8.9
OS: Windows 10

**Comment by stefankueng** [comment]
BP uses the c++ regex engine with the ECMAScript syntax (ECMA-262), which does not support lookbehind.
Sorry.
