### ISSUE TITLE
How to set Directory in File Tree w/o its' Parents ?

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#346]
greetings king regards
may i please inquire how to set the directory in the File Tree w/o its' parent directories . exempli gratia in the attached PNG i wish to make the directory "applications" as the top most directory w/ its' parents not displayed ,
thank you kindly
![image](https://github.com/stefankueng/BowPad/assets/48535920/be64e10d-7c79-4ba0-ad42-aa733ef88b70)

**Comment by stefankueng** [comment]
Sorry, but I'm not implementing this.
The file tree is 'global' for all opened tabs if they're in the same root. Only if the root changes, then the file tree also changes.

**Comment by PaltryProgrammer** [comment]
greetings kind regards . i apologize for troubling your kind self w/ this stupid request .
