### ISSUE TITLE
Bowpad syntax highlighting breaks if specifying language identifier to a fenced codeblock

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#354]
![image](https://github.com/stefankueng/BowPad/assets/13614975/deb151d9-1ad9-4aef-b7e9-0fa2c9fd70f5)

The line ` ``` C ` is not recognised it seems (doesn't turn green) and every line after looks incorrect.

BowPad version 2.8.9.3017 (64-bit)

**Comment by Wallby** [comment]
Seems like ` ```C ` is recognised. Github fenced code blocks only show this version without any space<sup>1</sup>, but both versions work on github.com. According to wikipedia the origin of fenced code blocks is PHP Markdown Extra, which does show the version with a space<sup>2</sup>.

I expect this should be reported either here..
https://sourceforge.net/p/scintilla/bugs/milestone/Bug/
.. or here..
https://github.com/ScintillaOrg/lexilla/issues
.. ?

1 https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
2 https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks

**Comment by stefankueng** [comment]
please report it here: https://github.com/ScintillaOrg/lexilla/issues
