### ISSUE TITLE
Feature Request : Tab Ordering Options

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#355]
greetings kind regards
this is to request feature id est tab ordering options in addition to currently utilized alphabetic file name to be specific [0] last access date/time [2] creation date/time . 
thank you kindly

**Comment by stefankueng** [comment]
tabs are not ordered, they appear in the 'order' in which you open the files.

**Comment by PaltryProgrammer** [comment]
greetings kind regards
my apologies . i should have stated i was referring to ordering of the names in the Tabs drop down list .
thank you kindly

**Comment by stefankueng** [comment]
And how would that look UI wise?

- a setting somewhere means switching the sorting can't be done fast
- separate buttons is ugly, and would use too much space
- other?

**Comment by PaltryProgrammer** [comment]
greetings & kind regards

perhaps a means is as follows : 
[0th user action] mouse **hovers** over "Tabs" menu button
[0th software response] a drop down list of buttons appears w/ option buttons :
[0th option] creation order and reverse (so 2 buttons)
[1st option] alphabetical and reverse (so 2 buttons)
[2nd option] last use order and reverse (so 2 buttons)
[1st user action] click on a button voila bingo presto ordered list is presented

further i have never understood why it is necessary to click upon a menu button whose purpose is to drop down a list as it seems to me it is sufficient to merely hover over said menu button .

further yet as the "Tabs" menu button is rather large perhaps it can be in actuality 2 buttons perhaps an upper and a lower each ½ current size . exempli gratia upper button presents list in order of last prior choosing or of course default order if no such last prior choice . lower button presents above discussed drop down list of order options again each upon hover w/o need to click upon .

thank you for your kind consideration

**Comment by stefankueng** [comment]
why it's necessary to click: a touch screen doesn't know that you're hovering your finger over it.
Also: if hovering is enough, there would be many dropdowns expanding all the time just by moving the mouse from A to B (or you would actually have to move around all such hover buttons). That would be the most horrible UI I can think of.

**Comment by stefankueng** [comment]
dup of #371
