### ISSUE TITLE
Minor UI Change Request

### ISSUE THREAD

**Issue by PaltryProgrammer** [stefankueng/BowPad#357]
greetings kind regards
thank you for providing BowPad , i utilize it constantly , this is a minor UI change request . to be specific the "Tabs" label on the Main / Tabs drop down list i often find momentarily confusing for several reasons to be specific [0] a "tab" is also a spacing character [1] a "tab" is an item utilized for file name placement . [2] simply stating "Tabs" is not a direct \ clear statement of the intended meaning . of course upon drop down the intended meaning becomes clear , to prevent momentary confusion i request if space allows to rename to term(s) which more clearly presents intended meaning exempli gratia "Open Files List" .
thank you kindly

**Comment by stefankueng** [comment]
"Open Files List" is too long, there's not enough space under that button for the full text.
"Open Tabs" perhaps?

**Comment by PaltryProgrammer** [comment]
greetings kind regards i apologize for troubling your kind self w/ this needless request .
