### ISSUE TITLE
get current file path and filename in plugin

### ISSUE THREAD

**Issue by ShadyShenAli** [stefankueng/BowPad#358]
How can I get the full path of the current file / docID?

**Comment by stefankueng** [comment]
right-click on the tab, in the context menu there's an entry "Copy Path".

**Comment by stefankueng** [comment]
oh, just noticed: you need this info in a plugin.
Sorry, currently there's no way to get that path. May I ask what exactly do you need it for? Always remember that not all documents/tabs have a path.

**Comment by ShadyShenAli** [comment]
I want to use a commandline tool to parse the file and load the file again.
Therefore I will need the full path in my plugin.
