### ISSUE TITLE
Fixed width fonts don't line up

### ISSUE THREAD

**Issue by SillyWilly80** [stefankueng/BowPad#36]
The latest versions of BowPad have an issue displaying fixed width fonts (Courier New).
Lines with lots of spaces don't line up properly with lines having lots of characters.

**Comment by stefankueng** [comment]
I can not reproduce this.
Also, there weren't any changes that would suddenly show such a behavior.

**Comment by SillyWilly80** [comment]
I have attached a screen shot of BowPad and an example very short file with just 3 lines.
The file lines up correctly in NotePad, but not in BowPad. The 3 lines in the .TXT file are copied from the central comments in the file shown in the screen shot. As a .TXT file, it looks OK. Change the extension to .FOR and it won't line up.

![BowPad_Image](https://user-images.githubusercontent.com/53828494/62890061-a52fa400-bd10-11e9-83f4-602583ccf87c.jpg)

[BowPad_Example.TXT](https://github.com/stefankueng/BowPad/files/3493889/BowPad_Example.TXT)

**Comment by stefankueng** [comment]
That's the lexer, or better the styling of the lexer: some words are shown in bold, and those then lead to those slight offsets.
You can change the styling yourself if you like.

**Comment by SillyWilly80** [comment]
Thanks. Apparently, you have to select the same font and font size on the "Other" tab and on the "Configure Styles" screen. Changing the font size on the "Other" screen does not reflect back to the style. Now that I have them both set the same, all is OK. Thanks again.
