### ISSUE TITLE
使用 Configure Styles 时 BowPad 崩溃退出

### ISSUE THREAD

**Issue by MagicMaker** [stefankueng/BowPad#362]
我在  Configure Styles  里设置字体为  Consolas 、14  然后点击 OK 按钮，BowPad 崩溃退出了，可以重现这个问题。

**Comment by stefankueng** [comment]
translation:
I set the font to Consolas in Configure Styles and 14 and then hit the OK button, BowPad crashed and exited, I can reproduce the problem.

**Comment by stefankueng** [comment]
Sorry, can't reproduce the crash here.
