### ISSUE TITLE
Load last session restores a previously closed window

### ISSUE THREAD

**Issue by Wallby** [stefankueng/BowPad#365]
Hello,

Sorry if I write a lot of issues. I use bowpad as my main editor hence I care about issues being resolved.

To reproduce..

1. load a last session
2. open a new window (either by right clicking on taskbar icon and then selecting "bowpad", or by dragging a tab out to create a new window)
3. open a file in that new window such that it does not contain only an empty file
4. close the old window
5. close the new window
6. open bowpad and notice that the old window is loaded not the new window, which I would expect as that is the last session

Bowpad version.. 2.8.9.3017 (64-bit)

**Comment by stefankueng** [comment]
Yes, that's actually by design.
The session that's stored is always the one from the first window that was started/created. Because that's the window where the session was restored.
