### ISSUE TITLE
tab size and monospace font problems

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/BowPad#384]
from #376:
Some monospaced fonts seem to have an issue with spaces (and it seems line height too). Spaces don't seem to count as a single font space, but less. Example below...

TAB size doesn't seem to work properly in some cases. I use a filetype .mnx to create README files for software I use, with things like how to extract and install portable software, how to update, the author URL and information, etc.. But the tab size is always 8 when I open those files, even tho in the ribbon indicates a size of 4.. This is fixed by setting the size to 3 and then back to 4, but this has to be done every time a file is open.

Font: Consolas | Tab size: 4
![2024-06-08 08 56 07](https://github.com/stefankueng/BowPad/assets/24944618/81f8e6d3-f045-49fa-acc1-ac8355afc8c9)

Font: Consolas | Tab size: 4 (after setting the size to 3 and then back to 4)
![2024-06-08 08 56 26](https://github.com/stefankueng/BowPad/assets/24944618/e41d19ac-fb4c-4e27-ac51-e4656c063de7)

Font: Consolas NF3 (This is the same "Consolas" font patched with Nerd Fonts Patcher)
![2024-06-08 08 56 44](https://github.com/stefankueng/BowPad/assets/24944618/ddff2a3b-2652-44bb-9b70-e450c1dd0eb4)

Font: Consolas NF3 (This is how it looks in EditPlus)
![2024-06-08 08 57 08](https://github.com/stefankueng/BowPad/assets/24944618/e7d53826-a5fb-4648-b1f7-2055951d037d)

Font: Consolas NF3 (This is how it looks in Visual Studio Code)
![2024-06-08 09 02 20](https://github.com/stefankueng/BowPad/assets/24944618/cb6c93bf-8b89-4f45-8111-dd7537569c2c)

**Comment by mdnava** [comment]
I attach the Windows font Consolas and the patched font Consolas NF3 in case they're of use..

[Consolas.zip](https://github.com/user-attachments/files/16040957/Consolas.zip)

**Comment by mdnava** [comment]
> is there an .editorconfig file that sets a tab size beneath or up the file tree?

@stefankueng I checked.. But no .editorconfig file in the BowPad up or down the directory tree.

Just in case, I tried copying the program folder to the root drive:

![2024-08-02 10 52 12](https://github.com/user-attachments/assets/196adf64-d73a-4d99-a4ab-4835cf311d3e)

Best regards!

**Comment by stefankueng** [comment]
could you attach the mnx file (the part visible in the screenshot is enough in case there's info in there you don't want to share). And then which lexer do you use for those files?

**Comment by mdnava** [comment]
@stefankueng I used no lexer in BowPad for that file.

But I just tried to use the following lexers: txt, php, json, c sharp..

Same reasult.

**Comment by stefankueng** [comment]
thanks!
I can now reproduce the problem. Working on it...

**Comment by stefankueng** [comment]
found a similar issue here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10608

basically, if you add
[View]
d2d=0

to the config file and restart BP, the issue won't show. But then you don't get the ligatures.

But I think I found the problem: the font is not properly monospaced!
Using the "consolas NP3" font you attached above and then calling the [GetClusterMetrics ](https://learn.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritetextlayout-getclustermetrics) API, the result shows different widths for some chars (not just space but also ,. and others)

So I'm closing this issue since it's really the font that's not quite correct and a workaround exists.

**Comment by mdnava** [comment]
@stefankueng ok, I tried patching again the font, so it seems to work now, with some minor discrepancies:

![2024-08-02 16 06 13](https://github.com/user-attachments/assets/29ae101e-69a5-4b69-8b12-dbc61f11c9c5)

I used the same exact command to patch the font. The only difference is that the fontpatcher script version
is currently at v3.2.1 but before it was v3.0~ when I originally patched the font.

However, I have to make the point that even if the patching was flawed the font worked fine in other editors.
I mention this just in case, and to keep in mind in case of any future issues.

> basically, if you add [View] d2d=0
> 
> to the config file and restart BP, the issue won't show. But then you don't get the ligatures.

I did tried this workaround first but didn't work for me, nothing happened.
I did noticed that the "d2d=0" setting dissapeared from the "settings" file every time after I closed the editor.

Best regards..

**Comment by stefankueng** [comment]
first: other editors where the font works most likely don't use DirectWrite and don't show ligatures. They use the 'old' APIs to draw text. DirectWrite is the API set that supports ligatures and other new features of fonts which the old APIs don't.

second: to disable d2d, you have to edit the config file with another editor while BP is not running.
