### ISSUE TITLE
Bug: BowPad icon disappeared on taskbar

### ISSUE THREAD

**Issue by peter8777555** [stefankueng/BowPad#389]
OS: Windows 11
BowPad V2.9.1 X64
Size : 1 GB
Lines: 18,910,241

OK:
Menu --> Open --> TXT File

NG:
Drag TXT File from Explorer.exe into BowPad.

**Comment by stefankueng** [comment]
screenshot please

**Comment by peter8777555** [comment]
See picture.

![z1](https://github.com/user-attachments/assets/f45862af-4899-4fb8-94fd-80a2eab2897f)

**Comment by peter8777555** [comment]
By the way,

Size : 1 GB
Lines: 18,910,241

BowPad freeze until load finish.

Suggestion:
BowPad shows loading lines or loadind percent.

**Comment by stefankueng** [comment]
screenshot shows icon. So what exactly is wrong??

**Comment by peter8777555** [comment]
See screen recording by Screen2EXE.
https://www.screen-record.com/screen2exe.htm

[Demo.zip](https://github.com/user-attachments/files/16636480/Demo.zip)

**Comment by stefankueng** [comment]
seriously? You expect me to run an exe?
Please use a tool that creates a video/gif and not an exe.

**Comment by peter8777555** [comment]
See  MP4.

[Demo.zip](https://github.com/user-attachments/files/16636779/Demo.zip)
