### ISSUE TITLE
Bug: Wrap Lines setting keeps turning off

### ISSUE THREAD

**Issue by SamKr** [stefankueng/BowPad#392]
Since the last update, the _wrap lines_ setting keeps turning itself off. I read in the release notes that it's now type-based, but even if I set it on a txt file, the next time I open the same file in BowPad _wrap lines_ is turned off again. Besides setting it per filetype, it'd be great if it could have a global setting as well (as I prefer it always on for my BowPad usecases).

Thanks for this great tool :)

**Comment by stefankueng** [comment]
I'll fix it when I get to it.

**Comment by stefankueng** [comment]
currently, the wrap mode is only saved if the feature "load session on start" is active. Otherwise the state of files is not saved and loaded.

**Comment by SamKr** [comment]
Thanks @stefankueng. BowPad is my daily driver note taking, config editing and my external memory. Its combination of options and features is perfect. Your work is very much appreciated :)
