### ISSUE TITLE
allow to mark selected text througout the file in different colors

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/BowPad#395]
currently, the selected text is marked. But that's only one text. Should be possible to mark another text and assign a color to it to mark it throughout the file.

**Comment by tvb377** [comment]
Hi Stefan,

so the original functionality  is lost, i.e. occurrences of selected text are marked green as long as the text is selected?
Or is there a way to reenable that?
I was using this quite frequently to quickly find text in a block.
Thanks
Titus
