### ISSUE TITLE
wrap lines setting cannot take effect when open a new BowPad window

### ISSUE THREAD

**Issue by Yanstory** [stefankueng/BowPad#396]
the `setting` file shows `View.wrapmode=1` but the namesake setting in new window always `off (false)`.

By click the button the setting value can be saved in file correctly. It just cannot work well when open a new BowPad window.

**Comment by stefankueng** [comment]
dupe of #392

**Comment by Yanstory** [comment]
The problem still exist.
![16AC17600C905D41B2D505DA868A6EBC](https://github.com/user-attachments/assets/48d6dfde-e808-4fdd-a1c7-62eeaccd113e)
