### ISSUE TITLE
Edit selection no longer works

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#397]
In the recent published version, Edit Selection command does nothing when clicked.
Please check to see what's wrong.

**Comment by stefankueng** [comment]
what "edit selection" command?

**Comment by wmjordan** [comment]
![image](https://github.com/user-attachments/assets/9ed1aa03-238a-4822-8d34-99d9d96c306c)

Please see the above screenshot.
I selected "o" and execute that "Edit Selection" command in the drop-down.
Previous version will select all "o" and insert carets there. This version nothing happens.

**Comment by wmjordan** [comment]
Fixed in recent commit.
