### ISSUE TITLE
Default file extension

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#40]
Currently there's no default extension while we save a newly created file. We have to explicitly specify it when saving the file.

Is it possible to assign a default extension according to the selected syntax language?
For instance, by default the new file uses Text as the syntax language, thus a ".txt" extension is used as default file extension while saving the new file; if we use Markdown as the syntax language and save the newly created file, a  ".md" extension is offered as the default file extension.

**Comment by wmjordan** [comment]
While I was composing plugin files, I tried to create a desc file and named it as _pluginname.desc_ in the Save As dialog, BowPad saved it as _pluginname.desc.txt_.

It seems that there's no need to append the extension if the name already has one.

**Comment by stefankueng** [comment]
I can not reproduce that. If I specify "pluginname.desc" as the filename to save as, there's no *.txt appended to it, it's saved as requested.

**Comment by wmjordan** [comment]
You can't save an existing file as a new name.

Reproduction:
1. New file,
2. Save the file as "abc.desc",
3. The file becomes "abc.desc.txt".

**Comment by stefankueng** [comment]
I tried that. And when I do that the file is properly saved as "abc.desc", not "abc.desc.txt".

**Comment by wmjordan** [comment]
That's weird.
Are you sure that your Windows has not hidden known file extensions? -- Is the _.txt_ extension hidden in your system?

**Comment by stefankueng** [comment]
no, I've always have extensions shown, as well as hidden item in explorer.

**Comment by wmjordan** [comment]
I debugged the release build and found that the .txt extension was automatically appended to the path after the FileSaveDialog was OKed.

In the FileSaveDialog, the file type was "Text File (*.txt ....)".
When we select that file type, the FileSaveDialog automatically appends the extension.
It seems that it is the behavior of the common dialog.
If we are to save the file to "abc.desc", we have to select "All file (*.*)" before closing the dialog.

````C
psiResult->GetDisplayName(SIGDN_FILESYSPATH, &pszPath) // here pszPath becomes ....abc.desc.txt
````

**Comment by stefankueng** [comment]
so we have a problem: should the default extension be added automatically or not?

**Comment by wmjordan** [comment]
I find that it is how the common dialog works. NotePad, MS Word and all other applications which use FileSaveDialog work like that.
Maybe we should just leave it alone as it is today and eventually close this issue forever.
