### ISSUE TITLE
Find All no longer works

### ISSUE THREAD

**Issue by gmcode** [stefankueng/BowPad#44]
In Bowpad 2.4.5, if you open a document and do a Find All action, i.e. do Ctrl-F, then select the Find All option from the Find split button so that it finds a few items on different lines; and then double click one of the lines so that the editor should do go to line number of the item selected, you should find that bowpad goes to the wrong line number.

If you comment out the OpenFile statement in line 1148 of CmdFindReplace.cpp, then it does seem to work, but that is not a fix, just observation to assist someone to find the fix. It suggests that OpenFile does something to break things so that goto line doesn't work, when opening a document that is already the current document.

It's also worth noting that ActivateTab in TabBar.cpp, the call to TabCtrl_SetCurSel's return value isn't checked. It returns -1 in some instances to indicate the current tab did not change. Putting an assertion on this value reveals that there are instances when this happens. It may be worth investigating if bowpad should do something different when this happens in some cases either inside or outside the function, to avoid this situation happening and if a selchange event should be sent in all cases even if the current tab hasn't changed. 

Note that putting in ActiveTab to do nothing if the tab to activate is already the current tab isn't sufficient to fix the problem with find not working. Just something else to note.

Possibly related to this problem (and possibly not), note that bowpad doesn't handle when files change or are deleted on disk when bowpad has them loaded and it's running. It routinely locks up and in many cases crashes. I don't have time to reproduce a test case for this problem, but it's not that hard to reproduce.

Good luck fixing these problem.
Thanks

**Comment by gmcode** [comment]
Hey, a fix for this problem is to add an UpdateWindow() call as shown below after open file:
    if (OpenFile(path.c_str(), openFlags) < 0)
        return;
    UpdateWindow(GetScintillaWnd());       // <-------
    ScintillaCall(SCI_GOTOLINE, item.line);
There may be other places where a fix like this is needed in bowpad, but I haven't looked into that.

I'm not sure at this time what the fix is regarding the other problem of bowpad crashing/locking up when files are deleted or changed outside of bowpad.

**Comment by stefankueng** [comment]
I can not reproduce this, neither on my two home machines nor on 5 different computers in the office.
Since you said that an `UpdateWindow()` call fixes this for you I suspect that the problem is somehow with your display driver which is not updating the view correctly.

**Comment by gmcode** [comment]
This issue has nothing to do with a bug or problem in the video driver. I think that's a stretch to guess that far.
The issue is to do with the wrapping mode I think. In your testing set wrapping mode on and you should see the problem, if wrap mode is off, you'll likely not see the problem. See this also:
https://sourceforge.net/p/scintilla/bugs/1387/
My UpdateWindow fix forces wrapping to be finish.

**Comment by wmjordan** [comment]
@gmcode Yes, I met with the same issue.
If we turn off the text-wrapping, the Find All function works as expected.

**Comment by gmcode** [comment]
@wmjordan, I suspected this would be the case for you, thanks for confirming this.

If you can't wait for my fix to be accepted (assuming it happens) and if you haven't done this already  you can apply it yourself by download the code and going to line 1156 of C:\BowPad\src\Commands\CmdFindReplace.cpp and right after this code:
    if (OpenFile(path.c_str(), openFlags)<0)
        return;
add this one additional line:
    UpdateWindow(GetScintillaWnd());
and then build the code and it will fix the problem you are experiencing.

Building isn't hard, but getting the build tools might not be worth it if you don't already have them. If you do create a custom build, be aware that any custom bowpad.exe you build will likely have a wrong version number in it, so you should decline and turn off in-app updates to bowpad when using your custom build. 

And if you decide to copy your custom built bowpad.exe over the official bowpad.exe in the program files\bowpad folder, perhaps keep a backup. Resource changes between versions might mean things crashes if you get something there wrong, but it will likely will work for you.

If you go this route, once an official fixed build is released,download the official manually and install it with the setup program, rather than letting your custom bowpad.exe update itself from within the editor. Once the official release is installed you are running that one can, you can re-enable in app updates if you turned them off.  Restoring your backup and updating from within bowpad might be another option.

If you get stuck I'm happy to try to help, but the safest and easiest option would be if my fix was applied by the project maintainer and released.

Hope this helps!

**Comment by wmjordan** [comment]
@gmcode Thank you very much for your kind help and information. Unfortunately, as you have mentioned, getting the build tools is too much for me.
@songbaoming Do you have time to look at this issue and adopt @gmcode's fix?

**Comment by songbaoming** [comment]
I reproduce this issue, which is definitely caused by wrap lines. But it involves a lot, so i need to find a better solution to fix it.

**Comment by gmcode** [comment]
@songbaoming What's wrong with the one line UpdateWindow fix I posted?
It seems to be the easy and correct fix because UpdateWindow would force painting to finish so that the line numbers are correct by the time goto line is called to goto the line number.
What is conceptually wrong or problematic with my fix?
What type of fix do you think is better?

**Comment by wmjordan** [comment]
@gmcode Could you please compile an exe, zip it and post it here? I'd love to test it.

**Comment by gmcode** [comment]
Hi @wmjordan, hey I'd normally be more than happy to help, but I have only a preview version of the tools required to build bowpad and the license for those tools don't allow me to distribute built code yet, so I'm not sure I can help. Sorry.

Perhaps with the weekend being here now nearly, Stefan will have time to create a build with my fix in for you to test or perhaps they'll find time to comment on why my fix is a bad idea. It should take no more than 15 minutes to do, so there's a good chance of something happening this weekend on either of those fronts.

If there's no progress by mid week, I could perhaps install the old/current version of the tools that do allow me to distribute code to you. There's some risk it might break my current setup, so I'm a bit reluctant to do it right now, but if there's no progress by the middle of the week coming, I'll take a chance and see if I can install them and build you something to try. I'll just give the other guys a little longer to investigate or do a build for you, because it's a lot easier for them to do a build, certainly for Stefan, because he will have a machine with the release tools on already. But if there's no joy by mid week, I'll see what I can do then.

If you are super keen to try this sooner, I'm more than happy to send you some instructions and help you get setup with the tools yourself and show you how to build it. :)

**Comment by wmjordan** [comment]
Thank you @gmcode , I'd love to wait :)

**Comment by stefankueng** [comment]
@gmcode : to build BP, you'll only need Visual Studio Community Edition which is free for personal and open source projects (BP is opensource so you'll be fine).

**Comment by gmcode** [comment]
@stefankueng 
I know the Community Edition is free, because I was telling wmjordan I didn't want to install that version next to my more recent preview version of it, unless it was really necessary as I don't want to risk it affecting the preview version (which it shouldn't, but it happens sometimes) and it also chews up SSD space.

I can confirm that your fix also solves the problem on my machine.

**Comment by wmjordan** [comment]
@songbaoming 
Could you kindly take the trouble to compile and upload a beta version?

**Comment by songbaoming** [comment]
@wmjordan: Sure, and now you can download it from my fork.

**Comment by wmjordan** [comment]
@songbaoming Xiexie very much! I have downloaded the beta and it is working very well on my machines.

**Comment by wmjordan** [comment]
This bug was not perfectly fixed yet.
If we open a very long file and use the find all command to list occurrences of a phrase, sometimes double clicking an item in the result list will not scroll the document window to desired location.

For instance, an occurrence is at line 479883, and currently the first visible line is 452100, quite far from the 479883rd line. When we double click the occurrence in the list, it will scroll the document window to a location where the last line is 479881 or so, if lines above it are wrapped. We have to scroll the document downward to see the occurrence.

At this time, if we double click the occurrence in the result list again, BowPad will center the line 479883 and the occurrence will be placed on the center of the document window.
