### ISSUE TITLE
Highlight Current Line

### ISSUE THREAD

**Issue by mva1985** [stefankueng/BowPad#45]
Is there a setting so that all of the current line could be highlighted in a color vs just having the 
 box outline for the current line?

Thanks

**Comment by stefankueng** [comment]
Sorry, but there's currently no way to configure that.

**Comment by wmjordan** [comment]
I tested with a script by calling [one or two of the following message in Scintilla](https://www.scintilla.org/ScintillaDoc.html#SCI_SETCARETLINEBACK), it was possible to alter the appearance of the current line indicator in BowPad.

SCI_SETCARETLINEVISIBLE(bool show)
SCI_GETCARETLINEVISIBLE → bool
SCI_SETCARETLINEBACK(colour back)
SCI_GETCARETLINEBACK → colour
SCI_SETCARETLINEBACKALPHA(alpha alpha)
SCI_GETCARETLINEBACKALPHA → int
SCI_SETCARETLINEFRAME(int width)
SCI_GETCARETLINEFRAME → int

**Comment by wmjordan** [comment]
With [this plugin](https://github.com/stefankueng/BowPad/issues/151), it is possible to customize the current line style now.

![image](https://user-images.githubusercontent.com/12182730/115318555-8acdef00-a1b0-11eb-9075-db2466a4978a.png)
