### ISSUE TITLE
Lost icon during to Pin to taskbar

### ISSUE THREAD

**Issue by freeunion1possible** [stefankueng/BowPad#46]
Bowpad 2.4.5 running with in win10 pro, when i try to pin to taskbar, the application will lost the default icon , and show the blank icon.

**Comment by stefankueng** [comment]
Seems to be a problem with Windows: if you open the start menu and find the BowPad icon there, you can right-click on that icon and select "pin to taskbar": if you do that from the start menu the right icon is shown.

Not sure how or even if I can fix that.

**Comment by songbaoming** [comment]
The file path pointed to by the taskbar icon may be incorrect. If the path is correct, you can manually modify the icon in the properties window.
