### ISSUE TITLE
feature request: list files/tabs open

### ISSUE THREAD

**Issue by gmcode** [stefankueng/BowPad#48]
It would be nice if there was a button lists the files/tabs currently open, next to the new tab/close tab buttons on the tab bar. It probably should large enough and to the left of the  other two buttons so they aren't clicked by accident when trying to click the files/tab list button. A short cut key like Alt-W seems reasonable.

The advantage of this is the new files/tabs list button could be used and clicked on when the ribbon is hidden and without having to add it to the caption bar. It is very non-discoverable to know how to put it buttons on the caption bar to begin with and to remember to look for buttons on the caption bar. By putting it on the tab bar, the existing files/tab list button could be removed to make room for something else, perhaps file tree or some new feature.

**Comment by stefankueng** [comment]
you mean like this one?
![image](https://user-images.githubusercontent.com/665591/68844608-5bb57300-06ca-11ea-8384-d94a49657300.png)

**Comment by gmcode** [comment]
No NOT like that one. The whole post was expressly about that one and why I don't like it, even to the extent of suggesting it be removed i.e. "...the existing files/tab list button could be removed...".

Did you not read my message at all? I can make a big screen grab of the whole first post and highlight a big ring around it for you if you like, since you missed the whole thing.

**Comment by wmjordan** [comment]
I think @gmcode did mean that button.
He was suggesting moving that button to the tab bar.

I agree with him. Each time I took quite a few seconds to look for that button while I wanted to use it. Moving it to the tab bar can make that function easier to be discovered.
