### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by CharlesSeartech** [stefankueng/BowPad#5]
Hi Stefan,

Great app, thanks.

Is there a chance you can add a right click "Go to definition" for functions/variables types? I find I am using BowPad more and more and the frustration of not having a go to definition is now becoming limiting.

Regards,
Charles

**Comment by stefankueng** [comment]
BowPad is only a text editor. It doesn't parse source code for programming languages.
To do what you want, we'd have to implement a c/c++/c# (or whatever language you use) compiler to figure out where a definition of a function or variable is.
Without a compiler backend, BowPad can't even figure out what a function and/or variable is - it only knows text.
