### ISSUE TITLE
It takes very long time to page up or down

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#50]
If a document is word-wrapped and very long (tens of thousands of lines), it takes quite considerable time to page up or page down with the paging buttons.

**Comment by stefankueng** [comment]
the problem is inside the scintilla control: when pageup/pagedown on line-wrapped documents it sometimes determines line wrapping not just up to the visible parts but way beyond that. And that takes a long time.
Nothing I can do in BP though, sorry.
