### ISSUE TITLE
 Loop when saving a file with BowPad started by BowPag via the elevate privileges dialog

### ISSUE THREAD

**Issue by Louisonix** [stefankueng/BowPad#53]
Steps to reproduce: 

- Open a file which requires Administrator privileges for write access
- Change some text in the file
- Save
- Elevate dialog appears
- Click "Save elevated"
- Save the file (that works fine)
- Still, the dialog from first Bowpad Dialog ist opened... 
- Try to click any of the buttons
- an errors message box appears: "access denied"
- still, the elevate dialog is visible
- try to continue ;-)

Windows 10, build 17763.973

**Comment by stefankueng** [comment]
When I try to do that, then the elevated BP starts up and I actually have to do the changes over again and can then save them. So the bug for me is that it doesn't carry over the changes properly.
When I do save the changes from the elevated BP, I then get a dialog in the non-elevated BP telling me that the file has been modified outside BP. That dialog I can close properly.

**Comment by Louisonix** [comment]
So, you see no problem here? It's annoying here. This wasn't in the previous versions and one of the reason why I always loved Bowpad, is the auto-elavation :-) Maybe this screeshots better describes the problem: 

https://postimg.cc/nMyRKfJG

How to get out of bowpad in such an situation? I always have to use the taskmanager. 

THanks for BowPad, anyway :-) !

**Comment by stefankueng** [comment]
It's not that I don't see that what you experience is a problem. It's that I can not reproduce the problem - it works fine for me.
But I won't give up trying to reproduce this.

**Comment by Louisonix** [comment]
When I switch back to version 2.4.3.2065 it works flawlessly. 

With the newer version it seems like BowPad's unelevated process doesn't receive a"file changed" event (which results in an "do you want to reload the file?" dialog).

**Comment by stefankueng** [comment]
closing this for now. If I ever get a way to reproduce this I'll reopen it.
