### ISSUE TITLE
Would you like to have a Windows ARM64 port?

### ISSUE THREAD

**Issue by Biswa96** [stefankueng/BowPad#56]

**Comment by stefankueng** [comment]
building for ARM64 isn't a problem. But testing - don't have an ARM64 machine.

**Comment by Biswa96** [comment]
Some errors are shown in VS19:

```
BowPad\src\last\version.h(7) : Info : Run the NAnt script to get proper version info
LINK : warning LNK4217: symbol 'CoolSB_SetScrollInfo' defined in 'coolsb.lib(coolsblib.obj)' is imported by 'Scintilla.lib(ScintillaWin.obj)' in function '"private: int __cdecl ScintillaWin::CoolSB_SetScrollInfo(int,struct tagSCROLLINFO const *,int)" (?CoolSB_SetScrollInfo@ScintillaWin@@AEAAHHPEBUtagSCROLLINFO@@H@Z)'
LINK : warning LNK4217: symbol 'CoolSB_GetScrollInfo' defined in 'coolsb.lib(coolsblib.obj)' is imported by 'Scintilla.lib(ScintillaWin.obj)' in function '"private: bool __cdecl ScintillaWin::CoolSB_GetScrollInfo(int,struct tagSCROLLINFO *)" (?CoolSB_GetScrollInfo@ScintillaWin@@AEAA_NHPEAUtagSCROLLINFO@@@Z)'
```

While compiling the ARM64 version, the executable is linked with comctl32 in WinSxS instead of system32, any solution?

```
C:\Windows\WinSxs\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19569.1000_none_6e34fb0e2d4dc0f9\comctl32.dll
```

**Comment by stefankueng** [comment]
the version.h info means that your build uses the default version.h file which does not have the proper version numbers in it but "0.0.0.0".

the link warnings can be ignored and come from the custom scrollbar we use.

as for comctl32 - why should it not use the one in WinSxS?

**Comment by Biswa96** [comment]
> as for comctl32 - why should it not use the one in WinSxS?

Because that path does not exist in ARM64.

**Comment by stefankueng** [comment]
add an
```
#if defined(_M_IX86) || defined(_M_X64)
// pragma
#endif
```
around the pragma in stdafx.h

**Comment by Biswa96** [comment]
I think there is some issue in the code, diving into it....

**Comment by Biswa96** [comment]
If I execute bowpad, a msvc assert/abort window popup. Debugging may be required but I am testing it in WinPE.

**Comment by zufuliu** [comment]
Scintilla it self works well on ARM64 (Windows 10) and ARM32 (Windows 10 on ARM64, and the discontinued Windows RT) without any code changes.
See https://github.com/zufuliu/notepad2/issues/134 (see comments, SC_TECHNOLOGY_DIRECTWRITERETAIN is used as default on ARM32)
https://sourceforge.net/p/scintilla/feature-requests/1319/

**Comment by Biswa96** [comment]
Apology for late reply. I have tested BowPad ARM64 latest master branch (as of today) in Windows 10 ARM64 build 20161. It works without any issue. Thank you ❤️
