### ISSUE TITLE
Feature request: Copy/Export find results

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#59]
Is it possible to copy results from the result list of the Find dialog?
Ideally, it is more convenient if we can choose to copy the whole result list or the matched text only.

Maybe it is also possible to redirect the search result to a new document.

**Comment by wmjordan** [comment]
I noticed that there was a newly added capture regex function in the recent version of BowPad.
Actually you don't have to design such a dialog, IMHO, just add the capture expression to the Find dialog and add a checkbox to redirect the search result to new document window will do the job.

**Comment by stefankueng** [comment]
closing: you wrote a plugin for this.
