### ISSUE TITLE
Performance Issue: Searching takes too much time

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#6]
It takes BowPad very long time to search a short item within a text file which contains tens of thousands of lines, whereas in AkelPad it takes less than 1 second to complete the search.

**Comment by wmjordan** [comment]
The search does not seem to take too much time because searching all occurrences in the file actually takes less than 1 second. However, when clicking on the result and jumping to the location causes the interface to freeze.

**Comment by wmjordan** [comment]
I am afraid that this issue has not yet been completely fixed.

I made a sample file for your test.
[test.7z.zip](https://github.com/stefankueng/BowPad/files/1958397/test.7z.zip)

Open it with BowPad, and Ctrl+F to open the search dialog and search for something, such as `jaidyv`.
The first several searching and locating matched occurrences should be fast.

When I dragged the scrollbar to the middle of the file and hit the _Find_ button again, it took quite some seconds to highlight the matched occurrence. Sometimes even the next match was just a few lines below on the screen, it still took quite a few seconds to locate it.
If we _Find All_ in the file, and hit a certain item in the result list, it could be slow to locate that line too.
Please check to see what else was making things slow.

**Comment by stefankueng** [comment]
I can't reproduce this anymore. Using the latest build, the search is fast for me every time.
Even scrolling to the middle or even further down and then hitting the _Find_ button again is fast.
This of course using your test file and searching for `jaidyv`.

Also using _Find All_ and randomly clicking on the search results is fast every time.

Can you maybe find some way for me to reproduce the problem?

**Comment by wmjordan** [comment]
I made a screen recording for reproducing the problem.
[Recording.7z.zip](https://github.com/stefankueng/BowPad/files/1962449/Recording.7z.zip)

The [View] section in the settings file was (`FontName` shall not be related to the problem):
````
[View]
autosave=0
darktheme=0
FileTree=1
FileTreeWidth=370
FontName=IosevkaCC
ShowFoldingMargin=0
tabsize=8
usetabs=1
verticaledge=0
whitespace=0
wrapmode=1
````

**Comment by stefankueng** [comment]
Thanks for the recording.
But I've now tried for over an hour, but I still can't get BowPad to hang or even take longer for the _Find_ to do it's job after the first time.
I'll leave this issue open until I can reproduce the problem.

**Comment by wmjordan** [comment]
It is so weird.
I could reproduce this on more than one computers: Win10 1709 64bit, Win2008 sp1 64bit. All of them are 64bit ones.
Open the big test file, open the file dialog, select something and find, drag the scrollbar down to the middle of the document, find again will hang BowPad.

**Comment by wmjordan** [comment]
Maybe this issue is related to word wrapping.
If I turned off word-wrap, no more hangs.

**Comment by stefankueng** [comment]
Yes, with word-wrapping on, I get the hang as well.
But unfortunately, that hang has nothing to do with the search per-se but with trying to ensure that the line where the search is found is in the visible part of the window.
And that part of the code is handled by Scintilla. The slow part is the Scintilla command SCI_ENSUREVISIBLE, which has to calculate the length of every line up to the line where the search is found. In your example, that's about 160'000 lines. And that's what's slow.
Don't know how I could speed that up in BowPad.

**Comment by wmjordan** [comment]
I understood. The "Go To Line" can produce the hang too.

`SCI_ENSUREVISIBLE` was about folded text. If no text was folded, could this routine be skipped? Could you cache the folded line ranges in BowPad to skip this function as much as possible?

**Comment by stefankueng** [comment]
It's not folded text but line-wrapping.
Scintilla does some caching already, but it seems it's not enough for these situations.

**Comment by wmjordan** [comment]
I found that pressing Ctrl+End could take quite long time. Perhaps it was related to this issue as well.
