### ISSUE TITLE
Crash on 1st startup

### ISSUE THREAD

**Issue by brodders61** [stefankueng/BowPad#60]
Hi Stefan,

been using Bowpad for a few years now... and have put together a new-build Windows 8.1 64bit box today. Have loaded Open Shell, BitDefender, Moo0 System Monitor and LibreOffice; all working OK, now Bowpad 2.5.1 downloaded today.

This crashes on startup (?) but my main work machine is fine with 2.5.1. That does not use Open Shell though. Reinstall / repair does not help

The error report from Windows is:

Problem signature:
  Problem Event Name:	BEX
  Application Name:	BowPad.exe
  Application Version:	2.5.1.2151
  Application Timestamp:	5e8c54cf
  Fault Module Name:	StackHash_75c7
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	PCH_47_FROM_ntdll+0x0003CEEC
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	2057
  Additional Information 1:	75c7
  Additional Information 2:	75c7b2acad8c1412e3059c2204320208
  Additional Information 3:	1b99
  Additional Information 4:	1b99e99f6b223154fc5f1e8bd3ec3462

Hope this is useful!

:)
brodders

**Comment by stefankueng** [comment]
Please get the procdump tool from here:
https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

then open a command prompt and type:
procdump -e -ma -w bowpad.exe

then start BP and get it to crash. Then zip and upload the dump file somewhere and post the link here so I can get a look at the cash.

**Comment by wmjordan** [comment]
It should be nothing to do with _Open Shell_. I also use that application for years. Nothing wrong with BowPad.

**Comment by brodders61** [comment]
Hi,
Found the problem - crash occurs when starting the 32bit version on a 64 bit machine (Win 8.1)
With 64bit code, BP runs OK. Odd...

**Comment by wmjordan** [comment]
> when starting the 32bit version on a 64 bit machine

Do you have both the 32bit version and the 64bit version on your machine, AND you have downloaded a language file? I verified that both versions could not co-exist if you had any language file installed. (see #2)

If so, please try to remove the language file located in the %appdata%\bowpad folder. Or uninstall BowPad and download the portable version and see whether it works.

**Comment by stefankueng** [comment]
the fix for this is part of the submodule:
https://github.com/stefankueng/sktoolslib/commit/92c7afe88caa538ab512a42bfbe406a071dd53de
So no commit in this project for the fix.
