### ISSUE TITLE
Toggle folds for  level 1 to 9 not woks for Python or CoffeeScript like files that use indentation

### ISSUE THREAD

**Issue by zufuliu** [stefankueng/BowPad#61]
`static bool Fold(std::function<sptr_t(int, uptr_t, sptr_t)> ScintillaCall, int level2Collapse = -1)` at
https://github.com/stefankueng/BowPad/blob/master/src/Commands/CmdFolding.cpp#L30
doesn't handle these file correctly, 

`ScintillaCall(SCI_GETFOLDLEVEL, line, 0)` for these file (search `IndentAmount` in scintilla\lexers folder) returns the indentation count, not the level like C/C++.

See other discussions on
(BSD 3-Clause) https://github.com/zufuliu/notepad2/issues/82 current code at https://github.com/zufuliu/notepad2/blob/master/src/Edit.c#L7200
(GPL) https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1898

I think you can also replace [SCI_TOGGLEFOLDSHOWTEXT](https://www.scintilla.org/ScintillaDoc.html#SCI_TOGGLEFOLDSHOWTEXT) with [SCI_SETDEFAULTFOLDDISPLAYTEXT](https://www.scintilla.org/ScintillaDoc.html#SCI_SETDEFAULTFOLDDISPLAYTEXT) (since Scintilla 4.1.5, https://sourceforge.net/p/scintilla/feature-requests/1272/)

**Comment by zufuliu** [comment]
The code is moved to https://github.com/zufuliu/notepad2/blob/master/src/Edit.c#L7281
[SCI_GETLASTCHILD](https://www.scintilla.org/ScintillaDoc.html#SCI_GETLASTCHILD) is the key to avoid stack overrun.

**Comment by stefankueng** [comment]
I've read about the stack overrun in notepad2 issue, but I don't see how or where a stack overrun could happen.

**Comment by zufuliu** [comment]
OK, I checked your latest code, it will not overrun.
But I think the code for toggle folding all and toggle level N can be separated. e.g. for toggle top level (level 1, but the menu is level 0. personally, I think level 1 to 10 is better than 0 to 9), with SCI_GETLASTCHILD, you can avoid checking all children lines.

`ScintillaCall(SCI_TOGGLEFOLDSHOWTEXT, headerLine, (sptr_t) "...");` is not needed sine it's same with the default text.
`ScintillaCall(SCI_SETDEFAULTFOLDDISPLAYTEXT, 0, (sptr_t) "...");` only need be called once like `SCI_SETCODEPAGE`, actually text set var `SCI_SETDEFAULTFOLDDISPLAYTEXT` is considered already encoded with same code as `SCI_SETCODEPAGE`. (possibly, this is by design, manually click minus box don't show ellipsis.)

**Comment by stefankueng** [comment]
I intentionally use SCI_TOGGLEFOLDSHOWTEXT since I'd like to extend the text depending on what part is collapsed. Haven't had the time to implement it yet though, but soon.
