### ISSUE TITLE
Items in the BowPad Titlebar

### ISSUE THREAD

**Issue by shujaatak** [stefankueng/BowPad#62]
I am trying to create a custom window frame but I am facing some issues. BowPad draws Quick-Access-Toolbar in the Title bar region and I wonder if you use a custom frame.

1: Is the BowPad Window  [dwm/customframe](https://docs.microsoft.com/en-us/windows/win32/dwm/customframe). If yes, in which file I can find the code for it?
2: Can you please tell where in the code I should look for adding more items to the titlebar?

![screenshot2](https://user-images.githubusercontent.com/14161646/80290287-d4325c80-875d-11ea-924e-ad103d4fb64e.png)

Best regards!

**Comment by stefankueng** [comment]
BP uses the Windows Ribbon Framework:
https://docs.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-introduction

The "source" for the ribbon is here:
https://github.com/stefankueng/BowPad/blob/master/src/res/BowPad.xml

**Comment by shujaatak** [comment]
So it's not custom.
