### ISSUE TITLE
Problem with Custom Commands

### ISSUE THREAD

**Issue by sshamblen** [stefankueng/BowPad#64]
I can enter custom command and they appear under the run menu. When I restart BowPad, the first custom command has "Custom Command 0", even though a name was specified. If I click on "Configure Custom Commands" and then click OK with no changes, it will appear properly with the name. It seems the name of command 1 is not getting properly initialized on start. Awesome editor, BTW.

**Comment by stefankueng** [comment]
this works fine for me. Are you sure you're using the latest version of BowPad (2.5.1)?

**Comment by sshamblen** [comment]
Hi Stefan.

Yes. I am using 2.5.1.2151 (64 bit).

I am running the application from the following directory (C:\Users\sshamblen\Apps\BowPad), as this is a work computer (and I am an unprivileged user).

If at all helpful, here are the first several lines from my settings file:

[CustomLaunch]
Command0=bash.exe -c 'pspprunner'
Command0Label=Run PSPP
Command1=bash.exe -c 'rrunner'
Command1Label=Run R
Command2=file:///C:/Users/sshamblen/Apps/StatsHelp/index.html
Command2Label=Statistics Help
Command3=
Command3Label=
Command4=
Command4Label=
Command5=
Command5Label=
Command6=
Command6Label=
Command7=
Command7Label=
Command8=
Command8Label=
Command9=
Command9Label=
websearch=http://www.google.com/search?q=$(SEL_TEXT_ESCAPED)

It will not show “Run PSPP” when I start the program. If I act like I am going to configure the commands under Run and then I just click OK, the “Run PSPP” appears.

Thanks,
…Steve

**Comment by stefankueng** [comment]
tried with your ini settings. Still: it works for me here and in my office.
Are you on Win10?

**Comment by sshamblen** [comment]
Yes, I am using Windows 10. …Steve

**Comment by stefankueng** [comment]
What happens if you click the run button again without going into the config dialog? Just so the dropdown shows again. Does it then show the text correctly?

**Comment by sshamblen** [comment]
That does not cause it to populate appropriately. I also tried seeing if clicking on “Custom Command 0” causes it to properly populate the next time, but no dice.

…Steve
