### ISSUE TITLE
Normalizing new line search in RegEx mode

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#65]
Give the following code snippet:
````
abc
cde
cex
acc
````

If we are to search for a line which ends with `c`, we will have to use expression `c\r\n`. If we search with `c\n`, which is more intuitive and concise, we get nothing.

Although `c\r\n` reflects the fact that the document is using `Windows (CRLF)` as new lines. For convenience, it is great if BowPad can also perform new line search with `c\n` and internally replaces `\n` to `\r\n`.

**Comment by stefankueng** [comment]
what if the file has inconsistent newlines? Or a file that actually uses only LF and not CRLF?
Why don't you just use the $ (end-of-line) regex char and do a regex search instead?

**Comment by wmjordan** [comment]
If the file has inconsistent newlines, it should be normalized before search. It is essential in the current implementation too.
In most cases, a file uses only LF, CR, or CRLF. It could be detected by BowPad now, and before searching, the `\n` could be replaced to corresponding new-line character sequence and then perform the actual search.
The `$`, which means the end of the content not the end of line, hence it will not work.

**Comment by stefankueng** [comment]
normalizing before a search is way too slow for big files.
you could use `(\n|\r\n)` as your search string instead of just `\n`

**Comment by wmjordan** [comment]
> If the file has inconsistent newlines, it should be normalized before search

Sorry for not having stated the situation clear enough, I meant this should be done MANUALLY before searching.
And for the most common case (situation 2), automatically replacing the search expression is easier than normalizing the new lines for the whole document. Thus I think it is viable to do so.

**Comment by wmjordan** [comment]
We could take advantage of the detected new line pattern and internally replace the `\n` in the expression to corresponding pattern.

For instance, as the following screenshot shows. The document is using CRLF as new lines. So, when searching for `\n`, BowPad could automatically change the expression to `\r\n` internally before performing the actual search operation.

![shot](https://user-images.githubusercontent.com/12182730/82113779-3560b500-978b-11ea-86a9-b562857fcc3a.PNG)

**Comment by stefankueng** [comment]
So I guess replacing all "\n" in the search string with "(?:\n|\r\n|\n\r)" should work. But only if searching in regex mode and of course only if there are no "\r" chars in the search string to begin with.
However I would like to be able to circumvent this automatism. I'm thinking about using a special char as the first char in the search string. E.g. if you enter a '@' as the fist char in the search string, it won't do the replacement. Not sure about the '@' char though - any suggestions?

**Comment by stefankueng** [comment]
I think I'll go with the '~' char...

**Comment by wmjordan** [comment]
> I'm thinking about using a special char as the first char in the search string

I don't think it is necessary in most cases.
1. General regular expression does not have such a character.
2. What if we are really searching something begin with `~`?
3. Ordinary users won't get any hint, especially when BowPad does not have a helper button which pop up a menu to insert expression patterns when clicked. (The search functions in most editors, such as Microsoft Word, PsPad, EditPlus, UltraEdit, etc., have such kind of buttons. Please see the screenshot below) So, the users will not get helped and will probably feel the same frustration when searching with multi-line expressions as they do nowadays.
![shot](https://user-images.githubusercontent.com/12182730/82134855-e40a0180-982e-11ea-8251-853f109c83ca.PNG)

I've been using EditPlus for more than 20 years, which always uses `\n` to denote the new lines. In this 20 years, I have never met with a situation which required me to distinguish `\r` or `\n`.

Were distinguishing of new line characters necessay, I suggest adding a checkbox to indicate that. However, I still think that type of distinguishability is of little use.

**Comment by stefankueng** [comment]
ok, I'll remove the ~char handling...
