### ISSUE TITLE
Feature Request: Join lines with comma

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#66]
Is it possible to join lines with comma or and quoted comma?

For instance, given the following lines:
````
123
345
234
````

After executing "join with comma", we get:
````
123, 345, 234
````

After executing "join with comma, quoted", we get:
````
'123', '345', '234'
````

The results of the above commands can be used in SQL `in` expressions, such as:
````SQL
SELECT * FROM T where id in (123, 345, 234);
SELECT * FROM T where name in ('123', '345', '234');
````

**Comment by stefankueng** [comment]
just use a regex find/replace:

search for `(\d+)\r\n`
replace it with `$1, ` or "`$1", `
