### ISSUE TITLE
Feature Request:  Better tab view style

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#70]
Current appearance of tab is not good in any theme. It's better if the appearance is changed like visual studio code.

**Comment by wmjordan** [comment]
I just cloned and compiled the source code.
The new style has a circle on the tab which does not look good and is a bit too odd and eye-catching for me.

![捕获](https://user-images.githubusercontent.com/12182730/91142546-87e33300-e6e3-11ea-9d24-2554ad6e592c.PNG)

In Visual Studio Code, they use a cross on the tab and not circles.
![捕获](https://user-images.githubusercontent.com/12182730/91142723-d5f83680-e6e3-11ea-996e-dc25eaf77287.PNG)

I think the crosses on the tabs in previous versions are quite good looking. There's nothing wrong with them. Please bring them back.
![捕获](https://user-images.githubusercontent.com/12182730/91142887-312a2900-e6e4-11ea-8018-e6535fafd6d9.PNG)

**Comment by wmjordan** [comment]
I think it is good to use the following value:
````C
TabCtrl_SetPadding(*this, 7.0f * m_dpiScale, 0);
````
And use the following code to draw a cross no matter the tab is hovered or not:
````C
    switch (buttonType)
    {
        case TabButtonType::Selected:
        case TabButtonType::Close:
            ::DrawText(pDrawItemStruct->hDC, L"\u274C", 1, &closeButtonRect, DT_SINGLELINE | DT_NOPREFIX | DT_CENTER | DT_VCENTER);
            break;
````
![捕获](https://user-images.githubusercontent.com/12182730/91145593-4903ac00-e6e8-11ea-9ddf-1c5ee337fa50.PNG)

The thing left to do is to make some padding at the right of the cross (sorry I am new to the source code)--please take a look at the second screenshot in VS Code, which has a decent margin around the close button on the tab.

**Comment by wmjordan** [comment]
I tested the version on Windows 7 and found that the cross was displayed as an "undefined" character.
![捕获](https://user-images.githubusercontent.com/12182730/91146906-207cb180-e6ea-11ea-887e-87db3ed190e4.PNG)

Maybe you should use the classic "Marlett" font and use 0x72 to display the cross.

**Comment by wmjordan** [comment]
I found the place to reposition the close button, and tweaked the value to the following.
````C
CloseButtonZone(): m_width(11), m_height(11), m_fromRight(7){};
````

And finally I got this:
![捕获](https://user-images.githubusercontent.com/12182730/91171709-8464a180-e70d-11ea-85fb-5649a587415a.PNG)

The left and right padding are almost the same on the active tab now.

**Comment by wmjordan** [comment]
I observed the behavior of the close button in VS Code.

1. The close button is a cross when the file is active, and hidden when inactive.
2. If the file is modified, the cross changes to a circle, no matter the file is active or not. No `*` is displayed.

Please consider modifying the code to make the tab bar behave like that.

1. No longer use `*` to indicate whether the file is modified but not saved. (The `*` will not be visible in BowPad if the file name is _toooooooooooooo.long_).
2. Use cross instead of circle when the file is not modified.
3. Circles will be used on files that are modified but not saved.
