### ISSUE TITLE
Feature Request: Keep the file last opened and keep the edits

### ISSUE THREAD

**Issue by mind-c** [stefankueng/BowPad#73]
When I open a few files and make some edits, I hope that the editor can automatically keep the edits and exit, but not asking for saving it (It may keep the temporary files somewhere). The next time I open the editor, everything is just like what before I exit. In Notepad++ and Sublime Text 3, they do so. 
Most of the time I just want to write something not so important to use next time. That's what the meaning of this feature is, you know, keep them in the text editor is convenient.

**Comment by wmjordan** [comment]
There's a problem in the current implementation.
I upgraded from the old version and found that the Auto Save checkbox was checked (but disabled), but I did not check the Restore Session button. Thus the Auto Save actually ineffective.

If I create a new document, type something into it, then close BowPad without saving. It will not ask me to save the document. The document will not be restored the next time when BowPad is opened either.
