### ISSUE TITLE
Color is not correct in Dark theme

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#76]
Background or foreground color is not correct in ribbon UI (Other tab).
![image](https://user-images.githubusercontent.com/28701482/91372448-40c18300-e846-11ea-80ee-d29a80b77192.png)

**Comment by stefankueng** [comment]
That's a problem of the ribbon itself. Can't really do anything about that :(

**Comment by kitepad** [comment]
I see it is correct in office, for example:
![image](https://user-images.githubusercontent.com/28701482/91511393-2523ae80-e912-11ea-8996-ccba132c0323.png)

I don't know why.

**Comment by stefankueng** [comment]
office does not use the windows ribbon - they have their own.

**Comment by kitepad** [comment]
Understand. Thanks.
