### ISSUE TITLE
new command to edit all marked words

### ISSUE THREAD

**Issue by stefankueng** [stefankueng/BowPad#78]
a selection of a word also marks all other occurrences in the current doc that match that selection.
Add a command which sets an edit cursor on all those occurrences at once (multi-edit).

**Comment by wmjordan** [comment]
This command has a problem.
Take the following text for example:
````
2020-08
2020-09
2020-10
````
Select the last "2020", execute the command and type "2021", the text becomes:
````
2021-08
2021-09
20212021-10
````

**Comment by stefankueng** [comment]
thanks for testing!
