### ISSUE TITLE
Crash @ language settings

### ISSUE THREAD

**Issue by Snookerfan** [stefankueng/BowPad#8]
Just after having downloaded BowPad I switched off Spell Checker then tried to change program's localization from English to German (Germany). At this stage, user needs to click "fetch remote languages..." first, since BowPad doesn't hold any other language than English by default. BowPad downloads a list of available languages which it presents moments later to select from. Immediately after having selected German it crashed as often as I tried. The same is true for any other language listed. Tested on Win10Pro x86, Version 1709.

**Comment by stefankueng** [comment]
Works fine for me.
If you have BowPad installed (not the portable version), check if the language file was downloaded properly in `%appdata%\BowPad\`. Maybe try to open it in a text editor: sometimes firewalls deliver not the file but a html page informing you that the file is being checked first. But BowPad can't handle those html pages and then it tries to use that html page as the language file.

For the portable version, the language file is downloaded to the same directory as the BowPad.exe is residing.

**Comment by stefankueng** [comment]
Ok, found a way to reproduce the problem.
