### ISSUE TITLE
Sort fields

### ISSUE THREAD

**Issue by Ekevanbatenburg** [stefankueng/BowPad#80]
A couple of my textfiles have different information in different columns.

I would like the extension as in PSPad: the option in 'sort Lines' that I can specify a columnnumber where the sort will start.

Thanks for a very nice editor.......Eke van Batenburg

**Comment by stefankueng** [comment]
just select the lines you want sorted, then only those selected lines are sorted.
Only if nothing is selected then the whole document is sorted.

**Comment by Ekevanbatenburg** [comment]
Probably I was not so clear in my description.
This is what I meant:
Imagine a file with the following 3 lines:

Amsterdam--2020.07.13  Pancakes
Berlin--------2020.04.15  Sweets
Aarhuus-----2019.07.01  Drinks

To sort on date there is a field in the "SortLines"  window where I can enter  12
To sort on food there is a field in the "SortLines"  window where I can enter  24

I hope this clarifies my wish .
Yours....Eke van Batenburg
