### ISSUE TITLE
No Alert for unsaved when click system close button

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#81]
Version: 2.6.3. Portable binary and self build from source code

You can repeat , 
1. Open a new or existing file
2. modified content.
3. click File-Exit, or close main window by Alt+F4, or Sytem Menu at left corner or close button at right corner.
Expected : alert for unsaved files.
Actual : Bowpad window is closed without any warning.

**Comment by stefankueng** [comment]
already fixed, see here: https://github.com/stefankueng/BowPad/issues/73#issuecomment-685561777

**Comment by stefankueng** [comment]
as a workaround: enable "load session on start", then the "auto-save" button gets enabled. Then you can configure the feature as you like it.
The problem happens if you have "load session on start" disabled but the new feature is enabled by default, so there's a conflict.

**Comment by wmjordan** [comment]
@stefankueng The bug could frustrate some users. Maybe you should update the released file here and on your site.

**Comment by stefankueng** [comment]
@wmjordan will do...
