### ISSUE TITLE
Help: How can I enable coolsb in FileTree to get same view with ScintillaWnd?

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#83]
In some scenario (if I install some theme engine, such as stardock and apply a theme), scrollbar view of file tree is different with editor. I know coolsb is used in editor. So I hope using coolsb to replace system scrollbar of filetree.

**Comment by stefankueng** [comment]
the original coolsb lib uses the detour lib to inject itself into other controls.
I don't use that in BP however for various reasons.
You can still use the original BP if you like: https://github.com/jsleroy/CoolSB

**Comment by kitepad** [comment]
Thanks.
