### ISSUE TITLE
Feature Request: Change font size for ribbon menu and all context menu

### ISSUE THREAD

**Issue by kitepad** [stefankueng/BowPad#84]
The current font size is small and cannot be read well on a high dpi screen .
It's better to enlarge all menu font size by default or can configure it by user .

**Comment by wmjordan** [comment]
The size of fonts are automatically enlarged on my computer.

Please take a look at the following screen shot.
The left part was on a remote machine accessed via remote desktop, which is using normal 96 DPI.
The right part was on my computer, using 120 DPI. You can see that the labels and icons are larger.
![捕获](https://user-images.githubusercontent.com/12182730/92572439-07156100-f2b7-11ea-93ad-fab1077d372b.PNG)

**Comment by kitepad** [comment]
My laptop system is win 10 insider preview 20206. If I enlarge all text by win 10 settings, you can refer below screen shot:
Other text (Title bar, file tree) are enlarge, but menu and editor is not.
Text is scale 120% as below:
![image](https://user-images.githubusercontent.com/28701482/92576214-d126ab80-f2bb-11ea-9f5e-c1e22d9007fb.png)
Text is scale 225% as below :
![image](https://user-images.githubusercontent.com/28701482/92576014-94f34b00-f2bb-11ea-9448-4544e0bcb742.png)

**Comment by kitepad** [comment]
I am trying Ribbon sample app which build by win32-framework, same issues is exist. But MFC ribbon demo app don't have same issue, the sample app is built by vs studio 2019 community version. Maybe, it is Ribbon's problem, i'm not sure.

**Comment by stefankueng** [comment]
this is a problem of the Windows ribbon framework, nothing I can do about that. Sorry.

**Comment by kitepad** [comment]
Unfortunately we cannot fix these issues because ribbon framework. So I investigate  other approach to avoid same issues, below idea is from other software. Maybe, it's a better replacement for ribbon and can be as Command Palette.
![image](https://user-images.githubusercontent.com/28701482/92841403-d9dec500-f414-11ea-87c0-3428a2a0c18d.png)

**Comment by wmjordan** [comment]
I am sorry that I have to say I like the ribbon bar.
Please don't _replace_ it with the above thing.

**Comment by wmjordan** [comment]
> MFC ribbon demo app don't have same issue

It is really a problem that the labels on Ribbon Bar are too small in BowPad shown as your screen shots.
Could you point me to the ribbon demo and let me see whether I can do something to help?

**Comment by kitepad** [comment]
My mean is provide two style for different users. For example, 
1. For ribbon fans, you can use original UI
2. For other user (like me), use quickly navigation UI

We can toggle two UI modes, we can use UI_PKEY_Viewable to hide ribbon and switch to other ui.

**Comment by kitepad** [comment]
Only use vs studio 2019 community MFC app wizard to generate app with ribbon.
Win 10 : enterprise insider builder 20206
VS Studio : 2019 community 16.7.3
make Text size is 225%
![image](https://user-images.githubusercontent.com/28701482/92861426-0c47ec80-f42c-11ea-866c-f53eca421901.png)

make text size is 120%
![image](https://user-images.githubusercontent.com/28701482/92861506-25e93400-f42c-11ea-82d7-66a858f8e358.png)

**Comment by wmjordan** [comment]
Would you mind attaching the code files here?
I don't have MFC installed.
But hopefully the difference does not have anything to do with MFC.
