### ISSUE TITLE
Possible to force refresh the file tree, or add a small toolbar for the file tree?

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#85]
There had been quite a few times that I renamed or deleted a file or folder outside of BowPad.
When I got back to BowPad, I could not find a way to refresh the file tree.

Is it OK to add a small toolbar on top of the file tree and offer the following buttons?
1. [..] Goes to the parent folder (with this button, we don't need the ".." item in the file tree, thus the toolbar won't take too much extra space).
2. [Refresh] Refreshes the file tree.
3. [Locate] Reveals the active file in the file tree.
4. [Collapse all] Collapses all tree items.

**Comment by stefankueng** [comment]
File->Reload also refreshes the file tree (or F5 if you prefer).

**Comment by wmjordan** [comment]
Alright.
Thanks for the tip.
