### ISSUE TITLE
BowPad got hung

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#86]
It happened to me quite some times, but infrequently, that BowPad hung and consumed quite a lot of CPU resources.

The window of BowPad was closed when this issue occurred, but the process of BowPad seemed to have run into an infinite loop thus it refused to quit. The CPU fan within my laptop ran and I hereby found that.

I will try to dump the process the next time it happens.

**Comment by wmjordan** [comment]
I met with this issue again today and I managed to create a minidump of BowPad.
[BowPad.zip](https://github.com/stefankueng/BowPad/files/5551739/BowPad.zip)
<img width="381" alt="shot" src="https://user-images.githubusercontent.com/12182730/99356220-c7857980-28e4-11eb-9a2b-e738c460f47f.png">

The above stack appeared to imply that there was something wrong in the file tree.

What was happening while it got hung?

1. I opened a file in BowPad.
2. I deleted that file from Windows Explorer.
3. I tried open another file with BowPad.
4. BowPad got hung.

It seemed that BowPad was trying to refresh the opened file, which had already been removed.

**Comment by stefankueng** [comment]
if you have the pdb file as well, that would be great. Without it, the dump is pretty useless.

**Comment by wmjordan** [comment]
pdb and exe below:
[BowPad.bin.7z.zip](https://github.com/stefankueng/BowPad/files/5557019/BowPad.bin.7z.zip)

**Comment by stefankueng** [comment]
thanks. that helped.
