### ISSUE TITLE
How to write a plugin to extract text from active document to a new document?

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#91]
It seems that there is not enough API to do this.

**Comment by stefankueng** [comment]
what API(s) is/are missing?
if you have a wish list for new APIs, please post them here.

**Comment by wmjordan** [comment]
There are API to manipulate document in active window, but I could not find one to manage scintilla instances in other document windows.

**Comment by stefankueng** [comment]
Just noticed: you'll need an API to create a new empty tab. I'll add that now.
Since there's only one Scintilla instance at a time, you can not manipulate text in "other" tabs, meaning you have to first extract the text from the current tab, then create a new one (which will make that tab the active one automatically) and then insert the text you've extracted in the new active tab.

**Comment by stefankueng** [comment]
maybe if you describe what exactly you're trying to do, I can better understand what APIs you need?

**Comment by wmjordan** [comment]
That's the thing.

I am using BowPad to analyze quite a few log files. Since #59 is not yet implemented, I'd try to make a plug in to do so.
The planned procedure of the plugin is:

1. Select something as the search phrase in the document,
2. Find all lines containing the phrase in the document.
3. Open a new tab.
4. Put all those lines into that place.

Similar result like the following DOS command:

````bat
TYPE thefile.txt>findstr "THE SELECTED TEXT TO FIND"
````

**Comment by wmjordan** [comment]
If there's an API which allows us to create a dialog to gather some simple text, that will be better.

So we can present a dialog, like:
````
Find: [ ____________ ]
[ ] Case sensitive
[ ] Use Regex

[[ Search ]]       [[ Cancel ]]
````
Controls in the dialog could be passed as will two arrays like:
````js
var params = new[] {
   [ "Find:", "" ], // default value is empty text, the string also implies that a text box should be created
   [ "Case sensitive", false ], // false implies that a checkbox should be created
   [ "Use Regex", false ]
};
var buttons = new[] {
   [ "Search", 1, true ], // button text is "Search", it returns 1 and close the dialog when clicked, it is the commit button
   [ "Cancel", 0 ] // button text is "Cancel", returns 0
};
var dialogResult = BowPad.CreateDialog(params, buttons);
alert (params[0]); // pop up a alert box with the text of the Find box
alert (dialogResult); // alert 1 if "search" is pressed, 0 if "cancel" is pressed
````
The selected text is automatically filled into the text box besides `Find:`.
Pressing `[[Search]]` button will return a value like 1 to the script and the `[[Cancel]]` button will return 0.
The `params` array will be replaced by values of the corresponding controls when the dialog is closed. For instance, the text in the `Find` box is "abc", and `Use Regex` checkbox is checked. The `params` can be the following array: `[ "abc", false, true ]`.

**Comment by stefankueng** [comment]
Well, creating a dialog on-the-fly is not something I'd like to implement in pure win32 code. Also, your example seems simple but you already assume a certain layout of the controls without specifying it. So you can see that this would be a little bit complicated.

But with the recent commit implementing the new command OpenNewTab, you can get the result you need with this little script:

```
function Execute()
{
    var selText = BowPad.SciGetSelText();
    if (selText.Length == 0)
        return false;
    var extractedLines = "";
    var docLen = BowPad.SciGetLength();
    var foundPos = BowPad.SciFindText(0, 0, docLen, selText).toArray();

    while (foundPos[0] >= 0)
    {
        var line = BowPad.SciLineFromPosition(foundPos[0]);
        var lineText = BowPad.SciGetLine(line);
        extractedLines = extractedLines + lineText;
        foundPos = BowPad.SciFindText(0, foundPos[0]+1, docLen, selText).toArray();
    }
    BowPad.OpenNewTab();
    BowPad.SciInsertText(0, extractedLines);

    return true;
}
```

**Comment by wmjordan** [comment]
> you already assume a certain layout of the controls without specifying it

We are not to make HTML like interfaces. To simplify things, I think it is OK to make some _assumption_s, we may even expect that the layout is one control in a row (label+textbox, or checkbox with label, or button, etc.).

**Comment by wmjordan** [comment]
After a second thought, I feel that your concern is very reasonable.

But it will still be great if we can utilize something which allows interaction. For instance, presenting a dialog containing a control like the Properties in Visual Studio--we don't need a thing that is 100% resembling that, a stripped version is OK.

**Comment by wmjordan** [comment]
> you can get the result you need with this little script

Thank you very much for this script. Without your help, it could take me hours! :)

I slightly modified the script to get better performance and completed the plugin.

[SearchSelection.zip](https://github.com/stefankueng/BowPad/files/5369773/SearchSelection.zip)

**Comment by wmjordan** [comment]
I found that BowPad was lacking the `SciSetSavePoint` function, and consequently the above script ended with an error.
Could you add that?

**Comment by stefankueng** [comment]
SciSetSavePoint was already implemented, but a bug prevented it from being used. Fixed now.

**Comment by wmjordan** [comment]
OK. It works great now.

**Comment by wmjordan** [comment]
Hi, the log files are generated by my programs, which are tab separated, something like the following:

````
17:01:17	PUSH	[Debug]	Connected to 127.0.0.1:7801
17:01:17	PUSH	[Info]	Begin receiving from 127.0.0.1:7801
17:08:20	LED	[Info]	Send FE0180017CF99EA38C0D0747BE0175BE5A504DF800FE 127.0.0.1:50380
17:08:20	LED	[Info]	Receive FE0100017CF99EA38C0D0747BE0175BE5A504DF804B2E2CAD40008E32C916644DB3DE4FE 127.0.0.1:50380
````

**Comment by wmjordan** [comment]
I just found a problem about the plug in script.
If the same line contains the selected text in various places, it will be extracted multiple times.
I think the subsequent search after meeting an occurrence should begin at the end of the line. Could you please tell me how to implement that?
````js
foundPos = BowPad.SciFindText(0, foundPos[0]+1, docLen, selText).toArray();
````

**Comment by wmjordan** [comment]
Another problemwas that I tried to select "17" from the code in the [previous "log" snippet](https://github.com/stefankueng/BowPad/issues/91#issuecomment-708742887), nothing but an empty document was returned.

**Comment by stefankueng** [comment]
use SciLineFromPosition(foundPos[1]), add +1 and then call SciPositionFromLine(nextLine) to get the next search start position.

As for nothing returned in your last comment: I don't have not enough information to guess as why this happened. Is it reproducable?

**Comment by wmjordan** [comment]
Thank you for the information. I will try to figure it out.

The problem in the last comment could be reproduced by the following steps:
1. New document,
2. Paste the following stuff into the editor:
````
17:01:17	PUSH	[Debug]	Connected to 127.0.0.1:7801
17:01:17	PUSH	[Info]	Begin receiving from 127.0.0.1:7801
17:08:20	DATA	[Info]	Send FE0180017CF99EA38C0D0747BE0175BE5A504DF800FE 127.0.0.1:50380
17:08:20	DATA	[Info]	Receive FE0100017CF99EA38C0D0747BE0175BE5A504DF804B2E2CAD40008E32C916644DB3DE4FE 127.0.0.1:50380
````

3. Select any `17` in the editor.
4. Click the SearchSelection plugin.
5. A new document is created but no text are there.

It seems that if the selection happens to be **at the beginning of the document**, the SciFindText will fail.

**Comment by stefankueng** [comment]
fixed the bug with SciFindText, also updated the plugin.

**Comment by wmjordan** [comment]
Thank you for the fix and updating the plugin.

I changed the place where opening a new document window and putting the extracted content to the following:

1. The new window will only open when two or more lines are extracted.
2. Previously I missed assigning the parameter to the `join` function, consequently a comma was inserted between each extracted line. It is fixed now.
3. Clearing the undo buffer to release some memory.

````js
    if (extractedLines.length > 1) {
        BowPad.OpenNewTab();
        BowPad.SciInsertText(0, extractedLines.join(""));
        BowPad.SciEmptyUndoBuffer();
        BowPad.SciSetSavePoint();
    }
    else {
	BowPad.alert("Only a single instance is found in document.");
    }
````

**Comment by wmjordan** [comment]
So far, so good.
Closed this issue.

**Comment by wmjordan** [comment]
[SearchSelection.zip](https://github.com/stefankueng/BowPad/files/5593692/SearchSelection.zip)

I've updated the plugin to alter its behavior by keyboard modifiers.
Ctrl+execute: Match whole word;
Shift+execute: Case sensitive.

Please check out the .desc file in the zip file to see whether it is possible to display multiline description in the install plugin dialog.
