### ISSUE TITLE
Dynamically reload plugin scripts

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#94]
During the development of plugin scripts for BowPad, I found it somewhat inconvenient.
The script was cached in memory and not reloaded from disk after I made modification to it. I had to restart BowPad to reflect the changes.

Is it possible to cache the modification time of the script file and reload the script when it is changed, so we don't have to restart BowPad?

**Comment by stefankueng** [comment]
I've already started on this yesterday, but my first attempt wasn't good enough.
While I'm at it: also reload the settings if the 'settings' file is edited directly, and also reload the styles if a *.bplex file is edited.
