### ISSUE TITLE
Distinguising items in Tabs drop-down

### ISSUE THREAD

**Issue by wmjordan** [stefankueng/BowPad#99]
Please add some ways for distinguishing items in the tabs drop-down.

In the following situation, it is hard to tell where the "status.txt" files are.
<img width="47" alt="shot" src="https://user-images.githubusercontent.com/12182730/97519007-69473400-19d3-11eb-9ecb-85e38a872cd1.PNG">

The best way may be listing the first ancestor folder name that are differ from each other, for those items having the same file name.

An alternative but easier approach is providing tool tips for items.

**Comment by stefankueng** [comment]
tooltips don't seem to work: the ribbon framework never asks for them for dropdown items :(

**Comment by wmjordan** [comment]
Thank you for your efforts!
It is much more efficient now.
